#+TITLE: Backwards Waveshine OOS

* Waveshine OOS Backwards

Waveshine OOS is super good. Sometimes they'll hit behind your shield in an attempt to dodge this. Being able to do it backwards makes it much more flexible. Doing it properly backwards is underused, the proper way to do that is to turnaround in the shine, rather than wavedashing backwards like in a normal waveshine.

#+BEGIN_EXPORT html
<iframe width="560" height="315" src="https://www.youtube.com/embed/-h4VvMdtA4E?si=Y3G1BsS8drViw84F" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
#+END_EXPORT

#+BEGIN_EXPORT html
<iframe width="560" height="315" src="https://www.youtube.com/embed/tHwVdKb7ffQ?si=f5GhEIgRxtas6A2e&amp;clip=UgkxjZaxhh0csp2u9hmV0p4fpaRByB-y3wzw&amp;clipt=EMmUJxjwvyc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
#+END_EXPORT

#+BEGIN_EXPORT html
<iframe width="560" height="315" src="https://www.youtube.com/embed/PAOia-60vPo?si=Q5OEm66uSZCXkxNX" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
#+END_EXPORT

** Why is this better

People do not do the turnaround waveshine forwards because it's 3 frames lower than waveshine backwards, and you have to make sure your jump input doesn't occur during the turnaround frames (otherwise it will get eaten and you'll just stand there).

However, waveshine OOS is different from a normal waveshine: you can't jump on the first two frames, since you are airborne and will get doublejump instead of jumpsquat. So, you have to wait anyways. You might as well input the turnarund during these frames. The subsequent jump will only be slower by 1 frame (turnaround takes 3 frames), but you will be facing forwards afterwards. That is, doing a backwards waveshine requires you to burn a frame turning around anyways, so they are equivalent timing-wise.

In addition to being equivalent timing-wise, it's much easier to execute from out of shield, since you can input your wavedash angle after hitting the shine oos, and it will turnaround for you. The stick movement for a normal backwards wavedash from shine out of shield is a 3f window (if you input on first frame of jumpsquat, the turnaround takes priority over the jump, so you have until the airdodge frame to input the stick input). In comparison, with the turnaround, you have the entire duration of hitlag to input the wavedash angle, which makes it much much easier (I think turning it to like a 9f window? It's pretty much unmissable with some practice, the shine oos itself is much harder).
