#+TITLE: Advanced Memory Palaces

* Book Review: Advanced Memory Palaces

Joe Reddington's /Advanced Memory Palaces/.

** Context

On the back of this book, there is a paragraph which leads with the following:

/This should be the second book you read on memory techniques. It doesn't matter which other book you read first, but you'll find it easier if you've had some practice of both using memory techniques well and discovering their limitations./

Before reading this book, I had read Joshua Foer's /Moonwalking with Einstein/, and Jerry Lucas & Harry Lorayne's /The Memory Book/. The former was more narrative-driven and investigative, the second was more instructional but decided oriented at beginners. The book took a bit to arrive, so I also managed to get ahold of Lynne Kelly's /Memory Craft/. For my current ability, I developed my own PAO word list + got an ~8 minutes speed cards time, a 2:17 speed cards with a program which would spit my pegs out for me, and level 5 on Memory League for card memorization. 

Likewise, the book seemed to be about making analogies between data structures and mnemonics, which is a topic I had been doing in unscripted rants to my computer-knowing friends for the last several weeks. For all intents and purposes, I seemed like the ideal target for this specific book, and so I purchased it. I figured, if anything was too hard to use for me as a memory techniques user, this book would be overpromising as a good "second book"; if anything was too hard for me to understand as a machine learning researcher, then it was probably too in-the-weeds for memory sport people of other backgrounds. 

** 

