* A Take On Reasoning Models

A recent tweet from Shane Gu:

#+BEGIN_QUOTE
Internet tokens will run out, but even more valuable tokens are those CoTs inside people that produced those tokens. Reinforcement Fine-Tuning (RFT) is a semi-supervised approach to recover those missing CoT tokens. 99% of information is within people, not internet. 99% of the wisdom of a paper is within the authors, not the paper. This is why you should go NeurIPS. I'll be there, actively asking questions to extract high quality tokens behind their papers and other accomplishments. And yes this tweet was a PR for you to go to NeurIPS.
#+END_QUOTE

I think at least some degree of insight about this sort of thing can be 

** On Chess As Human Thinking Task

Being good at chess involves becoming strong at a lot of things: memorizing opening moves, recognizing a large number of common tactical motifs, having a clear understanding of strong strategic principles, etc. But, at least to some degree, Chess is a game which, in it's platonic ideal form, rewards a player for /thinking well/.

As a result, some proportion of chess coaching content is about how to /think better/. This is much harder to develop in a student compared to just making them grind tactics for thousands of hours: an analogy can be made to /[[https://en.wikipedia.org/wiki/Kuzushi][Kuzushi]]/ in Judo, where the delicate art of [[https://www.youtube.com/watch?v=3WSOpQuyPEE][unbalancing the opponent]] has grown more infrequently taught compared to simply making the Judoka stronger via physical training[fn:1]. 

The relationship between better thinking and better chess performance is surprisingly not that straightforward as a result. You can get pretty strong with relatively poor thinking, and vice versa; it's just one aspect of what makes up "you" as a chess player. A great book often given to intermediate players[fn:2] is IM Jeremy Silman's /The Amateur's Mind/, which is precisely a book on how weaker players often make thinking errors. 

In this book, Silman makes his students narrate their thoughts out loud as they are playing a game, in order to actively judge why they are making moves. It's really important here that these are thoughts made /before/ the move, rather than post-hoc justifications made /after/ the move. I think this book is a pretty good starting point for thinking about some topics around reasoning models, so I want to pull out some excerpts from it. 

** Excerpts

* Footnotes

[fn:2] referring to myself here, as a mostly-former chess player that peaked at an intermediate level.  

[fn:1] strong disclaimer: I am no Judoka, so if you object to this statement then I have no recourse to disagree; I just watched this video by [[largely been supplanted ][Tengu]] on the martial arts archeology of Kuzushi in Judo and thought it was very engaging.
