#+TITLE: Ambi Dextrous Postmortem

* Postmortem: Ambi Dextrous

Here's a running document of takeaways downstream of feedback from players playing my charts. 

** Recurring Themes

*** Mono Direction

This is probably the biggest takeaway to improve future charts. I did try to pay some attention to facing direction in my charting, but I think an insufficient amount for what is expected in modern charting. This was a repeated error across this pack, since my threshold for "how much is too much mono" threshold was something like "7 measures" and not like "a whole measure".

Switching facing direction is not super complicated, just use a second staircase with up and down swapped, etc.

*** Making Tech "Worth It"

Lots of tech in stuff like Number One Boy, Another Life, Fly Away, etc are all things which are straightforwardly easier to perform if you do not do the form. I had pretty much the exact opposite mindset making virtually all of these charts (e.g. "I'd like them to be easy to learn the form on! So they have to be unthreatening to skip and let you do the form only if you really want to"). 

*** Taste Stuff

I sort of expected people to not vibe with the 270 footswitch in /Another Life/, and it was definitely a risk I willingly took releasing the chart with it still in it. I included it in there because I find that pattern very fun to play, and I tried to make it resolve cleanly if doublestepped. But I think people were more averse to it than I was expecting. I think a good amount of this goes back to making tech worth it -- as fun as I found the 270 footswitch it does lead the player down a path and then punishing them for doing so, which is less subjective than I thought while making the chart.

*** Foot Dominance

There are a couple of charts in this pack where I make everything happen on the same foot (e.g. crossover onto right, crossunder onto right, cross over onto right, crossunder onto right). Making sure that the patterns are distributed so that they "happen" evenly is a good takeaway. In this case a lot of these were because I cut the song after writing the chart for the full thing, and then didn't properly adjust the chart after cropping the steps to match the now-cut version. I shouldn't do that, but I somehow got halfway through the project not realizing I should cut the songs at all, so hopefully this should be reduced in future charts. 

** (Charting Lowers) Number One Boy

Well, I originally had it as an 8, and people thought it was an 8, so I probably should not have lowered it just because I thought it was easy.

One of the more pressing things about this chart was that there's a lot of empty space where sounds happen, and adding a little bit more density to it would have made the chart more fun to play without adding way too much difficulty to it. Lots of spots where I could have added in 8th notes just to keep the beat moving, which would have been better for something around the 8 block. 

** (Charting BXF) Another Life (feat. Rema)

If I submit this to e.g. ITL 2027 I'm pretty sure I just have to remove the 270 footswitch. 

** (Charting BTs) Crazy (feat. PinkPanthress)

When you do hold taps, it's very helpful to have the first hold be a bracket to ensure the facing direction stays consistent.

** (Charting FS/KS) Fly Away

Kickswitches should be marked with holds on the second FS note, which are a really important part of making them sightreadable. Mine placement for these is also different. There are a few mines in this chart which do not really serve any purpose signalling anything about the pattern they're attached to. 

** (Charting No Tech) Heads Will Roll (A-Trak Remix)

If you are going to use two versions of the same type of pattern for a repeating musical phrase, make the hardest one come second. This chart starts with jumps and then goes down to normal steps, but it would probably be better dynamics to start with normal steps and then finish that section with jumps.

The mono in the stream for the part of the song where she says "heads will roll" is actually good, since it highlights the high note. Mono is not /never useful/.

** (Charting Stamtech) Overtime

The candle xo in the stream is fine, but what would have eased the player in to the idea is if the first set was a non-candle crossover / non-candle crossunder, and then in the second 2 repetitions instead of making the patterns just mirrored they were now candles. This adds variety and also escalates the chart to make it feel like its building.

** (Charting Stamtech) Stupid (can't run from the urge)

The slow BRFS before the snare roll needed a mine. I never needed this mine in pad testing because I knew it was there, but neglecting it made it confusing on sightread. A lot of the XO / SS stuff in the break sections are a good example of charts which don't really reward you for doing the tech.

This chart does everything on the right foot (because it originally did everything on the left foot later, but then I cut the chart in half).

The roll fs motif needed to be tutorialized a little bit, it makes sense once you're in it but it's a jumpscare because there's no roll tech anywhere earlier before it appears in the stream. I introduce everything else nicely before except for this, and it makes this feel out of nowhere. 

** (Charting Gimmicks) Time Traveler

The kickswitch section at the beginning of this not being marked by holds is really punishing, it makes it very difficult to read even without the gimmick. The entrance is "super mean" as Snap put it, and the mines would be easier to read if they were moved up a 32nd 

** (Charting Uppers) The Third Sanctuary

BRFS on up arrows needs to be limited to 2 at the most, because its so forcing for heels out it feels really uncomfortable to play. This is a meaningful difference from down BRFS, where you can do a lot of them and it's totally fine.

Triple candle BR FS is just too aggressive for the difficulty level called for by the chart.

The candle XOs at 180 are just not really needed.

Starting the BT section on a bracket is very helpful for leading the player where they are supposed to be facing to not get lost in the pattern. Likewise, adding the jacks in this section instead of just alternating feet is just way too much -- I didn't like them there either but it's helpful to know that's not just me being bad.

If there's 8th note gap footswitch you should always mark with mine. 16th it can sometimes be optional if it's very clear playing it as jack would be unreasonable.

erictran0 thinks that the middle part of the chart is not hard enough relative to the first and third parts of the chart. I think either nerfing the other two sections down to this level and making the chart e.g. a 12 or making this part a little more difficult both make sense, it does feel like a psuedo-break the way the chart is currently written.
