* Notes on Spaced Repetition

#+BEGIN_QUOTE
Draft: v1.0 | Posted: 6/8/2018 | Updated: 6/8/2018 | confidence of success: 85% | estimated time to completion: 3/5/2018 | importance: Medium
#+END_QUOTE

** What is Spaced Repetition?

Spaced Reptition is a method of efficiently reviewing flashcards by scheduling them based upon how easily you remember something. The gist of the idea is that it's much easier to remember something in your long-term memory than your short-term memory, so if you are trying to memorize a large body of information you should prioritize things you don't know very well and things you are just about to forget. Below is a good video explaining the concept and the relevant research behind it.

#+BEGIN_HTML
<iframe width="560" height="315" src="https://www.youtube.com/embed/ai2K3qHpC7c" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
#+END_HTML

The cool thing about spaced repetition is that it allows you to review and manage an extremely large body of information with relatively little daily review[fn:5]. I use [[https://apps.ankiweb.net/][Anki]] to review flashcards, but other people use [[https://mnemosyne-proj.org/][Mnemosyne]] which works just as well. I use this little application a lot to remember pretty much anything I think is worth remembering, so I figured it would be useful to write up some of my notes from using it.

** Spaced Repetition as a Deep Reading Tool
  
I am a chronic skimmer - I often read books very quickly, consume a lot of books in a short window, and then forget everything in them after a short while. My first solution to this was very [[https://www.goodreads.com/user/show/25277520-eryk-banatt][detailed reviews on goodreads]]. It didn't help me much in committing my reading to memory, but at least I was able to go back and reread my notes as a refresher whenever I needed to. I find that I have relatively weak retention when I read, and have always been slanted towards [[https://en.wikipedia.org/wiki/Fluid_and_crystallized_intelligence#Improving_fluid_intelligence_with_training_on_working_memory][fluid intelligence, rather than crystallized intelligence]]. Spaced repetition (more specifically, the use of a single, uncategorized deck separated by tags rather than decks) was a gamechanger for me in this respect - I started reading things with my phone open next to me (I shelled out the money for Anki's [now free, but at the time] ridiculously overpriced app, I use it a lot so I felt the cost-per-use was rather low), and making a short flashcard for any detail or quote I felt like I wanted to remember. This, in turn, let me do three things:
  
A: It allowed me to absorb as much as I wanted from my reading, down to the level of direct quotes

B: It allowed me to realistically understand how much I could read in a day / a single sitting

C: It allowed me to [[http://cgi.stanford.edu/~dept-ctl/tomprof/posting.php?ID%3D928][better engage]] with the material I was reading, since I'd actually grasp details instead of just the concepts
  
The second point is very important, because it's one that I struggled with a great deal for a very long time. I'd often sit down with a theory-dense book and just start reading it, as if it was a novel, more or less straight through. I'd inevitably find myself not really grasping things, and it'd eventually become a huge pain to read it. Making flashcards of important details in a book as I went allowed me to roughly see how much information I was actually absorbing, via my daily reviews. Somehow I was surprised to realize that my absorption rate for more difficult books was worse, and that I ought to be reading those slower (for example, a chapter of Tae Kim's Guide to Japanese Grammar wasn't so bad, but a chapter of Introductory Statistics with R was very difficult and those cards frequently gave me a hard time). This ended up being a reasonably useful tool I could use to adjust my studying habits - if I was going through a book and it felt too easy, I could try studying more each day; if I felt like it was hard, I could go slower and give myself more time to think about the ideas.
  
The third point was pretty useful because actively reading almost anything while actively stopping to make flashcards makes it rather difficult to zone out while reading, which is a bad habit I had for a long time. I'd read a page, look back up, and realize that I was so distracted that I didn't really understand the literal last page I had just read. Actively making flashcards as I read made it so that I had to actually be reading when I was reading, which did wonders for keeping me on-task during study time.
  
** Spaced Repetition as Removal of "XP Waste"
  
[[http://runescape.wikia.com/wiki/Old_School_RuneScape][Old School Runescape]] Players have a wonderful concept that they refer to as "XP waste". Playing Runescape is mostly about maximizing your experienced gained per unit time (the game doesn't exactly involve much else), so players will often calculate how much experience they ought to gain performing a certain task (e.g. "if you cut this type of tree for an hour, you should gain 10,000 experience per hour"). However, there are many reasons why you might not actually hit that amount of experience in one hour - trips to the in-game bank, going to the bathroom in real life, deciding to take a nap, getting bored, etc. Therefore, the difference between experience gained and theoretical experience possible is referred to as "XP waste" (i.e. "you could have earned this much more experience but you wasted your time and lost out on it"). Granted, people have differing levels of commitment to eliminating XP waste (e.g using better training spots vs optimizing for global timer vs not sleeping), but the overall idea I think is pretty interesting.
  
The nice thing, I find, about spaced repetition, is the low effective time cost to actually doing it. Even studying a good amount each day (50+ new cards, plus reviews) will only swell your review time up to ~45 minutes per day, and that sounds much worse than it actually is, compared to something like Exercise or Meditation. Doing 45 minutes of exercise feels like a good chunk of time, since it needs to be a solid 45 minute block of your day in order to be useful. But Anki can be done at any time, for any amount of time. Waiting for your eggs to cook? Do a few flashcards. Walking to class? Do a few flashcards. On the bus home after work? Do a few flashcards. You can't exercise in 8 randomly spaced 150 second chunks throughout the day, but you *can* do flashcards like that. Spaced repetition requires some time, but it can come from any time in your day, *including dead time*. This is time you normally would have spent doing literally nothing, and it ends up making "XP waste" moments in your life into ones that actually have a purpose. **Doing flashcards is just free experience**, and making your default nervous phone habit "open Anki" instead of "open twitter" will essentially make this a zero-impact habit on your day-to-day routine.
  
** Quizbowl as a Content Aggregator
  
Something I think is fun and heavily applicable to spaced repetition is [[https://www.qbwiki.com/wiki/Quizbowl][Quizbowl]], or more broadly "trivia"[fn:1]
  
I was "decent" at quizbowl in high school, where my [[https://en.wikipedia.org/wiki/Sussex_County,_New_Jersey][geographic location]] played a large part of the lack of serious competition, but after being admitted to Yale (at the time arguably [[https://www.qbwiki.com/wiki/2012_ACF_Nationals][the best]]/second best collegiate team, period, with [[https://en.wikipedia.org/wiki/Matt_Jackson_(Jeopardy!_contestant)][Matt Jackson]] spearheading the team) I played in a few collegiate novice tournaments my freshman year of college, found out I [[http://www.hsquizbowl.org/db/tournaments/1652/stats/prelims/teamdetail/#t27%20][was]] [[http://www.hsquizbowl.org/db/tournaments/1600/stats/complete/teamdetail/#t0][terrible]], and promptly quit the team to pursue competitive Super Smash Brothers Melee instead.
  
Fast forwards to my realization that it is possible to remember things you read for more than a week after you read them, and suddenly I felt extremely motivated to hit up [[http://quizbowlpackets.com/][quizbowlpackets.com]]. The nice thing about spaced repetition is that you can memorize tons of things, but the weird thing about it is that the question "what do you want to memorize?" is surprisingly hard to answer. [[http://rs.io/anki-tips/][Robb Seaton]] puts it well: 

#+BEGIN_QUOTE
"Or here’s a common hangup people have, and that I had, when starting with spaced repetition. It’s the question, 'What ought I memorize?' and people think, well, maybe the presidents or something, because that’s what they’ve associated memorization with. It’s the wrong question. Ask 'What’s interesting?' and start ankifying that." [fn:2]
#+END_QUOTE

What's really exciting about quizbowl is that it's quite literally structured to provide you with useful information. You're rewarded on a question-by-question basis for [[https://www.qbwiki.com/wiki/Pyramidality][knowing more obscure things about a topic]], and you're rewarded on a round-by-round basis by [[https://www.qbwiki.com/wiki/Generalist][knowing more answers than your opponent]]. I'm not eligible for collegiate tournaments and I'm not skilled enough to solo open tournaments, so you might ask "why care about quizbowl?" The answer here lies in utilizing quizbowl packets as *cool shit aggregators*. By its nature, a good quizbowl question contains a range of clues about a topic, and if you don't know about something then a quizbowl question can serve as a unit of 3-6 things about it (quizbowl players typically advocate reading packets as a method of improving at the game). Knowing about random things, even on a somewhat shallow level, often leads me to some of my [[http://planetbanatt.net/articles/pingpongzen.html][most interesting projects]], which in turn makes my knowledge of those things less shallow. Viewing it from this lens, playing quizbowl is like reading a manic RSS feed of snippets cut out of textbooks, lowering the chance that you spend lots of time on something boring, and making it easy to find new things worth reading about. And its pretty fun![fn:3]
  
** Useful Habits for Using Spaced Repetition
  
- Every time you look something reasonably useful up (e.g. "wait, what does this word mean?" Or "didn't they do a study on football causing CTE?") make a flashcard about it (usually takes 20 seconds)[fn:4]
- Use one big deck, and separate things by tags instead. It's much better to do it this way since otherwise reviews will pile on in decks you have no motivation for, and putting everything together is a good way to avoid the pain of starting. Likewise, it's more fun this way! One moment you'll be reading a sentence in Japanese and the next you'll be thinking about frame data in super smash brothers; it keeps you on your toes!
- Associate feeling of being bored and waiting for something with the act of doing flashcards 
- Have phone open while reading nonfiction and make flashcards for things that seem interesting but also not trivial to remember
- Make flashcards as short as possible - longer answer flashcards are prone to being bad flashcards and typically end up leeches / deleted
- Use images often, and make drawings when applicable - they can be terrible ms paint drawings, if you don't plan on sharing them then nobody will judge you for your art and it will help you remember.
- Don't add things you don't care about, or you will not want to actually do your reviews. I have made it a point to delete anything I come across during reviews that I decide is a badly made card or a card on something I don't care about.
- I have noticed when I am doing flashcards sleep deprived that I sometimes glaze over a card and do not really absorb the meaning of certain questions, but think something like "oh it's this card, and the answer to this card is Krebs Cycle". I think this points to good flashcard-making habits making cards as hard to differentiate as possible, which usually involves making them as short as possible to avoid unique strings giving the answer away to you (if the only card in your deck with the phrase "million years ago" is "Cambrian Explosion", you might not actually remember the "541" part when you actually need to remember the Cambrian Explosion for some reason)

** Closing

I plan to periodically add to this page as I come up with useful thoughts on flashcarding, but overall I think that using flashcards is one of those "Real-Life Cheat Codes" that I wish I found out earlier. It's one of those things like Counting Calories or Index Funds that is actually capable of producing [[https://en.wikipedia.org/wiki/Pareto_principle][large changes with minimal effort]], and I think things like that deserve some good documentation even if it isn't entirely complete.

* Footnotes

[fn:1] this word is sort of frowned upon in quizbowl circles, since quizbowl tries to put a strong emphasis on, for lack of a better term, "useful academic knowledge", rather than "arbitrary memorized facts". "Trivia" typically refers to information that offers no reason why anybody would know it (e.g. "Nikola Tesla was born on July 10, 1856"), whereas pop culture questions are affectionately referred to as "[[https://www.qbwiki.com/wiki/Trash][Trash]]"; and typically get regaled to side tournaments or the odd 1-2 questions per game. [[https://www.qbwiki.com/wiki/Trivia][Further reading]].

[fn:2] Robb Seaton uses anki for, as far as I can tell, literally everything - he puts little factoids about people he likes in his deck, so that he can memorize stuff like "My coworker's favorite color" or "someone's favorite type of cheese" which strikes me as a little much, but knowing people's birthdays certainly seems like a great example of a nontraditional use of anki.

[fn:3] for more information see [[https://myanimelist.net/manga/23165/Nana_Maru_San_Batsu][Nana Maru San Batsu]]

[fn:4] my rule of thumb is thinking of gwern's estimation of a card roughly equaling 5 minutes of time and thinking "am I willing to stare at this for five minutes if it means memorizing it"

On top of that, since I always have emacs open these days I have a (very very basic) capture template that creates an anki card which makes the process pretty straightforward - no matter what I'm looking at I can do Win-3 C-c c a and be in the process of making a card.

#+BEGIN_SRC 
("a" "anki basic" entry (file+headline "~/Dropbox/org/logs/added_anki.org" "Basic")
     "* know :deck: \n** Item :note: \n\t:PROPERTIES:\n\t:ANKI_NOTE_TYPE: Basic\n\t:ANKI_TAGS: \n\t:END:\n*** Front\n%?\n*** Back\n")
#+END_SRC

[fn:5] Further reading http://www.gwern.net/Spaced-repetition
