#+TITLE: Arcades

* Arcade Culture Encourages High Skill Acquisition

The death of the Arcade as a third space has roughly coincided with an era in gaming history which has largely moved away from technically demanding, high-skill-expression gameplay. I do some simple modeling and show that arcades offer an avenue for lower-income players to achieve similar enjoyment to their more wealthy peers only if they can develop high skill at particular games. 

** The Arcade as a Multi-Arm Bandit Problem

In Reinforcement Learning, Multi-Arm Bandit settings are problems where you have a bunch of actions and need to figure out which one provides the most reward. They're named this way because you're supposed to picture a bunch of slot machines ("one-armed bandits"), and your task is to figure out which of the slot machines pays out at the best rate.

We can model arcades as a variant of the multi-arm bandit problem in order to illustrate the effect of skill acquisition. Departing from the traditional multi-arm bandit setting, we describe a stateful version as follows:

Each day, the player has 180 minutes of free time (/time/) and recieves some constant amount of money (/income/). The player exists in an environment with different machines which cost some price to play (/quarters/), and when played will return a tuple of values (enjoyment, duration). Fun is defined as the total enjoyment * duration. The objective is to maximize the amount of fun the player experiences.

There are two types of machines: cabinets and home games. A home game has a fixed one-time price which is very high, and will return a constant enjoyment value for the entire remaining duration of that particular day. Once you've purchased a home game, you can continue playing it at no cost. Over time, the enjoyment will decay for these games, but you can refill this to the full original amusement value if you purchase another home game at the same original price.

A cabinet has a price which is very low, and will produce an enjoyment value for a relatively short time. However, these games behave differently from home games. Each time you play an arcade cabinet, the duration will increase, and the amount of enjoyment will skew towards higher values (/skill acquisition/). The first time you play a particular cabinet on a particular day, there's a small bonus (/novelty/) for the first couple of plays, which wears off quickly. Novelty also lessens day-by-day, so over time that initial bonus will shrink.  

Note that by the construction here, if you can't afford a home game, you have to save up for one and forego the enjoyment of playing in the arcade. If you need to save up a long time, that is a large opportunity cost compared to the fun you would be having playing in the arcade. On the flip side, if you have so much money that you can continually buy new home games, you might not have any desire to play the cabinets at all. There's a sweetspot here -- people who cannot afford home console games, but can spend enough time in the arcade that they can become good at using a particular cabinet. This may result in them being able to compete or even outperform peers with more income, because it's so much harder to encounter this situation if you're armed with high income (and can just buy home games).

** Why Did The Arcade Die?

Conventional wisdom will tell you that the arcade died because of rapidly increasing technological advancement in the home console market. However, through this lens, the story becomes slightly more nuanced. You can model an arcade's typical clientele as a variety of different agents for this multi-arm bandit problem, each with their own personal q* values for each cabinet (i.e. the player's /taste/).

As home console games grow more fun and less expensive, this sweetspot of regular arcade goers will begin to dwindle. Likewise, players who learn a specific policy which prefers the arcade over a home console is likely doing so because they can extract more fun for fewer quarters compared to a higher income player who happens to randomly go to the arcade on a particular day. That player on average will be worse at most of the cabinets compared to a regular, which means they will spend less /time/ on each cabinet, and be able to visit /more/ of them, netting the arcade's owner much more compared to a regular arcade-goer.

More concretely, the hardcore fan of arcades is largely irrelevant for the operating revenue of the arcade, the money-making clientele vanish with increased accessibility of home games, and overall most players will inevitably funnel out.

The nail in the coffin for arcades is if somehow arcade owners started seeking to make the games more expensive for these regulars, which makes sense given their attachment to being there. This can be done in two ways: First, making cabinets more expensive overall, which may potentially extract value from existing regulars of high skill, but shrinks the sweet spot for new players who would be encouraged to learn to play the cabinets at the first place. Second, making the cabinets less prone to skill acquisition, so that players can't spend a lot of time in the arcade without spending lots of money on the machines.

This last point can even be accidental -- the LCD screen revolution that took place in the late aughts represented a major pivot away from games which demanded snappy, high-octane gameplay simply by virtue of those games being difficult to play subject to [[https://planetbanatt.net/articles/lagless.html][input lag]]. Most classic

Finally, incentives from the developer side would make these industries very difficult compared to the wide open home market. While new machines at an arcade would increase novelty in our toy examples, /getting rid/ of machines is comparatively more difficult. Creating a development cycle which gets arcade owners perpetually buying new machines is extremely subject to oversaturation, but directly selling new games to home consoles became exponentially easier to manage after home consoles became much more popular. 

* More Reading

[[https://d1wqtxts1xzle7.cloudfront.net/64961322/JBVI_arcades_Roundy_2020-libre.pdf?1605627336=&response-content-disposition=inline%3B+filename%3DAn_extra_life_for_the_arcade_Entrepreneu.pdf&Expires=1728609608&Signature=Q5plQGSd7~EPQ8DC1pULbrDwCko6BQjFuBhzC78rqy2UH-u2u2nuPqpCtCjGl4NQV~qkiL6STIYDNsmWvjHrat12y20UOODKPrpcFYOPJAxaYwI-riZ3AmvZqk5kSoL~gxsTmGolD011Q4cfQj1MWN4yNzX4z4610ut1aC2ZP2Me71PrT1likpEHEjynCwHkUiu9ckQjUGFJ8BZyvan6ypG7R8ot01QAX~gIhzP-ZrKEWSFbu7cVs87Qg~4anxQ5zJOXZpE3wrWfV6AwT8WkiLPcB6-ZPi218HSG6nz5RaSgAHyy6YY-sgYpe9ar0u7GnVY5PQceSEa7lPhcI18BIw__&Key-Pair-Id=APKAJLOHF5GGSLRBV4ZA]["extra life" for the arcade]]

https://books.google.com/books?hl=en&lr=&id=gTB0DwAAQBAJ&oi=fnd&pg=PT5&dq=arcade+culture&ots=ocNeoT2dS4&sig=roYG2DYE6hmu0unMvlXILc1b29A#v=onepage&q=arcade%20culture&f=false

