* Learning Miscellaneous Artsy Stuff in (Hopefully) Relatively Short Time

#+BEGIN_QUOTE
Draft: v0.1 | Posted: 09/29/2020 | Updated: 09/29/2020 | confidence of success: 10% | estimated time to completion: 12/31/2020 | importance: Medium
#+END_QUOTE


** Film

After asking some of my more knowledgeable art/photography/film friends and digging around the internet, I decided to purchase a Panasonic Lumix G7, alongside a tripod and a few other miscellaneous peripherals. Since I'll be using this to film Melee Stats content, the camera technically doesn't belong to me (and will likely be passed around as people have projects that require it) but as it stands I am the one who has an active film-based content piece in the works so I was the one who pulled the trigger to purchase it. 

The goal here is *learn to use this equipment quickly in order to be able to film documentary-style content within a short period of time*. As a result I don't need to super worry about stuff like fluid head tripods or autofocus or any of that stuff; I just need to learn to use the camera, point it at the right thing, make it look nice, and be able to effectively edit it together into something watchable. Should be achieveable!

I am going to be largely focused on working through [[https://www.youtube.com/watch?v=1-sBvBBi6MY][D4Darious's How to Learn Filmmaking FAST! - Without Film School]] video. I'm not trying to diminish the value of film school, but this video seems like a nice set of exercises to learn to use my equipment and make the type of content I'm interested in within a relatively short amount of time. 

*** General Points of Advice

**** 50/50 Rule

The general point here is to spend roughly half the time looking stuff up and the other half of the time actively practicing those things. This is hard to do and there's a lot of temptation to do only one or the other so make sure to look out for this (see: improving at melee). This also shows up later so don't forget it

**** Do Too Many Tests

Tests with every individual skill you acquire get the skill into your brain and make things easier to use later. It is hard to do a bunch of things at once for the first time, in a project that you want to be good as much as possible (trust me on this one).

**** Microfilms

The fastest way to get good at filmmaking is what D4Darious refers to as "Microfilms" which are basically one-scene short films which are almost exclusively intended as drills to practice a specific technique or idea. I will update this section later with my opinion later.

**** Do Not Choose Too Large A Project Too Fast

I've spoken about /Learning by Accumulation/ on this website before but when learning an entirely new medium it's best to accumulate in a way which doesn't completely overwhelm you 

**** Do Not Get Bogged Down Consuming Filmmaking Content Instead of Filmmaking

If you want to do something, you have to do it. You can not merely know about it. This is a skill, it is not a list of facts.

*** Curriculum

Necessary gear:
- [X] Camera
- [X] Tripod
- [ ] Sound Recorder
- [ ] Potentially, dedicated lights

**** Day 1 

- [X] Search “Framing and Composition” on YouTube; watch 3 videos twice
- [X] Take 100 Photos with your camera

***** Rule of thirds

Generally speaking, when composing and framing shots you want to place things on the boundary of thirds.

Things generally just look better when placed on the gridlines, and generally attention is easily drawn to the intersection of those gridlines. It serves as a roadmap for perception of the image in a more straightforward way.

You usually can enable these lines on your camera, and this is useful for composing good shots easily.

For landscape shots, it looks much nicer if horizons are placed along the lower or upper line, rather than the middle of the image.

The reason the rule of thirds look nice is because the resulting pictures serve as an approximation of the golden ratio, proportionally speaking.

***** Symmetry

Symmetrical shots are fun to look at, look nice, and are useful if you want to place something in the center of the frame. You'll generally want to do this for two, related reasons:

1. You want to clue the watcher that virtually nothing else is worth the effort to train your eye onto
2. You want to make cuts amidst chaotic action which allow the watcher to follow the action without hunting around the frame for the relevant information

This is useful for documentary style content where the subject speaks directly into the camera (i.e. tutorial videos).

Wes Anderson is famous for good use of symmetry in his films, if you want good examples.

***** Leading lines

Visible lines in the image point at your subject and tell the viewer what is important.

Useful for portrait shots, since they direct attention to the subject in a sort of visual vortex.

***** Headroom and lead room

People being cut off from frame makes image claustrophobic unless it’s a closeup to get at their eyes

Lead room facing image boundary makes shot feel uncomfortable because there’s no information about where they are facing

Good for interview style content to have lead room and the subject off to one side

Doing the opposite here is called “short sighting” and was used for example in Kings Speech to convey trappedness

***** Depth

Every shot has foreground, mid ground, background, use these to tell a story about how your subject exists in its surroundings

Lens is important here because it’s what will allow you to separate or not separate your subject from its background, and a wider angle lens will put more of the shot in focus

***** Size equals power

Large objects are usually important, small objects are insignificant, so use this to inform the shot

Far away subject can signify lost / smallness / insignificance while a mid or close shot gives them more agency

Angling down at subject makes them feel dominated, angling up makes them feel more powerful

***** Framing within your frame

Some sort of environmental subunit which reduces the size of your frame is really valuable (e.g. doorways)

***** Repeating elements

Interesting shots come from scenes where some element appears multiple times

***** Contrast and counterbalance

Having two visual elements which are opposed in some way can be useful to make a shot feel more balanced, or imbalanced in a way which directs attention in a specific way (e.g. light)

***** Don’t be religious

Sometimes these rules can be broken for contrast reasons or to deliberately make someone feel uncomfortable watching it

**** Day 2 

- [X] Take 50 more pictures practicing framing and composition, rule of thirds, etc.

**** Day 3 

- [X] Search “3-Point Lighting” on YouTube; watch 3 videos twice 
- [X] Use lights at home to replicate, take 50 photos of a subject

***** Three Point Lighting
There are three important types of lights which are used in three-point lighting, which is often referred to as "the first thing you learn about in film school"

- *Key light*: big important light for your subject, by itself it's a little dramatic since it'll cast shadows over your face
- *Fill light*: alt side light to diminish shadow contrast from your key light, called this because it "fills in" shadows, usualy not more than 50% as powerful as the key light
- *Backlight / Hair light*: separate subject from background, give halo-y effect, "filmic look"

*General Tidbits*
- If you want less intense light, you can move the light source further away
- "Hugo" movie known for super hot hair light, won award for cinematography
- "Motivated Lighting" placing insignificant light sources in frame to make the 3 point lighting (specifically, back light) look more natural, often you need to control the temperature of the back light to match the light source.
- Sometimes you can also add a background light to light up the background
- You can add or remove these lights for *specific* effects, such as making a scene more dramatic or less realistic-looking

It seems important to not use normal room light for this from my basic testing today so tomorrow I'll try it with a third light instead of two lights and a ceiling light for back light

**** Day 4

- [X] Take 50 photos practicing framing, composition, and 3-point lighting, with 20 of those photos next to a window with natural lighting

I tried this at around 6pm and honestly you need quite a lot of light from natural light source to be compelling in a photo, which is duly noted

**** Day 5

- [X] Search "Depth of Field" on youtube, watch 3 videos twice
- [ ] Take 50 pictures with the kit lens, experimenting with different focal lengths / aperture / etc (don't have to be amazing photos just mess with it)

***** Depth of Field

Depth is the range of objects in focus in your shot.

That is, it is the distance between closest object in focus and furthest object in focus; can be narrow (focus only on an object) or this can be very wide (focus on the whole landscape). For example, if you want to shoot an interview, you might want to isolate your subject and then make the background a bit out of focus. In general, this is used to help stylize your shots the way your want them.

Please remember that F number moves in the same direction as depth of field, not aperture size (i.e. small F number, narrow depth of field, big F number, wide depth of field). Fun mnemonic for this: Imagine your camera lens shoots out a lot of F's like a laser. If you want only a small number of those f's in focus, use small F number. If you want all of them in focus, use a big F number. 

You can even use depth of field to take pictures through meshes or grates and have that obstruction vanish with proper depth of field. Wow!

You directly move this with the "A mode" in a camera, which you use when the depth of field is the most important creative element to your shot (i.e. most times; portraits and landscapes). Important to remember, huge F numbers require much slower shutter speed. Also, notably, it doesn't change in the viewfinder (because the hole would be too small for high F number). Since the hole is smaller, it takes forever for all the necessary light to get in a decent picture. Opposite side; crazy exposure might be too small f number. If you get camera shake for high F numbers, you might benefit from higher ISO.

For big big depth of field, you want to focus about a third of the way through the shot first, since otherwise you're "wasting" the fs past the center of your depth of field (think of this as "centering" your prism of focus, except it's more like the one-third point in it).

****** Three ways to affect Depth of Field.

******* Aperture

The opening in your lens; wider aperture (smaller number) = shallower depth of field, and the tighter aperture (bigger number) = wider depth of field

******* distance to subject

The closer you are, the shallower the depth of field
the further you are, the wider the depth of field

******* focal length

Longer focal length = shallower depth of field
This usually matters if you have a longer lens and a shorter lens

****** Different types of shots using Depth of Field

******* Deep Focus

When the subject and background are both in focus (wide)

Gives more information to the viewer, allows information happening on multiple planes

Useful for layered 

******* Shallow Focus

Renders a portion of the image more important than the rest, the "plane of focus", which can be background, foreground, both, etc.

Used for Bokeh effect. 

Most shots use some degree of shallow focus, to draw attention to a subject. Useful to save when it really matters.

******* Soft Focus

i.e. nothing in focus, nothing is 100% sharp. Done with diffusion filters. or built-in imperfections (e.g. smear lens with vaseline)

used to lend atmosphere to dream sequences, or just surrealism in general. Generally very bold to go for this.

******* Rack Focus

A verb, not an adjective; used to move focus from one part of the shot to another part of the shot (e.g. move focus in and out of foreground / background)

"follow focus"?

******* Split Diopter

two separate focal points with medium out of focus spot

Done with specialized lenses, which are used rarely (looks a bit unnatural because human eyes cannot do it)

******* Tilt Shift

aka swing shift, which focuses an extremely narrow part of the frame.

Occasionally when zoomed out this can make actual shots look like miniatures.

**** Day 6

- [X] Search "How to get the Film look" on youtube, watch 3 videos twice
- [X] Pick up camera and record 2-minute clip of anything, with those settings

***** The Film Look

Apparently this is a specific subclass of looks that can be had, which I guess makes sense.

****** Camera Settings

Everything Manual Mode

24 fps unless you plan on slowing down footage, higher framerates look "too smooth", with "soap opera feel". This is just what "film" looks like. 

Shutter speed should be set to 1/48th of a second for 24 fps, cinematic motion blur. Faster shutter speed reduces motion blur (makes things feel jittery), Slower shutter speed adds extra motion blur. Adjusting this is useful sometimes for conveying specific feelings, such as chaos in saving private ryan's opening scene. 

180 degree shutter rule: double framerate to get shutter speed default.

ISO adjust sensitivity to light; higher, means more sensitive to light

outside: 100-200 usually
inside: 800 probably
too high you get digital noise
sometimes if your f number is too low then even 100 is too high, and you have to a smaller aperture opening to not overexpose the shot

dyanmic range: distance between brightest and darkest parts of the image, usually this is pretty hard for cameras 

useful to shoot shaded vs shaded, light vs lights etc

picture styles: Neutral style usually best if you plan to color grade in post, otherwise these are nice to have

Do not use autofocus, disable it if it is on your lens.

****** Technique

usually 16:9 is the right way, but sometimes theres 2.35:1, easiest to do it with a letter box image but the best way to do it is to just adjust it in premiere sequence settings

film grain overlay makes it look nice sometimes, find a youtube video and overlay it with opacity cranked up, but its a stylistic choice

Warp Stablizer can be used to make things look more stable, like with hardware stablizers used in professional film, at the cost of some resolution. Can make the camera completely still for things that should have been done on tripods but weren't.

Color Grading makes a huge difference for changing the tone of a shot with no other changes. Common film look makes darks darker and lights brighter, but this depends on the footage and the shot (e.g. blues higher works good for sadder scenes). A three way color corrector can be used to make darks a bluer hue and highlights a warmer color, as an example for common film look.

Audio is the most important thing to not fuck up because if it sounds bad it stands out 

Good acting is imporant, second most important behind audio; mumble core is a good example of using nothing other than good acting 

Framing and composition makes things look like a film, you can deal with mediocre lighting but not mediocre framing

Film grammar is what makes things feel like they make sense, Hitchcock is one of the masters of film grammar. This just takes time and study, it's a language.

Good lighting is important to make things look good

Depth of field is good, make sure the actor isn't that close to any walls

Music is important for setting the ambiance

****** Misc

Backlighting is a good way to control the lighting during outdoor scenes with natural light

Use a lens hood if you are shooting into the sun unless you deliberately want lens flare / washed images

Sillouhettes are a stylistic choice, underlit shots are not.

Magic hour leads to beautiful lighting

Light baths look nice but are only appropriate when they are appropriate

Adding depth is good

Texture and Patterns looks great on cameras (see: every superhero)

Closeups, specifically of interesting faces, is good.

Christmas lights look nice out of focus so they come up a lot in films, but sometimes don't work out

Good transitions really punch up shots

****** Limitations

moire happens in patterns with weaker cameras

**** Day 7

- [ ] Do some camera tests, make videos playing around with shutter speed, ISO, etc in order to see what doesn't work ("do this all wrong")

**** Day 8

- [ ] Watch 3 videos twice about adobe premiere pro CC
- [ ] import 1 or 2 of your camera tests, make two edits, and render it out (don't do anything else to it)

**** Day 9

- [ ] LIGHTING EXERCISE: Tell a story using light, find 6 interesting shots that have something to do with the light, pay attention to camera settings and composition 

Something worth looking up here: "Magic Hour"

**** Day 10 

- [ ] Edit lighting exercise together, render, review, take notes on mistakes

**** Day 11

- [ ] vlog your day, pay attention to camera settings and composition

**** Day 12

- [ ] Edit the vlog together, render, take notes on mistakes

**** Day 13

- [ ] Search "types of shots" and "camera angles" on youtube, watch 3 videos twice

**** Day 14 

- [ ] Shoot a scene using this script:

Character A: Hey
Character B:  How long do we have?
Character A:  All night.
Character B:  OK.

Expect everything to suck, but use whatever meaning you want here.

I might do something silly instead of this

**** Day 15

- [ ] Cut the scene together and render, review and take notes on mistakes

**** Day 16

- [ ] Shoot the previous one-scene film again, but light with household lights, use a different room or location, and learn from previous mistakes

**** Day 17 

- [ ] Cut it together, render, review

**** Day 18

- [ ] Shoot another one-scene film focusing on framing and composition & camera settings.  Shoot the whole thing using available window light

**** Day 19  

- [ ] Cut it together, render, review

**** Day 20 

- [ ] Get a sound recorder, vlog adventures getting it, make it short and fun

**** Day 21 

- [ ] Look up how to use sound recorder on youtube, watch 3 videos twice
- [ ] Record 3 sounds around your house

**** Day 22 

- [ ] record 50 sounds with the sound recorder, play with gain, experiment with over modulating a few sounds
- [ ] import into an editing project, drop them into a timeline, crossfade between each of the clips, export

**** Day 23

- [ ] SOUND EXERCISE: record 20 sounds and try to tell a story (e.g., record morning routine)
- [ ] import sound clips, trim them down, render

**** Day 24 

- [ ] Interview a friend, pay attention to lights, make sure sound is good

This is the big day for my project :) 

**** Day 25

- [ ] Look up “How to Sync Sound” on YouTube, watch three videos twice
- [ ] Take footage of friend, dump into editing application, sync the sound with picture, cut so it flows nicely, render 

**** Day 26 

- [ ] Look up “180-degree Rule” on YouTube, watch three videos twice
- [ ] practice the above using toys as a subject

**** Day 27

- [ ] Search “How to Write a Script” on YouTube, watch three videos twice

**** Day 28 

- [ ] Write a simple two-page scene with a couple of people in one location (include conflict)

**** Day 29 

- [ ] Record the scene with two friends (improv is ok, lines don't have to be perfect)

(remember your framing and composition, camera angles, 180 rule, keep sound recorder >3 feet from speaker)

**** Day 30

- [ ] Edit together, render


** Drawing

Drawing in particular I think is something I've always considered myself very much terrible at, but since I've been taking a bit more of a creative / artsy stint recently I thought it would be fun to see if I could at least become suitably intermediate at it with some focused practice. 

For a more directed goal, in general most of the things I do are focused around two things:
1. Storytelling
2. Practical Use

This suggests to me that I would like to be good enough at drawing to do two things: draw objects so they're identifiable, and draw people / characters so people know what they are doing. It would be nice to eventually get into painting, portrait drawing, realism, or whatever, but for the most part I think my primary goal is just to *make simple drawings with a focus on figure drawing*. 

Of course the big thing at the heart of all art is the fundamentals, so my primary resources to learn to draw will be the following:
- https://drawabox.com/
- [[https://www.youtube.com/playlist?list=PLtG4P3lq8RHGuMuprDarMz_Y9Fbw_d2ws][Figure Drawing - How to Draw People | Proko]]

Unlike the Film track I'm pretty uncertain about the timeline for this one, but I'm sure throwing a lot of deliberate effort at this will be better than doing nothing so I might as well just do it. For me this is mostly a success if I get to a point where I can draw stretches in a notebook in order to remember how to perform them. 

*** Art Supplies

Fineliner Pens 0.5

maybe get this later https://www.amazon.com/Figure-Drawing-All-Its-Worth/dp/0857680986

can i do figure drawings with a fineliner pen?

we will figure it out later
