#+TITLE: On Being The Bad Guy

* On Being The Bad Guy

Generally speaking, the audience is smarter than they are often given credit for. It is extremely rare for popular media to depict characters for which it is difficult to determine which characters are good and which characters are bad. By construction, there is a powerful looking guy on the cover, and he punches other guys -- those guys are the bad guys, and usually we are supposed to dislike them.

It usually helps if this guy is deformed or deranged in some way, to really sell that they are the /bad guy/. If they aren't, they usually need to be at least properly creepy or unsettling. If you do a poor job at this, you'll muddle the message. Sometimes the good guy is wrong about something, and sometimes the bad guy kind of has a point, but this critically must never be enough to confuse the audience about who is supposed to be good and who is supposed to be bad. Where the good guy lands is always the point, and anything convincing from the bad guy must either be misguided, "doing things the wrong way", or some sort of advanced sophistry where the bad guy tries to garner sympathy.

All of this is very simple.

** A World of Good Guys

There is, of course, a small problem. Most people view themselves as the good guy, and view their enemies as the bad guys.

If you are a bad guy, this is bad news. The audience usually likes the good guy[fn:2] and for some reason they don't like you, even though you are the good guy. You are pretty sure this is because you are a temporarily embarrassed good guy, and you are just currently misunderstood. You're pretty sure you can think of some really huge examples where this happens in popular media, especially if you really think hard about it[fn:3].  

Even worse, all those bad guys you keep running into seem to think /they're/ the good guys. And the worst part is, everybody loves those guys. This is some advanced bad guy stuff, you think -- they've managed to brainwash the masses into turning against you. You plot and scheme (good guys do this, too) in an attempt to devise a method to win back the public, to wake them up to the truth that you are the good guy.

Ultimately all of this is in vain. There is a single thing which determines who the bad guy is: it's who the audience sees the good guy punching. 

** How It Feels to be Punched by Captain America

It does not feel good to be punched by Captain America.

Maybe you would have had a more detailed thought, but you're pretty sure you have a concussion (you know, from the punch). He seems to punch much harder than you do, which is sort of unusual, since you're the good guy and you're overwhelmingly supposed to [[https://tvtropes.org/pmwiki/pmwiki.php/Main/TheGoodGuysAlwaysWin][always win]].

There's a strong temptation here to use the strength of the punches as shorthand for who is the good guy and who is the bad guy. After all, even out here, in the real world, it says right here in the history books that the good guys have won every single war (what are the odds?)[fn:1]. Surely, with some logical step-by-step thinking, we can arrive at the conclusion that whoever punches the hardest must be the good guy.

Something about this feels sort of off to you, as you hurtle towards the floor after Steve's most recent killer right hook. This guy punching you was frail and weak before being roided out by the government or something, right? Was he more or less evil back then compared to now, where he's punching you (obviously, the good guy here)? Is it centrist to be weak instead of being slightly less strong?

The more you think about it, the less it really makes sense. It seems like how hard the punches are doesn't really have anything to do with who is right and who is wrong. Maybe. It's possible you're just coping about it. You are still pretty sure you are the good guy. You lose consciousness.

** Just Another Body Swap Horror Plot

You bolt up in a panic and it's worse than you thought -- you've woken up inside the body of another person. It is, of course, the person you dislike most in this world, the /real bad guy/.

You briefly consider your options. Harming yourself seems like an obviously bad idea, since who knows how long you will be stuck here. You quickly land upon the idea of turning yourself in, but then realize that you're not sure what that even means: currently it seems like the public believes you ("you") are the good guy, and it seems like you don't have any real way to convince them otherwise.

A knot develops in your stomach. It occurs to you that it's highly likely that the previous occupant of this body is out there somewhere running around in /your/ body. Oh god, he's going to ruin everything. He might turn himself in, or worse, he might even hurt me. He thinks he's the /bad guy/ now, and he was already bad enough before.

Luckily it turns out this new body of yours can punch pretty hard -- you should know, you've been punched by it. After a substantial amount of deliberation, you make it your new purpose to make sure that guy doesn't do bad stuff inside your old body. From the audience's perspective, very little has changed, but it's nice that they're randomly cheering for you now, even if they haven't really been vibing with the slightly different pre-fight banter recently. You smile. You were the good guy all along. 

** Being the Bad Guy Isn't That Bad

The real secret here is that there are no such thing as good guys and bad guys. I made it all up, it turns out. We are not fictional characters: we are just people. Things don't happen according to storylines. Things /just happen/, and storylines are superimposed thing we use to make sense of those things that happen. I made a [[https://www.youtube.com/watch?v=Fg_7DcXwBlk][weird video]] about this once, and even though I wrote it years ago, it still took me a really long time to really believe it deep down. Part of me still doesn't even really believe it -- a part of me that clings to my self-image as a hero, a perfectly moral being who is never wrong.

It took a lot of times being the bad guy before it really clicked for me that I was not the hero of reality, subject to frequent and devastating temporary embarrassment. It took many, many sleepless nights where it felt like everybody was just one blogpost away from /getting it/, from really understanding that I've been the good guy this whole time, that from my point of view the Jedi were evil. Sometimes you get to feel the joy of being the good guy, and sometimes you get punched by a beloved hero. It's nothing personal. 

In a lot of ways it's like how competitors will often mentally consider their "true skill level" their selective memory of all their most unbelievable successes, and write off all of the times they underperformed as being somehow anomalous and unrepresentative of how good they are. This is called the [[https://en.wikipedia.org/wiki/Availability_heuristic][availability heuristic]]: a mental shortcut which basically says "if I can remember it, it must be more important than all those things I can't remember". A highlight reel of all our successes playing constantly on loop in our mind's eye; that time we won an important match, or the time we did something extra good at work. With such a view, how could it be possible for anybody to view themselves as anything /but/ a hero? 

I do think there is maybe something worth examining in how social media perpetuates hero/villain narratives, about what they do to people's perceptions of right and wrong, the times where that feels potentially [[https://en.wikipedia.org/wiki/Gaza%E2%80%93Israel_conflict][really necessary]] and the times where that feels [[https://liquipedia.net/smash/SSBMRank][really stupid]]. But that's for a much longer and much more careful post, different from this one. For the most part, I think it's probably best to discard this hero/villain framework altogether; something at best useless and at worst actively harmful.

It's okay to embrace the risk of being the bad guy, sometimes. In the end, it's more important to do the thing you think is right, more than it is to do whatever you think the hero is "supposed to do".

* Footnotes

[fn:3] You could probably think of this faster than [[https://www.youtube.com/watch?v=l24TjgdRNTU][Ludwig could think of 100 women]], at least. Good to have an upper bound on it.
p
[fn:2] Some people like you, and you love them, but for some reason everybody keeps calling them weirdos and that makes you angry.

[fn:1] I've heard this joke attributed to Norm Macdonald but I can't find a source for this anywhere. 
