#+TITLE: Novelty Dispersion
* Novelty Dispersion

#+BEGIN_QUOTE
Draft: v1.0 | Posted: 5/6/2019 | Updated: 5/6/2019 | confidence of success: 85% | estimated time to completion: 5/6/2019 | importance: Low
#+END_QUOTE

There is a phenomenon I've noticed in myself when I commit to doing larger, longer-term tasks that I've started to realize might be more common than I thought. I've often worked an extremely long amount of time making something, editing it, revising it, editing it again, and otherwise re-consuming my own drafted content over and over again, and this constant repeated exposure to my project gradually warps my perception of how interesting my project is in the first place, usually in a downwards direction. I think this phenomenon is actually somewhat more common than I initially imagined, so I have decided to give it a name - /Novelty Dispersion/.

** Content is Novel, Creation is a Grind

#+BEGIN_QUOTE
/To be an artist means to never avert one's eyes/

—Akira Kurosawa
#+END_QUOTE

The tragedy of good content is that it takes so long to create yet can be consumed in a comparatively trivial amount of time. [[https://en.wikipedia.org/wiki/Seven_Samurai#Production][Akira Kurosawa]] is my favorite example of this, who filmed /Seven Samurai/ over the course of a year, with 148 full days of shooting. Twice during this process, the film studio closed down, and Kurosawa just went fishing until they opened up again, so he could continue. It's easy to lose sight of the pretty monumental effort required to create things (even [[https://www.youtube.com/watch?v%3DU64j80P-Vl0&list%3DPLQvvxnU2-ItePyupBYGFLlKJ5SZap2y8L][completely mundane objects in day-to-day life]]), since most things either exist in the filtered-out backgrounds of our lives or are consumed in real-time, usually relatively quickly.

However, even with a strong vision of the end-goal of some project, the process of /making things/ in general is inherently very psychologically difficult. The big reason I think that this is the case is that the idea for a project exponentially loses it's novelty to the creator, but the effort required to continue grinding out a project typically continues increasing as you grow more and more skilled. Put another way, your project gets *harder to work on* and *feels like a worse project* /even as you make your project better and better/. The really devious thing about this phenomenon is that for the most part it's really entirely in your head, and that if you were magically able to see your project for the first time at multiple points during your work-in-progress you'd just be monotonically more impressed the further you go.

I find this typically manifests as some combination of "subjective" and "objective", so let's briefly talk about these.

** Subjective Novelty Dispersion

#+BEGIN_QUOTE
/Maybe this project just isn't that interesting after all./
#+END_QUOTE

Those of you familiar with my youtube channel probably know about [[https://www.youtube.com/watch?v%3DOGpB5d5nuPg][STARS ALIGNED]], which was a tool-assisted Super Smash Brothers highlight reel where I created gameplay clips frame-by-frame which looked like they came from once-in-a-lifetime actual play, compared to most TAS videos which focus on creating [[https://www.youtube.com/watch?v%3DIndm8KGXaEU][amazingly superhuman]] gameplay. This was generally pretty well-received once I published it, and it remains arguably my favorite video content I've ever made.

However a funny thing happened as I made clips for this video - I just started to believe that most of the clips were too boring, that nobody would like it, that I was getting overly enthusiastic about minutiae that my audience would not share.

Something I think that is relatively underappreciated about content creation is how much the creator has to actually confront their own work. If you watched STARS ALIGNED, you probably watched it once or twice, and if you were really fanatical about your enjoyment of it you might've watched it somewhere between five and ten times. There are eighteen clips in the video, and during the creative process I walked through every frame of every clip, iterated upon the ideas, scrapped several ideas after completing initial clips, edit the video together, etc. I have watched every clip of this video literally hundreds of times, at varying speeds, in different stages of completeness. 

Every piece of content you ever consume is like this in some capacity. Every film you watch took many people thousands of hours to collectively produce. Every book you've enjoyed was almost certainly reread by 
their author countless times.

The funny part about this, from the perspective of the one making something, is that your definition of "normal" changes over time, and it gets really hard to judge how exciting something is when you've seen it countless times. 

Something I think that helps here is peer feedback and solid documentation of your good ideas. Obviously the best way to know how someone will react seeing something for the first time is to observe someone being shown something for the first time, and that includes yourself back when you first envisioned the project in the first place, so outside / archived perspectives are very useful for fighting this sort of feeling. 

Importantly, though, it'll only ever help you gauge what your project will feel like for other people. There's no magic trick that will help you feel like you're seeing something for the first time again - if there were I'm sure there's a good amount of media I would give anything to experience for the first time again.

** Objective Novelty Dispersion

#+BEGIN_QUOTE
/But nothing is more opaque than absolute transparency/

—Margaret Atwood
#+END_QUOTE

There is a well-known cognitive bias called /The Illusion of Transparency/ which describes the tendency for people to overestimate how much their own mental state is known by others. One experiment that [[https://en.wikipedia.org/wiki/Illusion_of_transparency][nicely demonstrated]] this asked subjects to tap with their fingers the rhythm to some well-known song (Happy Birthday, the national anthem, etc) and have another participant guess the song. People typically guess that the other participant will get the answer 50% of the time, but in actuality the true rate of correct guessing is around 3%. This feels outrageous if you tap out happy birthday yourself - I can hear the entire melody! But other people don't have access to your internal mental state, they only hear a rhythmic tapping and nothing else. This has all sorts of ramifications, one quick example being public speaking (people tend to overestimate how visible their nervousness is onstage).

A funny thing that I've noticed happens during projects is the feeling that your project is exceedingly trivial, and that "everybody knows this". I think novelty dispersion can also take this interesting form where your project slides from "currently interesting concepts" to "things I've known for a good while now", and as a result your perception of the novelty of your project slides with it from "right on the border of things I know" to "things people generally know, right?". Your project /feels/ smaller, but it's actually because /you've/ grown, not because your project changed in size at all.

The best illustration I've seen of this is in the below tweet:

#+BEGIN_EXPORT html
<blockquote class="twitter-tweet" data-lang="en"><p lang="und" dir="ltr"><a href="https://t.co/1oo2CyX5GO">pic.twitter.com/1oo2CyX5GO</a></p>&mdash; Ben Orlin (@benorlin) <a href="https://twitter.com/benorlin/status/988775097623248898?ref_src=twsrc%5Etfw">April 24, 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
#+END_EXPORT

This has happened to me a number of times, where after learning something new for a project I will eventually come to believe that this new thing I learned is just actually known by everyone in the world, and that it's inclusion in my project is obviously uninteresting and no longer novel. The kicker here is that this is entirely based on /my own/ corpus of information; as if the entire world learns all the same things as me at the same speed I learn them, and that my projects grow less interesting to the world at a 1:1 rate to my own ability to complete the project. To make a crude analogy, it's like struggling to climb a specific rock climbing route, learning to climb it, and then deciding that the climb /became easier for the entire world/ after you became able to do it. 

** Closing thoughts

I think that creating new content for the world is great, and that it's a useful exercise to reflect upon the psychological hurdles inherent in making new things and still believing that you're doing a good job. It's useful to keep in mind when I'm making my own things, but I find it also allows me to consume other people's cool things with a greater sense of empathy. It takes a lot of work to make things, and it takes a lot of courage to try and make something good in the face of [[https://en.wikipedia.org/wiki/Sturgeon%27s_law][Sturgeon's Law]]

If you once thought your project was cool and are doubting yourself, just imagine you're going to send it back in time to yourself back when you thought it was interesting. Even if you don't totally believe it yourself anymore, the person in the present who shares an opinion with the version of you that used to exist will probably be really excited about it.

/posted on 5/6/2019/\\
