#+TITLE: Dance Games: How I Learned to Stop Worrying and Love Cardio

#+BEGIN_QUOTE
Draft: v1.0 | Posted: 08/23/2022 | Updated: 08/23/2022 | confidence of success: 30% | estimated time to completion: 08/23/2025 | importance: Low
#+END_QUOTE

* Dance Games: How I Learned to Stop Worrying and Love Cardio
** Abstract 

You probably don't like cardio. Most people don't. You probably like video games. Otherwise I'm not sure why you would be on my web page. If you grew up in the aughts like I did, you probably have played /[[https://en.wikipedia.org/wiki/Dance_Dance_Revolution][Dance Dance Revolution]]/ (DDR), and if you are like me, you probably liked it. People who grew up in the heyday of arcade culture still play dance games, and have managed to turn it into an endurance sport. If you like games, modern dance game setups are trivially inexpensive compared to the cost of most forms of cardio equipment, and it's fun. This page contains my notes on getting started, and how I have broken through different blocks for different methods of playing. I'm fairly average at these types of games, but I plan on updating this as I have more things to say.

** Sportification

I, like many people, didn't really care for cardio-based exercise once upon a time. I had a vague desire to move around more for health reasons, but the actual moving around part was not terribly enjoyable. I liked sports growing up, but coordinating people to play sports with, who have roughly the same schedule as you, etc was much harder in adulthood than it was in high school. So, I embarked in search of something which I could generally do alone, which was kind of sporty, relatively inexpensive, and would capture my interest for a long period of time. One arcade trip later, I decided upon dance games. 

I think the concept of sport is relatively interesting, since I think it is something which will naturally emerge from any high-skill activity which multiple people can compete in, either against some sort of objective function (e.g. running times, high scores) or directly against each other (i.e. opponents, opposing teams). My go-to answer to this is [[https://en.wikipedia.org/wiki/Competitive_karuta][Competitive Karuta]], a japanese card game for which players compete to find the second verse of a poem which is read aloud by a third party. This is generally an idle diversion in broader Japan, but a specific group of hardcore karuta players are so skilled at this that they've "sportified" it by adding a memorization phase and becoming so good at card-taking that [[https://www.jstage.jst.go.jp/article/ipsjjip/26/0/26_38/_article/-char/ja/][20 ms error is only enough to correctly judge the winner 69.2% of the time]]. 

So it is with all high-skill, human-oriented activity; the more people do a thing the more that thing will come to resemble sport rather than diversion. Dance Games (e.g. DDR) are a fun example of this, because it has all the makings of an endurance sport despite being a video game. Dance game players [[https://www.youtube.com/watch?v=wiOOOAw2AfY][really push themselves]], and a substantial part of the "meta" is about efficient form, fitness, and successful engagement with your equipment (not, in my opinion, far off from cycling). In a year or so of playing I noticed my resting heart rate drop from 59 to the high 40s, and moving around in general just feels much easier for me compared to before I started playing. I'm not going to claim playing stepmania will make you lose a bunch of weight (at least not like [[https://planetbanatt.net/articles/health.html][tracking]] will), but cardio's effects on [[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3951958/#:~:text=Taken%2520together%252C%2520the%2520findings%2520across,tasks%2520requiring%2520top%252Ddown%2520cognitive][cognition]] alone constitute good enough reason to give it a shot if you manage to find a way to like it.

** You, Too, Can Dance

Contrary to what you may believe, you do not need to travel to an arcade multiple times a week to play dance games. In fact, you can play a nearly endless supply of intense, high-level charts from the comfort of your own home, provided you live on the ground floor, or hate your downstairs neighbors. 

Fundamentally, to play dance games, you will need two, maybe three things.

1. A pad
2. A bar, if you plan on using the bar
3. A game to connect the pad to

** Acquiring a Pad

For the sake of everybody's sanity, please do not bother "trying the game out" on a soft pad or a foam pad. Soft pads are notoriously horrible, they rarely properly register your steps, you will hate playing on it, and you will conclude you hate dance games even if you would have loved them with a better start. Save yourself the trouble and start on a pad which will listen to your feet, even if you are a beginner. If you do not know if you will like dance games (whether that is DDR, In The Groove, Pump It Up, or whatever), try to make your way out to an arcade and play on arcade pads. If that's fun, consider buying/building a hard pad, or going to the arcade more regularly.

If you are handy, you can build a pad with about $80 worth of parts. [[https://www.youtube.com/channel/UC5PzDDBBf5tIwItQRFnM0NA][Bandit]] has a great guide to building a very basic pad which you can find below.

#+BEGIN_EXPORT html
<iframe width="560" height="315" src="https://www.youtube.com/embed/y6wGYLE0YI4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
#+END_EXPORT

I primarily play on one of these pads and have cleared up to 14s on it. I find the panels are more than big enough to play tech charts on, as well. Just don't play on this barefoot since the panel edges are fairly sharp. For a bar, I use a walker I bought on amazon. Lots of people just use a chair.

#+BEGIN_EXPORT html
<iframe width="560" height="315" src="https://www.youtube.com/embed/Kkrlbx6Fp0o" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
#+END_EXPORT

If you don't like the idea of building something, the consensus best pre-built pad are [[https://www.maty-taneczne.pl/shop/dance-mat-ex-pro-metal-black/][L-Tek pads]], sometimes called "polish pads". Some players mod these pads to be more sensitive using "[[https://ddrpad.com/collections/l-tek-pad-parts/products/l-tek-copper-sensitivity-mod?variant=39375584493620][Penny Mods]]", and people use these modded pads to clear very difficult charts. They are a lot more expensive than building a cheap travel pad (including shipping it'll probably run you ~$350) but I have heard good things. 

** Playing the Game

The standard way to play 4-panel dance games (henceforth ITG) is through various forks of [[https://www.stepmania.com/][StepMania]]. I personally recommend [[https://www.itgmania.com/][ITGmania]], which is a 5.1 stepmania fork which is pre-built for higher level play / comes with some common themes. StepMania runs on toasters, there's a version floating around which runs on Raspberry Pi 3. I ran the game on my regular desktop computer started out, but I later bought a used dell optiplex from the stone age as a dedicated machine to run stepmania in my home gym. You don't need to buy anything new or fancy to run the game, it'll run on any old computer or laptop you happen to be using already.

*** Pack Recommendations for Beginners

Once you get the game, you'll want song packs. I recommend at minimum grabbing some DDR charts from [[https://zenius-i-vanisher.com/v5.2/simfiles.php?category=simfiles][Zanius-I-Vanisher]], the [[https://www.google.com/url?q=https://mega.nz/file/mEoyiQRB%2523D7VUynt69-l3gKLO_Uily2KwrZ618O3fBJts63SfUkU&sa=D&source=editors&ust=1656530549484752&usg=AOvVaw1R291ssfKUZNJPoW6-JS6V][original ITG and ITG 2 packs]] and [[https://docs.google.com/spreadsheets/d/1vnsJu85DxRA2Spq71g_MheY2B0_j99dPC1ap5RVQX-4/edit#gid=0][The Starter Pack of Stamina]]. In general the best place to go for new charts is [[http://itgpacks.com/][itgpacks.com]] which has everything nicely sorted by difficulty and chart type, just check the beginner tab first. Once you can clear ITG-scale 11s, I highly recommend getting into [[https://srpg6.groovestats.com/][stamina RPG]] as well.

** Progressing Advice (Stamina)

Getting better at the game is what keeps it from sucking as a form of exercise, so I have some notes on what helped me with different blocks below. The important thing is that the more you play, the more efficient your form will become, which becomes super noticable over a long period of time.

#+BEGIN_EXPORT html
<iframe width="560" height="315" src="https://www.youtube.com/embed/gMlmlBGlB8Q" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
#+END_EXPORT

** Breaking Through 10 block

Getting to 10 block (~15 new scale DDR) is mostly just about playing more, and learning to "walk". The two big things to know at this level are:

1. Put your foot on the arrow to step on the arrow, leave your foot on the panel after pressing the arrow, and lift that foot again only when you need that foot to press another arrow.
2. Try to alternate feet whenever possible. If you use the same foot twice in a row, you have to move your legs twice as fast.

If you try doing this, around 6-7 block you'll realize that there are some patterns where doing this is kind of hard. You'll have patterns where you have to put your right foot on the left arrow ("crossovers"), you'll have patterns where you have to step on the same arrow twice in a row ("jacks"), you'll have patterns where you have to step on two different arrows with the same foot ("double steps"), you'll have patterns where you have to travel the full distance from down to up, instead of just moving diagonally from down to right ("candles"). There are lots of different patterns and you shouldn't really stress out too much about it; just getting exposure to them will be enough at this level.

Different people spend different amount of time in this phase just depending on how generally coordinated, or experienced with rhythm games you are going into it. The important thing is to just enjoy yourself; there are hundreds of fun DDR charts specifically for players this level, and some very good beginner ITG packs which go far enough down in level to be playable by children. As long as the game is fun for you, it's all good if you remain at this level indefinitely: there will be more content than you can play even in hundreds of hours worth of sessions.

** Breaking through 11-14 block

TODO: Write this section a bit more fleshed out. Recommend: considering sock material/footwear, sweat management, going for jogs, minimizing form, sliding.

** My Stamina Block Milestones

Below are my first-passes for stamina charts in a given block level. It's fun to keep track of these, but they're not that important. 

| Block | Date    | Chart                            |
|-------+---------+----------------------------------|
|   11? | 09/2021 | Dancin KRONO Extended Remix [11] |
|    12 | 11/2021 | [12][130] Spontaneous Me         |
|    13 | 12/2021 | [13][134] March of the ants      |
|    14 | 02/2022 | [14][160] Katamari on the Rocks  |

