#+TITLE: Dance Games: How I Learned to Stop Worrying and Love Cardio
* Dance Games: How I Learned to Stop Worrying and Love Cardio

#+BEGIN_QUOTE
Draft: v1.0 | Posted: 08/23/2022 | Updated: 08/23/2022 | confidence of success: 30% | estimated time to completion: 08/23/2025 | importance: Low
#+END_QUOTE


** Abstract 

You probably don't like cardio. Most people don't. You probably like video games. Otherwise I'm not sure why you would be on my web page. If you grew up in the aughts like I did, you probably have played /[[https://en.wikipedia.org/wiki/Dance_Dance_Revolution][Dance Dance Revolution]]/ (DDR), and if you are like me, you probably liked it. People who grew up in the heyday of arcade culture still play dance games, and have managed to turn it into an endurance sport. If you like games, modern dance game setups are trivially inexpensive compared to the cost of most forms of cardio equipment, and it's fun. This page contains my notes on getting started, and how I have broken through different blocks for different methods of playing. I'm fairly average at these types of games, but I plan on updating this as I have more things to say.

** Sportification

I, like many people, didn't really care for cardio-based exercise once upon a time. I had a vague desire to move around more for health reasons, but the actual moving around part was not terribly enjoyable. I liked sports growing up, but coordinating people to play sports with, who have roughly the same schedule as you, etc was much harder in adulthood than it was in high school. So, I embarked in search of something which I could generally do alone, which was kind of sporty, relatively inexpensive, and would capture my interest for a long period of time. One arcade trip later, I decided upon dance games. 

I think the concept of sport is relatively interesting, since I think it is something which will naturally emerge from any high-skill activity which multiple people can compete in, either against some sort of objective function (e.g. running times, high scores) or directly against each other (i.e. opponents, opposing teams). My go-to answer to this is [[https://en.wikipedia.org/wiki/Competitive_karuta][Competitive Karuta]], a japanese card game for which players compete to find the second verse of a poem which is read aloud by a third party. This is generally an idle diversion in broader Japan, but a specific group of hardcore karuta players are so skilled at this that they've "sportified" it by adding a memorization phase and becoming so good at card-taking that [[https://www.jstage.jst.go.jp/article/ipsjjip/26/0/26_38/_article/-char/ja/][20 ms error is only enough to correctly judge the winner 69.2% of the time]]. 

So it is with all high-skill, human-oriented activity; the more people do a thing the more that thing will come to resemble sport rather than diversion. Dance Games (e.g. DDR) are a fun example of this, because it has all the makings of an endurance sport despite being a video game. Dance game players [[https://www.youtube.com/watch?v=wiOOOAw2AfY][really push themselves]], and a substantial part of the "meta" is about efficient form, fitness, and successful engagement with your equipment (not, in my opinion, far off from cycling). In a year or so of playing I noticed my resting heart rate drop from 59 to the high 40s, and moving around in general just feels much easier for me compared to before I started playing. I'm not going to claim playing stepmania will make you lose a bunch of weight (at least not like [[https://planetbanatt.net/articles/health.html][tracking]] will), but cardio's effects on [[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3951958/#:~:text=Taken%2520together%252C%2520the%2520findings%2520across,tasks%2520requiring%2520top%252Ddown%2520cognitive][cognition]] alone constitute good enough reason to give it a shot if you manage to find a way to like it.

** You, Too, Can Dance

Contrary to what you may believe, you do not need to travel to an arcade multiple times a week to play dance games. In fact, you can play a nearly endless supply of intense, high-level charts from the comfort of your own home, provided you live on the ground floor, or hate your downstairs neighbors. 

Fundamentally, to play dance games, you will need two, maybe three things.

1. A pad
2. A bar, if you plan on using the bar
3. A game to connect the pad to

** Acquiring a Pad

*** Please Do Not Start With a Soft Pad

For the sake of everybody's sanity, please do not bother "trying the game out" on a soft pad or a foam pad. Soft pads are notoriously horrible, they rarely properly register your steps, you will hate playing on it, and you will conclude you hate dance games even if you would have loved them with a better start. Some people may tell you "you can probably clear up to ITG 10s on soft pads", and while this is certainly true, the people saying this are [[https://en.wikipedia.org/wiki/Survivorship_bias][survivorship biasing]] you. Soft pads are pads which are servicable if you are desperate to play dance games, and will force you to play charts which are much lower than your "true" arcade block level. 

Save yourself the trouble and start on a pad which will listen to your feet, even if you are a beginner. You do not need a home setup right away if you are not sure whether or not you will like it. If you do not know if you will like dance games (whether that is DDR, In The Groove, Pump It Up, or whatever), try to make your way out to an arcade and play on arcade pads. You can find arcades near you using the [[https://zenius-i-vanisher.com/v5.2/arcades.php][Zanius-i-Vanisher arcade finder tool]]: just look for DDR / ITG / StepmaniaX / Pump It Up machines near you. If that's fun, consider buying/building a hard pad, or going to the arcade more regularly. 

*** Building a Pad

If you are handy, you can build a pad with about $80 worth of parts. [[https://www.youtube.com/channel/UC5PzDDBBf5tIwItQRFnM0NA][Bandit]] has a great guide to building a very basic pad which you can find below.

#+BEGIN_EXPORT html
<iframe width="560" height="315" src="https://www.youtube.com/embed/y6wGYLE0YI4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
#+END_EXPORT

I primarily play on one of these pads and have cleared up to ITG 14s / DDR 17s on it. I find the panels are more than big enough to play tech charts on, as well. Just don't play on this barefoot since the panel edges are fairly sharp. For a bar, I use a walker I bought on amazon. Lots of people just use a chair.

#+BEGIN_EXPORT html
<iframe width="560" height="315" src="https://www.youtube.com/embed/Kkrlbx6Fp0o" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
#+END_EXPORT

Other options to build pads can be found on the [[https://itgwiki.dominick.cc/en/hardware/itg-dance-pads][ITG wiki]], I am merely posting what worked for me.

*** Buying a Pad

If you don't like the idea of building something, the consensus best pre-built pad are [[https://www.maty-taneczne.pl/shop/dance-mat-ex-pro-metal-black/][L-Tek pads]], sometimes called "polish pads". I started using one of these pads when I moved to Los Angeles, and didn't have a car to drive around to hardware stores to buy materials to build one. Overall I agree that these pads are of high quality: they are a good option even out-of-the-box for beginner and intermediate players, and they are good pads both for tech charts and stamina charts. Ultimately I think I prefer the fsr pads, but there's no denying that L-Tek pads deliver an experience much closer to typical unmodded arcade pads compared to a travel pad.

If you want to get really into the game, I highly recommend modding your pads. There's two primary options: [[https://www.youtube.com/watch?v=Mi1IvZiLhL4][Penny Modding]], which you can do with tape and pennies lying around, or [[https://ddrpad.com/collections/l-tek-pad-parts/products/l-tek-copper-sensitivity-mod][copper tape modkits]] floating around on sites like DDRPad. I used the latter, and it was completely night and day -- hitting brackets (two panels with one foot) immediately went from impossible to fairly easy, and I could hit closer to the edges of the panels rather than needing to go all the way out to the center of each panel with my steps (which encourages good habits / tighter form).

Likewise, you'll probably need a bar. As mentioned before, there's lots of good options. I used a [[https://www.amazon.com/Booty-Kicker-Exercise-Portable-Exercises/dp/B089N3CKGZ][Booty Kicker Barre]] which is pretty popular in the dance game discords (I think it's for ballet exercises or something). One thing I've heard a lot is to avoid the L-Tek bar setup, which I hear is very wobbly and still expensive. You can really use anything.

** Playing the Game

The standard way to play 4-panel dance games (henceforth ITG) is through various forks of [[https://www.stepmania.com/][StepMania]]. I personally recommend [[https://www.itgmania.com/][ITGmania]], which is a 5.1 stepmania fork which is pre-built for higher level play / comes with some common themes. StepMania runs on toasters, there's a version floating around which runs on Raspberry Pi 3. I ran the game on my regular desktop computer started out, but I later bought a used dell optiplex from the stone age as a dedicated machine to run stepmania in my home gym. You don't need to buy anything new or fancy to run the game, it'll run on any old computer or laptop you happen to be using already.

*** Pack Recommendations for Beginners

Once you get the game, you'll want song packs. Generally speaking, I think it's good to get a pretty broad beginner exposure to the different /types/ of charts when you are new to the game. In my opinion, the best ways to do this are as follows:

- DDR: DDR charts from [[https://zenius-i-vanisher.com/v5.2/simfiles.php?category=simfiles][Zanius-I-Vanisher]]
- ITG Officials: the [[https://www.google.com/url?q=https://mega.nz/file/mEoyiQRB%2523D7VUynt69-l3gKLO_Uily2KwrZ618O3fBJts63SfUkU&sa=D&source=editors&ust=1656530549484752&usg=AOvVaw1R291ssfKUZNJPoW6-JS6V][original ITG and ITG 2 packs]]
- ITG Stamina: [[https://docs.google.com/spreadsheets/d/1vnsJu85DxRA2Spq71g_MheY2B0_j99dPC1ap5RVQX-4/edit#gid=0][The Starter Pack of Stamina]]
- ITG Tech: [[https://itl2023.groovestats.com/][ITL Online 2023 (or whatever is most recent)]]

ITL Online starts at around ITG 7 block, but the rest have lowers which go down all the way to complete beginner level. Once you can clear ITG 11s, I highly recommend getting into [[https://srpg6.groovestats.com/][stamina RPG]] as well.

** Progressing Advice

Getting better at the game is what keeps it from sucking as a form of exercise, so I have some notes on what helped me with different blocks below. The important thing is that the more you play, the more efficient your form will become, which becomes super noticable over a long period of time.

#+BEGIN_EXPORT html
<iframe width="560" height="315" src="https://www.youtube.com/embed/gMlmlBGlB8Q" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
#+END_EXPORT

** Breaking Through 10 block

Getting to 10 block (~15 new scale DDR) is mostly just about playing more, and learning to "walk". The two big things to know at this level are:

1. Put your foot on the arrow to step on the arrow, leave your foot on the panel after pressing the arrow, and lift that foot again only when you need that foot to press another arrow.
2. Try to alternate feet whenever possible. If you use the same foot twice in a row, you have to move your legs twice as fast.

If you try doing this, around 6-7 block you'll realize that there are some patterns where doing this is kind of hard. You'll have patterns where you have to put your right foot on the left arrow ("crossovers"), you'll have patterns where you have to step on the same arrow twice in a row ("jacks"), you'll have patterns where you have to step on two different arrows with the same foot ("double steps"), you'll have patterns where you have to travel the full distance from down to up, instead of just moving diagonally from down to right ("candles"). There are lots of different patterns and you shouldn't really stress out too much about it; just getting exposure to them will be enough at this level.

Different people spend different amount of time in this phase just depending on how generally coordinated, or experienced with rhythm games you are going into it. The important thing is to just enjoy yourself; there are hundreds of fun DDR charts specifically for players this level, and some very good beginner ITG packs which go far enough down in level to be playable by children. As long as the game is fun for you, it's all good if you remain at this level indefinitely: there will be more content than you can play even in hundreds of hours worth of sessions.

** Progression Advice for Stamina

Some advice which is semi-controversial, but has worked pretty well for me so far, is Beremy's [[https://itgwiki.dominick.cc/en/playstyles/stamina/thee-guide][thee guide]]. The basic idea here is: play 3x / week, take rest days, focus on playing bpm ranges where you cannot pass 64 measures of stream, make sure you eat enough protein. 

I get the impression /thee guide/ is kind of a meme, but the core idea matches what I've felt was the correct way to play with improvement in mind: stamina is about "passing the chart", so your sets should be charts which are hard to pass. You should spend a lot of your sets failing, and you should push that threshold higher as you pass harder and harder charts. It's somewhat difficult to manage mentally, and I do think it's good to play some longer stuff occasionally, but your sets should involve you pushing yourself if your aim is to improve.

 TODO: Write this section a bit more fleshed out. Recommend: considering sock material/footwear, sweat management, going for jogs, minimizing form, sliding.

** Progression Advice for Tech

Some notes I've seen suggested by good tech players:

- Play everything at every block level, play a lot.
- Play stuff you are bad at. If you struggle with something, play it until you can do it.
- When you are learning tech, focus more on /doing tech/ than getting good scores -- getting correct movements is more important than scoring marginally higher on a chart at your current level. (e.g. don't go back to jumps if brackets aren't working)
- Don't neglect playing stuff that feels "too easy", don't neglect playing stuff that feels "too hard".


** My Stamina Block Milestones

Below are my first-passes for stamina charts in a given block level. It's fun to keep track of these, but they're not that important. 

| Block | Date    | Chart                            |
|-------+---------+----------------------------------|
|   11? | 09/2021 | Dancin KRONO Extended Remix [11] |
|    12 | 11/2021 | [12][130] Spontaneous Me         |
|    13 | 12/2021 | [13][134] March of the ants      |
|    14 | 02/2022 | [14][160] Katamari on the Rocks  |

