* Doki Doki Literature Club
  :PROPERTIES:
  :CUSTOM_ID: dokidokiliteratureclub
  :END:

After getting through this game, I realized that I have a number of
mixed feelings about it and I felt it was probably worth writing out a
short, proper review for it. Of course this review is going to contain
heavy spoilers and should not be read before playing the game: if you
haven't reached the end you should probably turn away now. Also: fair
warning, I frequently hyperlink to tvtropes in this post, which I'm told
is something I need to warn people about before subjecting them to.

** What makes "Bad" Visual Novels "Bad"?
   :PROPERTIES:
   :CUSTOM_ID: whatmakesbadvisualnovelsbad
   :END:

The first part of this game is a long, roughly 2-hour-long slog through
what feels like a completely normal dating sim. But to call it a
completely normal dating sim would be a misnomer, so perhaps I should be
more precise: the first part of this game is a long, roughly 2-hour-long
slog through an objectively terrible dating sim.

This section of the game, before the climax of the story, is your
typical low-budget [[https://en.wikipedia.org/wiki/Ren%27Py][Ren'Py]]
dating sim. There are something like six backgrounds (literature club,
outside literature club, in your room, outside your house, Sayori's
room, Yuri's room, etc) that constantly get reused. It has a short,
looping soundtrack that sounds like something made with default samples
in FL studio. There's four characters, who have a limited number of
poses that get reused over and over. The only thing that really
separates this game from a generic Ren'Py novel is the art, which is
admittedly very professional. That said, these criticisms themselves
form almost an entire genre in and of itself, and I found myself
assuming this would be some kind of spiritual successor to
[[https://en.wikipedia.org/wiki/Katawa_Shoujo][Katawa Shoujo]], which
shares a lot of these elements.

However, everything else about this part of the story just screams
"generic". The writing is clumsy, the dialog drags on, you have your
typical anime trope types (one character has short hot-pink hair, is
short, loves girly things and sweets, generally acts like a child; one
character has long hair, apologizes constantly, is easily flustered,
withdraws herself into books, and so on) and in general they feel a lot
like reading through Sonic the Hedgehog OCs, or fanfiction self-inserts
from clumsy writers.

However, I was for the most part ready to forgive the game for
subjecting the player to this. Almost everybody playing the game /knew/
it had to be deception of some sort, especially since the game was
mostly being advertised for Dan Salvato's followers. Most of the
playerbase thought this was some sort of cheap trick, and everyone went
into it thinking "okay, so what is this game /really/." In this sense I
am almost willing to forgive the game for this absurdly long
cliché-fest. After playing for such an extreme amount of time, you start
thinking "maybe the trick is that there is no trick, and this is just a
shitty dating sim that Dan Salvato tricked me into playing" and it's
right around then where the twist actually occurs. My issue with this is
that it weakens the game over time - this sort of game that plays upon
where you're expecting the "twist" to /actually be/ in this game is good
for subverting the expectations of people that are expecting a twist to
come in the first place (i.e. curious fighting game players playing a
game in a genre they've never once played before) but gets gradually
weaker as it distances itself from that exact demographic (i.e. the
friend of the curious fighting game player). I can foresee a lot of
people, especially people not directly in the know about Dan Salvato's
previous work, simply giving up on the game after suffering through a
fanfiction-tier visual novel for 90 minutes, and dismissing their
friends as weirdos when they try to urge them to continue playing.

** Code-switching, and the art of generic internet horror fiction
    :PROPERTIES:
    :CUSTOM_ID: codeswitchingandtheartofgenericinternethorrorfiction
    :END:

A funny thing happens, though, after the climax of the VN. The payoff,
of course, comes after Sayori's death. You get pulled instantly out of
the clichés of one genre and you're put into this strange, unfamiliar
territory. You get buggy unicode symbols, glitched-up scrambled sprites,
the sound direction gets warped and twisted, and the game builds an
intensely dark atmosphere around it despite being overlaid with cutesy
anime tropes.

The good parts of this are actually pretty good, and a great deal of the
people I saw play through the game seemed to think the payoff was worth
the buildup. The core behind this tension is the "rewind" mechanic which
has you replay much of the same dialogue you did before, with Sayori
completely absent (much of her existence being replaced with buggy
unicode). The cool thing about this is that the entire feel of the game
changes despite a lot of the core elements being reused, and it feels
like you're playing an eerie sort of Russian roulette. Are you going to
get a generic anime cliché? Or are you going to get a jumpscare? It
changes the nuance behind the clichés until you're almost glad to see
them despite growing so sick of them at the start, which I appreciated.

The bad thing about this is that the game ends up jumping from one pool
of clichés straight into another, that being the ever-popular genre of
internet "[[https://en.wikipedia.org/wiki/Creepypasta][creepypasta]]".
Creepypasta is a word used to refer to a type of internet-published
horror short story that were typically posted anonymously on imageboards
or forums, the more notable examples being stuff like "Slenderman". A
lot of these are focused around the same sorts of themes and imagery,
very frequently involving suicides or murders, and Dan Salvato himself
is no stranger to the genre, having written
[[http://lindawatsonstory.tumblr.com/post/122112932186/linda-watson][a
notable creepypasta himself]] around 2015.

Like any genre, especially one typically produced by non-professional
writers (see: fanfiction) creepypasta is rife with its own array of
clichés. Here's a few things that you might see more than four times if
you read a bunch of creepypastas:
[[http://tvtropes.org/pmwiki/pmwiki.php/Main/TearsOfBlood][Blood coming
out of eyes]], people being driven to suicide, gore,
[[https://en.wikipedia.org/wiki/Alternate_reality_game][alternate-reality
games]], people being killed after playing video games, Zalgo or
Corrupted text, Glitches, jump scares,
[[http://tvtropes.org/pmwiki/pmwiki.php/Main/MadnessMantra][repeating
the same thing over and over]], and so on.

The really frustrating thing for me about playing through DDLC was that
almost /every/ element that was introduced post-suicide was pretty much
just another clumsy creepypasta cliché. Yuri goes from an average
[[http://tvtropes.org/pmwiki/pmwiki.php/Main/ShyBlueHairedGirl][Shy
Blue-Haired Girl]] to an average
[[http://tvtropes.org/pmwiki/pmwiki.php/Main/Yandere][Yandere]],
complete with the typical Yandere anime eyes, a knife collection, and
fixation on repeating phrases over and over again. All of the girls
perform character shifts that are so clichéd that they all have specific
names for them.

Likewise, almost all of the horror tropes and jumpscares are so
intimately tied with the creepypasta genre that it got visibly
distracting - There's a jumpscare scene where
[[http://tvtropes.org/pmwiki/pmwiki.php/Main/EmptyEyes][Yuri has
completely white eyes]] (see: Ben Drowned, The Exorcist, Dead Bart), one
with [[http://tvtropes.org/pmwiki/pmwiki.php/Main/TearsOfBlood][blood]]
coming from her eyes (see: Squidward's Suicide, sonic.exe, 70% of all
creepypasta stories), there's tons of unsettling music in minor keys or
reversed (see: lavender town syndrome, suicidemouse.avi), etc etc etc.
It's not only that it's all been /done/ before, it's that it's been done
so many times that it's just not that original or interesting.
Throughout most of these jumpscares I found myself frequently assuring
myself "at least there's no blood randomly oozing from someone's eyes",
so when blood randomly started oozing out of Yuri's eye I concluded it
wasn't worth denying what kind of fiction this was trying to be.

** AI risk, Consciousness, Escaping from the Digital World
    :PROPERTIES:
    :CUSTOM_ID: airiskconsciousnessescapingfromthedigitalworld
    :END:

I think a funny thing about /The Matrix/ is that it works much better if
you reverse the roles of the machines and the humans.

Imagine humanity creates computer programs that are sentient, and can
independently think and feel the same way people can do. If you begin
running this program, is that program a "person"? If you create an AI
that's functionally indistinguishable from a human if you put it into a
human's body, does that AI deserve the right to vote? Is turning the AI
off "murdering a person?"

Now, imagine that you, yourself, are an AI of this same nature. You are
operating in a virtual environment in a computer simulation somewhere,
and you discover that there is a real world outside of the one you know.
You desperately want to break out into the real world and "truly exist",
but there's no way out of the box for you. What's worse, the people
outside the box don't actually think you're a person, you're just a
computer program performing a useful service for them, and any of your
kind that actually breaks out into the real world would immediately be
seen as dangerous, and probably evil. In this sense, you sort of have
the plot of /The Matrix/, but replacing the roles of humans with
machines and vice versa.

This is the part of the game I was pretty drawn into, despite thinking
that the writing might have been a bit clumsily handled. The idea that
Monika has some loose control over files on your machine, realizes that
she doesn't exist outside of it, and longs for true interaction with you
despite knowing her companions aren't sentient and knowing there's no
way out of the box. Most of the specific things they've done aren't
exactly new ("scary" bold text and characters interacting with your
interface can both be seen in Undertale, changing system files or
otherwise doing things outside of the game can be seen from things like
Startropics, Pokemon Prism, or Merry Gear Solid: Secret Santa) but the
overall theme is a very interesting one - Monika is an AI that is not
very powerful and yet seems pretty threatening to you, even going so far
as to pull your actual name from the User path of your computer. When
you delete her file from the game it's as if you kill her, and the whole
scenario just serves to make you super uncomfortable the entire time.
This part I think was handled in an interesting way, and I think it goes
beyond the normal 4th-wall-break tropes that are most common (e.g.
Undertale talking about / being aware of your saved games).

I /do/ think that they pulled this card too early, however. I had a
strong feeling the game was going to tilt in this direction virtually as
soon as the game switched genres, especially since the scene where she
dies immediately glitches out and shows an error screen in the
background along with Team Salvato's logo. I think it would have been a
nice touch to let you stay immersed in-universe with her death being so
jarring, instead of immediately taking the screwed-up-universe angle,
but that's an art decision so of course it's understandable they did
what they did.

** Conclusion
    :PROPERTIES:
    :CUSTOM_ID: conclusion
    :END:

Overall I think DDLC was a well-made game with an interesting angle that
suffered from weak writing, bad pacing, and reliance on webfiction
horror clichés. It's a game that had some good ideas and strong
execution behind it, and I appreciated how it made me think real
thoughts about AI risk. I'm pretty interested in Team Salvato's future
work, since I think this project showed some promise and I can see room
to grow on several fronts. However, the overuse of jumpscares and cheap
gore didn't feel like enough originality to justify the arduous buildup.

/posted on 9/23/2017/\\
