* Energy Drink Tier List

/Last Updated 3-18-20/

Over the last several months I have been drinking a lot of energy drinks as a slightly more fun way of consuming caffeine before workouts / focus sessions, and I thought I would assemble a list of my thoughts on each one.

Given that my ability to obtain random single flavors has been significantly hampered by the global pandemic happening right now, I've decided I'm just going to upload what I have right now and then add to it slowly as I accrue more and more flavors. So far I've tried about 30, so expect this list to grow as I go on this journey. 

** Some up-front disclaimers

*** Energy Drinks are Expensive!

Energy drinks are not an efficient means of doing anything. If you want caffeine in the cheapest way possible, purchase caffeine tablets off of amazon. They are like $0.04 per 100mg serving, meaning you can just take one or two with some tap water and immediately have 90%+ of the same effect of monster or whatever. If you want preworkout, add on some [[https://examine.com/supplements/beta-alanine/][beta alanine]] and [[https://examine.com/supplements/citrulline/][citrulline]], which provide some muscular endurance and fatigue/soreness reduction, respectively. If you want to shell out the money for a fun can of almost soda which has some useful things in it, feel free to drink energy drinks. 

*** Energy Drinks are Not Good Preworkouts

This is correct, usually they're not as good as actual preworkouts for use as preworkouts. But caffeine really gets you 90% of the way there, and it's more fun to try 30 flavors of energy drink over the course of a few weeks rather than try 30 different tubs of preworkout over the course of probably years. If your energy drink doesn't have citrulline or whatever, just take some with it.

*** Energy Drinks are Bad For You

Of course they are bad for you. That said, the badness of energy drinks is, I find, [[https://examine.com/nutrition/are-energy-drinks-bad-for-you/][vastly]] [[https://examine.com/nutrition/the-mild-health-risks-of-energy-drinks/][overstated]] especially when explicitly paired with stuff like resistance training, for which their active ingredients frequently help out with [[https://link.springer.com/article/10.1007/s00421-007-0557-x][strength]] and [[https://pdfs.semanticscholar.org/12b4/7c27f774c7968b80d8309a3300a9a9901f09.pdf][anaerobic capability]]. You obviously don't want to go nuts with these things but as long as you stay under the FDA's safe zone of 400mg per day from all sources it's really not going to be the worst thing in the world (probably).

*** Just Drink Water!

Water doesn't have caffeine in it. Mixing caffeine with water tastes awful. I drink plenty of water, and generally speaking don't drink more than one energy drink on any given day. Please, I beg you, go away.

** Tier List

TODO: Add more notes about the flavors of each of these.

Some keys:

$^c$ - has a flavor a lot like candy; potentially overly sweet, which is a turnoff to some people

$^m$ - contains milk, which I have a hard time drinking and usually docks points for me off of otherwise good drinks

$^\uparrow$ - Has a lot of caffeine, usually labeled 

*** S

- *Monster Zero Ultra (white)* Perhaps sort of a meme to have this in S tier but my relatively informed opinion on this is that it is still quite good
- *Monster Green Tea* Not very common but amazing whenever I find it
- *Monster Ultra Sunrise (Orange)* Pretty much orange soda

*** A

- *Monster Ultra Blue* Possible S tier, need to try again
- *Reign Sour Apple* $^{c \uparrow 300mg}$ You will probably like it if you think "caffeinated green jolly rancher" sounds appealing to you
- *Reign Blue Razz* $^{\uparrow 300mg}$
- *Monster Ultra Red* $^c$
- *3D Strawberry (Chrome)* $^{\uparrow 200mg}$
- *Reign Mango* $^{\uparrow 300mg}$ Would probably like this more if I liked mango in general more, but it is a good flavor
- *Monster Ultra Paradise (Green)* $^c$ see reign sour apple, but more sickly sweet

*** A-

- *Reign Orange Dreamsicle* $^{c \uparrow 300mg}$ orange cream flavor definitely very well captured imo
- *Reign Strawberry Sublime* $^{c \uparrow 300mg}$
- *Red Bull Crisp Pear*

*** B+

- *Reign Melon Mania* $^{\uparrow 300mg}$
- *Adrenaline Shoc Frozen Ice* $^{c \uparrow 300mg}$
- *Monster Ultra Fiesta*
- *Monster Ultra Rose*
- *Monster White Tea*
- *Monster Watermelon*
- *Bang Sour Heads* $^{c \uparrow 300mg}$
- *Bang Blue Razz* $^{\uparrow 300mg}$
- *Sugar Free Red Bull* Low caffeine content + high price hurts this, but it tastes good
- *Red Bull Zero* Tastes pretty much exactly the same as sugar free red bull
- *Adrenaline Shoc Watermelon* $^{c \uparrow 300mg}$

*** B

B tier and below is where I start deciding I mostly would rather not be drinking these

- *Adrenaline Shoc Fruit Punch* $^{\uparrow 300mg}$ Tastes like overly sweet fruit punch
- *Adrenaline Shoc Mango Peach* $^{\uparrow 300mg}$
- *Monster Energy Iced Tea* $^c$
- *Monster Rehab Lemonade + Tea*
- *Monster Java Mean Bean* Just shy of 200mg caffeine, tastes pretty good if you like coffee with milk but an unfortunate one if you are lactose intolerant.
- *Bang Berry Bangster* $^{c \uparrow 300mg}$
- *Red Bull (Regular)*
- *Uptime, Sugarfree* notably has L-Theanine in it
- *Reign Inferno Red Dragon* $^{\uparrow 300mg}$

*** B-

- *Adrenaline Shoc Sour Candy* $^{\uparrow 300mg}$ it's very, very sour
- *Adrenaline Shoc Acai Berry* $^{\uparrow 300mg}$
- *Monster Rehab Orangeade*
- *Uptime, Original Citrus* think "capri sun for adults", also has L-theanine in it
- *Monster Rehab Raspberry Tea*

*** C+

- *Reign Inferno True Blu* $^{\uparrow 300mg}$
- *Rockstar Thermo Neon Blast* $^{\uparrow 300mg}$ tastes okay but avant garde, weird waxy aftertaste
- *Arenaline Shoc Cotton Candy* $^{\uparrow 300mg}$

*** C 

- *Bang Star Blast* $^{c \uparrow 300mg}$
- *Low Carb Blue Monster*
- *Bang Rainbow Unicorn* $^{c \uparrow 300mg}$
- *Reign Lemon* $^{\uparrow 300mg}$ as my SO put it: "it tastes like danger"
- *Rockstar Peach Iced Tea* $^{\uparrow 300mg}$
- *Bang Cotton Candy* $^{\uparrow 300mg}$

*** C-

- *Standard Monster*
- *Monster Zero Sugar* minimal difference from normal flavor
- *Monster Absolute Zero* I'm not even sure this is a different flavor from zero sugar or if the cans just come in pairs
- *Hi-Ball Blood Orange*
- *Bang Frose Rose* $^{\uparrow 300mg}$
- *Adrenaline Shoc, Black* $^{c \uparrow 300mg}$

*** D

Everything below D tier I would call "atrocious"

- *Rockstar, in general*
- *Monster Ultra Violet* 
- *Coke Energy* 
- *Cherry Coke Energy*
- *Reign Cotton Candy* $^{\uparrow 300mg}$

*** D- 

- *Bang Miami Cola* $^{\uparrow 300mg}$ imagine the unpleasantness of giving budget cola at a restaurant instead of coke, which you asked for, but multiply that unpleasantness by ten thousand times.

*** F 

- *Reign Thermogenic Jalapeno Strawberry* $^{\uparrow 300mg}$ I am baffled they sell this, and am convinced it is a novelty flavor. I was talked into buying this explicitly so I could put it in this list, and even so I regret having to drink this.
- *Bang Birthday Cake Bash* $^{c \uparrow 300mg}$ tastes like cake made with expired milk


** Overarching Thoughts on the Institution of Energy Drinks

*** Caffeine Content

I really can't stress how mind-bending it is to me that so many of these drinks contain 300 milligrams of caffeine in them. For scale, that's something like 3-5 cups of coffee, all at once in one beverage. A number of the below drinks contain that amount and I certainly cannot recommend them unless you are explicitly going to exert yourself in some way immediately after (e.g. lifting weights). 

*** Sugar Content / Calories

I have a very strong preference against drinks with sugar / caloric content in general. You might think this is because I think they add empty calories in exchange for no actual nutritional benefits. You would be half right, but I also think generally speaking non-diet soda just tastes pretty terrible (see: diet coke vs regular coke). As such please keep in mind that I have this relatively extreme bias, and that most of the sugary energy drinks are ranked fairly low as a consequence.

*** I Wish There Were More Samplers

Generally speaking, I don't know how you could arrive at opinions about this sort of thing unless you get to try tons and tons of flavors. I know wine people have wine tasting parties where you drink a sip or two of many different kinds of wines, and I am a bit frustrated that I'm doing the caffeine equivalent of buying many bottles of wine, even if I end up hating the bottle. Likewise preworkout doesn't usually come in single serving packets (and even if they did, they would be all the same flavor), so I wish there was a generally more efficient way of doing this compared to just purchasing tons of things and then finishing them.


** Remaining To-Do items

- Some interesting visualizations would be fun probably
  - Caffeine content vs score
  - Subjective candy-ness vs score
- Drink more energy drinks
  - 3D Energy Drinks (enjoyed the one flavor I've tried)
  - Misc stragglers of the brands I've tried


** Updates

- 4/12/20: added six drinks, moved a few things around based on new criteria
- 4/26/20: added 10ish drinks
