#+TITLE:The Genie

* The Genie

It's 2016, and for the third night in a row, I can't fell asleep.

I'm sure that what I am doing probably /counts/ as sleeping in some way. For the last two nights, I have laid in bed for what seems like roughly 8 hours fully awake, but so exhausted that I probably am not noticing if I lose consciousness for brief periods. I have spoken to multiple doctors about this and have been given advice which ranges from useless ("drink milk before bed") to offensive ("Looks like you didn't sleep in the sleep study. Nothing we can do with no data. That will be one thousand dollars."). It feels like it's never going to end, like I'm trapped in a personal hell of permanent exhaustion, confounding all medical science. I used to have so much energy. I used to be so good at studying. Now I'm a pile of rubble reduced to staring at the blank wall for hours every night.

I get out of bed, since lying here is boring and it doesn't seem like I'm going to get any sleep anyways. I slump into my creaky, university-provided wooden chair. I've taken up repairing old, broken Gamecube controllers recently, since we sometime need spare controllers in the Smash club that I've been running at this school. A number of them are scattered across my desk, all broken. Some are not that bad, just worn down thumbsticks or frayed cables. Some are completely destroyed, cracked circuit boards, water damage, stuff like that. In some twisted way I see myself in the controllers on my desk -- something which used to be full of life, artifacts of joy, things once loved which might never come back to their former selves. I'm not that good at fixing these things; often all I am doing is taking the parts from multiple broken controllers and trying to form a single controller-of-theseus which works. But something about doing this feels like I am performing an act of healing, like something I'm doing to the controllers could eventually be done upon me to make me "work" again.

This feels like nonsense to think about, but like I mentioned, I have not really slept in several days. You'll have to forgive my deluded, loopy thoughts. The closest controller on my desk looks particularly destroyed, so I begin the methodical process of unscrewing the six tiny triwing screws. These are horribly stripped, so opening it is a huge pain. I'll definitely need to replace these with spare screws.

Finally, I manage to get it open. There is an outrageous amount of dust inside this controller, so I blow upon it to get it all off. The dust forms a giant cloud. In retrospect, I probably should have shaken it into a trash can or something. Slowly, the dust cloud starts to swirl in an unusual way, almost like it's alive. The shapes solidify into connected, modular components, lazily floating into a vaguely humanoid shape. I can see it start to stretch and shake it's appendages.

"Ahh!" spoke the dust. "It was terribly cramped in there. I was so sure I would end up trapped in some landfill for all eternity. Thank goodness I can stretch my legs again."

This is the weirdest hallucination I've ever seen. Maybe I did fall asleep, after all.

"Alright." The dust cracks its knuckles. "I'm sure you know the deal, people your age knew what Genies were when I was trapped in there around 2003. Are you religious? Any food allergies, or anything that would prevent you from claiming your rewards?"

I blinked at the figure of dust. "You're a Genie," I said. I looked over at the alarm clock on my desk, which read /4:33 AM/. "You're telling me I freed a Genie inside a Gamecube controller at 4am".

"Yup," spoke the Genie. "Originally the Djinn were trapped in artifacts by King Solomon in 955 BC, but you know how these 'RETVRN' kids are these days, they're learning the sealing majicks and stuff. Anyways, it's not too different from what you've probably heard of. Three wishes, no inherent strings attached, Genie corporation assumes no responsibility for poor wishes borne in hubris which cause sorrow and regret."

I like this guy, probably because he's a figment of my imagination. I'm sure this is some sort of weird dream, so I'm willing to play along. "No use wishing to become president, then, huh?"

The genie put his hands to his face so quickly that his arms phased through his head. "Why do you think I got sealed in the controller in the first place? Anyways, let's get this over with".

"I'll be frank with you," I said to the Genie. "I am pretty sure I am just half-awake dreaming here, since I've had severe sleep problems for the last couple of years. More than anything right now, I just want to be able to consistently sleep again. I want to learn whatever is causing this problem, and be able to treat it so it goes away quickly."

The genie tried to snap his fingers, but as he was made of dust, there was no sound. "Uh, snap!" The genie said, "your first wish has been granted. Go to the doctor and ask for a blood test, there's something wrong with your blood and it will be fixed in 2 weeks."

Now I'm sure it's a dream. Can you imagine how stupid it would be if none of the doctors I saw did a routine blood test after seeing me, and that ended up being the problem? Two weeks to fix a years-long health problem? I would resent doctors forever. "Okay, well, that was the big one. I guess we can live a little bit from here. I wish for the most beautiful girl I know to fall in love with me."

The genie laughed at me. "Wish granted, I guess. In a few years you and that girl will be happily married." The genie crossed its arms. "Come on, man, I know we're supposed to warn you about the hubris of your wishes, but you aren't making me work very hard here. Let's go crazy with this last one. Wish for something you think is truly impossible."

I was a bit too exhausted to consider the implications of his comment. "Okay, well, how about this. I wish for the opportunity to prove that I'm still good at studying. My college experience was kind of ruined by this whole sleeping thing. I wish I could get the chance to try this again with good health, for me to get good grades and to be able to believe I am good at it again, and that I wasn't permanently made dumber by these health issues."

The genie shrugged. "You got it. In a few years, you will get a job at an institution affiliated with Hopkins, and you will get to enroll in the part-time masters degree program they offer. You'll do great in this program, you'll get a masters degree in a field you care about, you'll graduate with honors, and the majority of it will be paid for by your employers."

"Wow," I said "that's a bit more involved than the other wishes".

The genie just smiled, and in a whorl of dust, the genie dispersed into the atmosphere.

"Well," I said, after he left. "I should probably check into a mental institution soon. Just in case, I'll get that blood test first".

A flash of light appeared at my window, and suddenly a version of myself with longer hair appeared in the corner of my room. "Oh, Jesus Christ," I said.

"Am I too late? Did you free him?" pleaded the other me.

"Who are you? How did you get here?"

"I am you from ten years in the future, how I got here is not important. Did you use the third wish?" He started looking around the room, and made a heartbroken, dejected expression when he saw the opened controller.

"I did use the wishes" I found myself explaining my hallucination to my hallucination. "I, uh, did I do something bad?"

The other me threw his hands up in frustration. "God /damn it/. I was /this close/ to fixing that third wish."

"What happened with the third wish?"

"That program was a huge waste of time!" whined the other me. "Do you not remember what it felt like to not be challenged? How boring that was? You could have just wished for wisdom, you could have wished for anything. You could have wished for wealth. Do you have any idea how much housing costs now?"

I blinked at him. "You mean, it worked? I got the chance to prove myself, and I did?"

"Yes," the other me said flatly, "you proved yourself. It was a lot of time, you didn't learn very much, and by the time you get it completed nobody else cares about the fact that you do or do not have this credential. A lot about the world changes by the time you get there, and you'll wish you spent that time doing something more challenging instead."

"And you are... unhappy about this? I'm doing /so much better/ in ten years that I'm not even happy about this?"

"You could have wished for /anything/! You could have just wished to be good at the thing you were going to study."

I smiled at him. To be so dissatisfied with the lack of challenge needed to prove myself is a future I could not even begin to imagine to be possible in my current state. "I guess that's your job now" I said to myself.

He groaned at me "You were such a smartass back then. I'm going home. Make sure you get that blood test." He vanished in another flash of light.

As far as weird dreams go, this one wasn't so bad.
