* The Saccharine Prison

The sun is so bright. The sun is always so god damn bright.

Elijah groggily began to roll out of the hammock he had been sleeping on. The rays of sunlight cast into his room with the perfect, gentle warmth, right at a cozy temperature just warm enough to feel friendly and inviting. It was always cast upon him at the same time, every day. It was always this temperature, these same beautiful beautiful rays at this same beautiful beautiful temperature.

It was Heaven. He had been living in Heaven for quite some time now, and he had to admit that God had done a pretty good job, and that the promised land had, in fact, lived up to those lofty promises. But the monotony of those promises had somehow begin to wear upon him, like a part of him was longing, just once, for a bitter wind instead of beautiful warm rays.

When God had descended from the Heaven in the late 2030s, he had announced that he would select a single human at random back to Heaven as a show of compassion to humanity, and by fate's will God had selected him, a 27-year-old kid from a quiet suburb in Michigan. He was like the winner of a divine sweepstakes, a single human gifted direct access to eternity in paradise. Every morning these beautifully warm rays woke him up from this beautifully comfortable hammock, and he would get out of bed and experience a day filled with whatever interesting experiences he could possibly desire. He could spend all day with the immortal souls of his departed friends and family, and every day was beautiful and perfect.

But Elijah was not an immortal soul brought to Heaven. He was a human brought into heaven, alive. He was not built to live in Heaven, and in some ways was like an imperfect splinter lodged in the body of paradise. God knew it would have sent the wrong message to end Elijah's life in order to bring his immortal soul to heaven -- it would not be such a show of compassion for God to descend from the heavens and then kill one person at random. In his eternal grace, he simply brought Elijah to heaven immediately, something he's done several times before in rare, important cases.

But at the end of the day, Elijah was not an important person with notably resolute, important spirituality. He had gone to church as a child, but he stopped going after he had grown a bit older. He worked in a warehouse, where he needed to move boxes from one shelf to another shelf for most of the day. God had never brought a regular person like him into Heaven like this before.

Normal people suffer from a malady known as the [[https://en.wikipedia.org/wiki/Hedonic_treadmill][hedonic treadmill]]. In general, they aren't very good at predicting what sorts of life events will make them more or less happy. People often think that losing a limb in a tragic accident would make them very unhappy forever, which sounds obvious to the point of absurdity. But in general, people with missing limbs tend to report themselves as being fairly happy, all things considered: the missing limb causes them problems in daily life, but people generally tend to learn to live with it and adapt fairly well. The same is true, for example, in lottery winners, where they find that the immense windfall didn't really make them much happier than they were before, even though their lifestyle changed a lot. Normal people are generally wired to get over it quickly. You generally need to, in order to live on in daily life.

Despite being a member of "normal people", Elijah lacked this need. He did not need to get over anything. His environment was perfectly, dynamically adapted to provide him an unlimited stream of infinite happiness. Elijah had developed a pet theory that, in death, the ability to retain infinite happiness indefinitely is imbued into the immortal soul. But he was a normal human, still living in a normal human body, and try as he could, he could not prevent himself from re-internalizing infinite happiness as "the normal amount".

Elijah was not about to complain about this. To even call it "complaining" would misrepresent the nature of what was happening inside his head. When Elijah lived in the world of the living, he would feel bad about problems in his life, and would feel good about the nice things in his life. It had been a permanent fixture of his psychology that feeling bad came from problems, and feeling good came from the best parts of life. Living in paradise, he was simply forced to acknowledge that these things were actually decoupled -- that feeling bad was an internal process independent from having problems, and the only reason this never occurred to him is that it is unnatural for a person to simply not have any problems.

He looked up at the shimmering light, the same shimmering light that spilled out of the window every single morning to prepare him for another flawless, beautiful day. It filled him with happiness once more, as it did every morning, like an ant perpetually living underneath a magnifying glass.

---

Elijah saw God. He was "in perfect communion" with him, as they told him, so he had immediate access to God whenever he wanted. God looked like Elijah, but also just like everybody else -- the first time he had looked at God he had been so moved, so filled with love for humanity, that he sobbed for what felt like days. Now, in seeing him, it had become merely a somewhat pleasant thing to look forward to on a given day.

"My son," said God, "what troubles you?"

"I don't like how this feels. I don't think I was meant to experience this in my body. Is it possible that I will ever die here, in Heaven? Is it possible I'll ever turn into an immortal soul?"

God shook his head. "Nothing here could ever harm you, my child, you will live on in paradise for eternity."

"Could you turn me into an immortal soul?"

God again shook his head. "I could never harm you within the confines of paradise."

"Then, can I kill myself? Can I turn to an immortal soul myself?"

For a third time, God shook his head. "The punishment for ending your own life is eternity in damnation."

And hearing this, Elijah became the first to dispair within the gates of Heaven. The gift of eternal joy, granted to someone prevented forever from experiencing that joy in its divine unlimitedness; trapped indefinitely outside of the experience of heaven while actively living within it; eternal damnation in the saccharine prison. 
