#+TITLE: Making Myself Drink Huel
* Thoughts on Huel

Longtime followers of my writing probably know that I really like [[https://planetbanatt.net/articles/energydrink.html][energy drinks]]. More specifically, I like drinking new energy drinks, even when I have a feeling they are going to taste bad. I feel like everybody got one or two weird things during the COVID-19 lockdown, and my two weird things were energy drinks and [[https://planetbanatt.net/articles/dancegames.html][ITG/DDR]]. 

I've been wanting to play ITG in longer sessions without getting as tired, so I decided the time has come for me to try to lose a bit of weight -- something I have done [[https://planetbanatt.net/articles/health.html][in the past]]. While there are occasional roadblocks, this is generally not so bad for me; I like to exercise, and I'm relatively good at the weird monastic discipline required to stick to caloric restriction. 

However, rather than trying to do the same thing I did the last time I seriously tried to lose weight, I figured I would try to do a much funnier version -- I would lose weight primarily with my newly adopted COVID-19 personality quirks, namely ITG and drinking weird bad tasting beverages.

** Enter Huel

Huel is a meal replacement beverage, similar to Soylent. I didn't do that much research onto why people prefer one over the other, and I'll probably get around to trying different ones later. I have heard these things taste absolutely terrible, which was part of the reason I ended up deciding that this would be the funniest possible way to lose weight. This highlights something I have decided to start calling *"Eryk's Law of Bits"*: if you start doing something challenging, you will have a much better chance of sticking with it if you decide you are doing it to run an extended bit. It seems stupid to do things this way, but I've found that doing things because they are funny is a much more powerful motivator than doing things because they are vaguely "good for you" or "healthy" or "impressive", all of which I've found to be crushingly weak motivators. 

To reiterate, I'm doing almost nothing different compared to the last time I attempted to lose weight. I'm not measuring things as carefully (I eat lunch at work and it would be a bit weird for me to bring the food scale to work compared to just eating more broccoli), but ultimately I'm trying to eat fewer calories and move around more (walking, cardio, etc). If you want a post about how this can be simple, even encouraging, and how you, too, can reach your goals, I have [[https://planetbanatt.net/articles/health.html][already written this post]]. If you want to read some notes about me being a weird freak and drinking meal replacement beverages for fun, then welcome to paradise. 

** Huel Flavor Notes / Tier List

I do not know ahead of time whether any of these will cross the threshold into "reasonable food" territory. If they do, I think it ought to be regarded with a degree of suspicion. I suspect a possible thing which can happen is that I'll drink enough of these to get used to it and brainwash myself into thinking that they're actually worthy replacements for a nice meal, so I think an important additional variable to keep track of is /when/ I drink each individual flavor. 

*** Banana White RTD (5/9/23) 7/10

Originally planned to drink these mostly on the weekends, but the box arrived at my apartment and my curiosity got the best of me. Honestly, I've certainly had worse energy drinks. It tastes a little synthetic, kind of like a banana that was made in a lab where they couldn't quite get it right. Taste wise it wasn't so bad, but it wasn't terribly filling for 400 calories.

An update to this: this is one of the few huel flavors that my wife does not mind eating (yes, I have roped her into this somehow as well. For more on persuasion, please see Cialdini's /influence: the psychology of persuasion/). If you have not already torched your expectations by drinking chocolate protein powder, this probably tastes the most like "a relatively normal fruit smoothie" compared to the other flavors' "a surprisingly filling protein shake". As such, I have bumped this up by 0.5 points -- it has some staying power.

*** Chocolate White RTD (5/10/23) 7/10

I think this tastes a bit less like "food" compared to banana. It tastes, in my opinion, a bit better than Banana, and the texture is slightly more tolerable in chocolate form. The general lack of sweetness in these beverages I think works well with chocolate, which works fairly well even a bit bitter. Overall better than expected! 

*** Berry White RTD (5/11/23) 4.5/10

Gotta say, tastes weird. Still drinkable enough. It doesn't really taste like berry, it tastes like the berry flavoring they use for captain crunch. But like, worse.

*** Vanilla White RTD (5/13/23) 3/10

Eww. I once had vanilla casein protein powder which I got scammed into thinking would be good for baking, and this pretty much tastes just like that to the letter. I had to throw out that tub of casein fairly quickly because I hated it so much. Drinking all four of these in the variety box is going to be very difficult.

*** Hot and Savory Pasta Bolognese (5/13/13) 6/10

After a full day of only meal replacement drinks, I'm going into this excited that I get to eat some solid food. Admittedly two huel RTDs and one scoop of whey protein with water has filled me up pretty well, but I think 930 kcal is not an appropriate amount of food to be eating so I'm eating a bit of this stuff as well. Cooking it was pretty convenient, as far as instant meals go. 

The huel pasta was generally pretty mediocre. The biggest shock to me was that the taste was really mild, to the point of being honestly quite bland -- visually it looks like it's supposed to have a lot of seasoning in it, but it pretty much just tastes like pasta and tomato sauce. It seems super healthy from the macros, and it was easy to cook, but I think I'm going to need to get some sort of hot sauce or seasoning to use when I prepare this in the future. I'll admit I am a bit disappointed: it's kind of bland, and it probably needs additional ingredients to make it go the distance, which reduces its convenience. I will say, it sort of just seems like normal food (albeit normal food that has been freeze dried), so my criticism here comes from a place comparing it to other real food: it's probably better than the RTD drinks, but it's less funny that it's mediocre.

**** TIPS TO MAKE THIS TOLERABLE

You can add sriracha to this and it becomes a little more tolerable. Sriracha is also vegan, so that shouldn't shift much of anything for most people. Sriracha with pasta bolognese is certainly a bit weird, but so far this is the best I've got. Everything else I have tried just made it worse.

*** Strawberry Shortcake RTD (5/25/23) 6/10

The first of the v2 flavors. I had a big lunch and then did a big workout, so I'm going into this pretty excited to get some food. Drinking it, I'm a little ambivalent. At this point I am starting to be able to perceive the gestalt of "huel taste" common to all of these beverages, and this more than the v1 bottle just tastes like huel with some cheap strawberry flavoring tacked on top of it. At first I thought "oh, it is interesting that this tastes sweeter than the chocolate version, even though they are probably the same. I wonder if that's because of a mental association with each flavor and a level of sweetness." However, I looked at the bottle and these just have 5g of sugar instead of 2g of sugar, which explains that. You might like this one more if you like sweeter stuff, and while it still tastes weird it's still a fair improvement over the Berry flavor from the v1 box. Overall not bad, but not good.

*** Cinnamon Roll RTD (5/26/23) 2/10

Tastes like I am drinking a candle. Would not recommend. 

*** Salted Caramel RTD (5/27/23) 4/10

Not really a fan. This doesn't taste sweet enough to really sell "caramel" as the flavor it's going for, and it tastes kinda salty (as the name suggests) which makes me actively feel thirstier as I drink it. "It tastes like sea water" is perhaps a bit harsh to describe this, but it's fairly close. If sea water tasted like this I would be like "oh, wow, this sea water tastes like food!" which is perhaps not a stunning endorsement for this product.

*** Iced Coffee Caramel RTD (5/28/23) 7/10

Pretty much what it says on the label. Tastes like coffee. There's actually 65 mg of caffeine in this, which is amusing. The texture makes it weirder than any coffee I've ever had (and I'm honestly not a big coffee guy) but if you like coffee then this is probably a good bet for you as far as huel flavors go.

*** Chocolate Black Edition (1/22/24) 6/10

The black editions in general have way more protein than the alternatives. What you get in exchange for this benefit, of course, is that it tastes more like protein powder (i.e quite a bit worse).

*** Mint Chocolate () /10

A relatively new flavor! 
