#+TITLE: Making Myself Drink Huel
* Thoughts on Huel

Longtime followers of my writing probably know that I really like [[https://planetbanatt.net/articles/energydrink.html][energy drinks]]. More specifically, I like drinking new energy drinks, even when I have a feeling they are going to taste bad. I feel like everybody got one or two weird things during the COVID-19 lockdown, and my two weird things were energy drinks and [[https://planetbanatt.net/articles/dancegames.html][ITG/DDR]]. 

I've been wanting to play ITG in longer sessions without getting as tired, so I decided the time has come for me to try to lose a bit of weight -- something I have done [[https://planetbanatt.net/articles/health.html][in the past]]. While there are occasional roadblocks, this is generally not so bad for me; I like to exercise, and I'm relatively good at the weird monastic discipline required to stick to caloric restriction. 

However, rather than trying to do the same thing I did the last time I seriously tried to lose weight, I figured I would try to do a much funnier version -- I would lose weight primarily with my newly adopted COVID-19 personality quirks, namely ITG and drinking weird bad tasting beverages.

** Enter Huel

Huel is a meal replacement beverage, similar to Soylent. I didn't do that much research onto why people prefer one over the other, and I'll probably get around to trying different ones later. I have heard these things taste absolutely terrible, which was part of the reason I ended up deciding that this would be the funniest possible way to lose weight. This highlights something I have decided to start calling "Eryk's Law of Bits": if you start doing something challenging, you will have a much better chance of sticking with it if you decide you are doing it to run an extended bit. It seems stupid to do things this way, but I've found that doing things because they are funny is a much more powerful motivator than doing things because they are vaguely "good for you" or "healthy" or "impressive", all of which I've found to be crushingly weak motivators. 

To reiterate, I'm doing almost nothing different compared to the last time I attempted to lose weight. I'm not measuring things as carefully (I eat lunch at work and it would be a bit weird for me to bring the food scale to work compared to just eating more broccoli), but ultimately I'm trying to eat fewer calories and move around more (walking, cardio, etc). If you want a post about how this can be simple, even encouraging, and how you, too, can reach your goals, I have [[https://planetbanatt.net/articles/health.html][already written this post]]. If you want to read some notes about me being a weird freak and drinking meal replacement beverages for fun, then welcome to paradise. 

** Huel Flavor Notes / Tier List

I do not know ahead of time whether any of these will cross the threshold into "reasonable food" territory. If they do, I think it ought to be regarded with a degree of suspicion. I suspect a possible thing which can happen is that I'll drink enough of these to get used to it and brainwash myself into thinking that they're actually worthy replacements for a nice meal, so I think an important additional variable to keep track of is /when/ I drink each individual flavor. 

*** Banana White RTD (5/9/23) 7/10

Originally planned to drink these mostly on the weekends, but the box arrived at my apartment and my curiosity got the best of me. Honestly, I've certainly had worse energy drinks. It tastes a little synthetic, kind of like a banana that was made in a lab where they couldn't quite get it right. Taste wise it wasn't so bad, but it wasn't terribly filling for 400 calories.

*** Chocolate White RTD (5/10/23) 8/10

I think this tastes a bit less like "food" compared to banana. It tastes, in my opinion, a bit better than Banana, and the texture is slightly more tolerable in chocolate form. The general lack of sweetness in these beverages I think works well with chocolate, which works fairly well even a bit bitter. Overall better than expected! 


