#+TITLE: Not a Mage
* Not a Mage

** I

Sixty years ago, the genesis meteor fell upon the earth. It was not a huge meteor or anything, so nobody got hurt right away when it fell. But soon after it fell, they determined that it had been carrying lots of these microscopic creatures on them, which subsequently released into the air like spores. It was like a sick joke: all those years spent searching for extraterrestrial life, and one day a big rock smashed into us to establish first contact. 

People were really worried about these creatures at first. It became immediately clear that these organisms were highly invasive, and they spread to every continent within days of the initial meteor impact. They were resilient, primarily airborne, and would occasionally kick up giant “dust storms” in certain climates. But the wave of initial panic wore off, and the organisms were deemed unthreatening to human civilization. People began to treat them like a new, mundane type of pollen which now happened to exist everywhere. 

Ten years later, a young girl from Maine fell gravely ill and was checked into a local hospital. She presented with what seemed a lot like routine pneumonia symptoms, but partway through treatment she began vomiting flames. Nobody really understood what was happening, obviously. She reported difficulty breathing, intense nausea, and then would “dump it all out” by “getting all the fire out of her lungs.” Strangest of all, she seemed completely unharmed by this; she was never burned by her own flames, even when they lit nearby flammable objects on fire. It was like a regular flame but somehow /alive/, able to choose its targets.

This young girl was the first recorded mage. It was eventually determined that the microbes, now with ubiquitous presence in the air at all times, had evolved some special mechanism to bind with each other inside human lungs. Once pulled together, they could do various things once re-exposed to the outside air: create fire, lift things off the ground, and so on. It didn’t take long after that for people to start calling the microbes /magic/.

War broke out soon after, short but ugly. Various governments and corporations began intensely researching magic, and it was quickly determined that certain people had innate “affinity” to magic manipulation. These people were quickly scouted, turned into weapons of war, and deployed upon each other en masse. More sophisticated techniques for manipulating magic were developed in a short time, and lots of people died in the resulting power struggle.

My quiet, remote hometown was one of the safe haven enclaves, established during the war by people fleeing the devastation brought upon by magic users. It became an annual tradition to test everyone in the town for affinity, and to expel anyone from the town who demonstrated any ability to use magic. At first many were expelled, young kids separated from their families, mothers taken from their children, all in service of preventing magic from ravaging the town. But affinity was mostly genetic, so after a couple generations the project was considered a huge success: nobody had been expelled for over fifteen years. The expulsion ceremony had evolved into a harmless little cultural event. Most people just called it the expulsion festival now. 

** II

The candle on my desk flickered with flame. It was dancing around, brimming with enthusiasm, mocking me. I pinched the candle's wick to put out the flame. Once I took my hand away, it sprung alight all over again.

No, no no no no no.

Focus. Focus. The first mage had pneumonia symptoms, right. This must have something to do with breathing. There’s probably some weird edge case where this could happen to anybody. Breathe. It feels grainy. The air feels warm. I can try holding my breath, as a test.

I put out the candle. This time, the flame stayed out. Problem solved. I just have to stop breathing. I exhaled and the light flickered back on. At the very least now I have isolated the source of the problem. I am not a mage. This is not affinity. There’s just something wrong with how I’m breathing.

The air feels grainy. I have to focus on that. The exhale feels grainy just like the inhale. What if I try to change the way I exhale? What if there was some way to exhale cleanly without the grainy sensation? 

I tried a few different ways before it eventually clicked. Inhale as normal. Exhale from the nose, then the chest, then the diaphragm, all in a single outbreath. The grainy texture emerges when exhaling out-of-sequence from this, but in this specific order the breath comes out perfectly clean. Inhale grainy, exhale clean. I put the candle out. Inhale grainy, exhale clean. The candle stayed out. A wave of relief washed over me. I’m not a mage. I’m not a mage. I fixed it. It’s all better now.

My throat and chest started to feel scratchy. I didn’t care at all. If it meant I wasn’t a mage I could just stay like this forever. Clean exhales only. I could control it. There’s no way I could be a mage. I could feel the insides of my mouth start tingling. This is just how everybody feels all the time. The stomach churning is normal. The chest pressure is normal. The sensation of panic is normal. Given enough time I could imagine it fading into the background along with everything else.

I turned away from my desk and retched. A string of flame erupted directly from my mouth. I felt so much better. The candle on my desk flickered alight. 

This cannot be happening to me. I can’t be a mage. My whole town hates mages. I never wanted to be a mage. If they think I’m a mage they’ll banish me from the town. Maybe they’ll kill me. Maybe I’ll die even if they don’t. I have to hide it. I can get better at hiding this. People won’t understand the difference between whatever is wrong with me and being a real mage. 

I’ve always thought that my ultimate dream in life was to grow up and be a regular person. I would do just fine in school, get a reasonable enough job in my hometown, and live peacefully with a family. This tiny candle on my desk was burning it all down. My future. My relationships. Everything I ever wanted for myself. All of it going up in this tiny, harmless flame.

I tried to run through the names of everybody I knew, anyone that could help me with this, anybody I could even talk to about it. But it all came up completely blank. My family. My friends. Everybody around me. It’s critical that I don’t ever talk with anyone about this. Magic is evil. I can’t be evil. Nobody is going to be receptive to the idea that I might be evil. Nobody is going to tolerate my fear that something about me is evil.

The candle burned, bold and unflinching. /You are a mage/, it was saying. /You better pack your things/.
