#+TITLE: Lose 100 Games

* Lose As Much As Possible

There's a commonly referenced "law" called [[https://en.wikipedia.org/wiki/Sturgeon%27s_law][Sturgeon's Law]] which says "90% of everything is crap".

There is a great temptation to see the existence of a law which says that almost everything in the world is garbage and to conclude "I need to be different, I need to never make any garbage, ever". Making something despite a base rate 9:1 odds that your thing will be garbage is [[https://planetbanatt.net/articles/coolness.html][an act of bravery]]. There is an unfortunate consequence of sturgeon's law which never gets mentioned: your thing will probably be garbage, and that is perfectly fine.

** Go Proverbs

There was a time period where I, like many anime watching competitive games guys, watched /Hikaru no Go/ and then briefly played a bunch of [[https://en.wikipedia.org/wiki/Go_(game)][Go]]. Like most of these people I did not end up sticking with it, but I did spend a lot of time /reading/ about the world of professional Go, a game with many thousands of years of history behind it[fn:3].

Given that the game was invented in China many years ago, it's somewhat unsurprising that the game has it's own little corpus of [[https://en.wikipedia.org/wiki/Chengyu][Chengyu]], commonly called set phrasees, chinese idioms, or /proverbs/. These are [[https://senseis.xmp.net/?Proverb][pithy little phrases]] that are esay to remember, and equivalents of these exist in english for [[https://en.wikipedia.org/wiki/Bruce_Pandolfini#%22Pandolfinisms%22][other board games]] as well. 

There are two proverbs which have stuck with me well past my brief fascination with Go.

*** Lose Your First 50 Games as Quickly as Possible

We live in a world of expected permanent success. Incentive structures for most children (and most adults) encourages people to adopt lifestyles where they see only the minimum possible probability of failure, with only the minimum possible stakes. Bright students are expected to succeed in all of their classes. Useful workers are expected to consistently deliver value. Failure is never an option.

Generally speaking this is all frightfully boring. It's a much better use of time to be [[https://planetbanatt.net/articles/leetcode.html][as uncomfortable as possible]], compared to only ever taking on challenges which are trivially possible for you.

This go proverb is memorable because not only does it tell you to not expect to win games, it specifically tells you that losing lots of games quickly is /a win condition/. In a lost game, there's always some distance between your performance and what you needed to cross in order to win; in a won game, there's always a temptation to say "I just need to do that, just like that, every time". It is much harder to motivate yourself to care about /winning/ a game /even harder/ than you already did[fn:1].

*** Only after the 10th punch will you see the fist

The [[https://senseis.xmp.net/?OnlyAfterThe10thPunchWillYouSeeTheFist][long form]] of this concludes "and only after the 20th will you block it". This is kind of like the above point, but on the scale of individual games. Go is very interesting in the space of board games because the games are won and lost over extremely long time horizons, meaning you win by winning a great many smaller battles compared to Chess where often one decisive confrontation will end the game[fn:2]. For example, you can see strong players sometimes play [[https://senseis.xmp.net/?TeachingGame][teaching games]] with weaker players, where the intent isn't to crush the player but to instead present a number of "tests" to the student, and giving them multiple attempts to eventually arrive at a conclusion.

The takeaway from this proverb is that it will often take you a lot of exposure to even become aware of common patterns that repeatedly foil you, to say nothing of patterns you are seeing for the first time. Even on a local move-by-move level, you will repeatedly fail until you actually notice what is happening, and then you will /still/ continue to fail until you come up with a satisfactory solution to that thing you just noticed.

** 90th Percentile Crosses a Graveyard of Quitters

Simulate things

* Footnotes

[fn:3] At one point I do think I'll go back and revisit this, since I did find it to be great fun, it was just a bit too intense of a time investment relative to other things I was already working on.

[fn:2] This maybe is an oversimplification here but the idea I'm hinting at is that "a tactic" in chess will confer you material advantage that a strong player could use to win the game immediately, and "a tactic" in go will win a fractionally higher probability of victory.

[fn:1] This could even look really weird in practice -- Alphago famously deteriorated it's own advantage in the tail end of games seemingly to drive down uncertainty, since it saw equal reward for a 0.5 stone win compared to a 10 stone win. 
