#+TITLE: Learning Chinese

* Learning Mandarin

This is, for now, mostly a collection of links to resources I use to learn Mandarin.

** Hanzi

I am working through [[https://www.amazon.com/Remembering-Simplified-Hanzi-Meaning-Characters/dp/0824833236][Remembering Simplified Hanzi]] by Heisig and Richardson.

Much ink has been spilled about whether this book is useful for Chinese language learners. The "No pronounciation, no compound word, pure meaning-character mapping" approach definitely makes a lot more sense for Japanese, where Kanji can often be pronounced in all sorts of different ways (unlike in Chinese where it's unambiguously mapped to a single syllable every time).

However, I have found working through the book to be very worthwhile. I have some experience with memory techniques so the wordlist linking approach (/"imaginative memory"/) has been fairly natural for me. Likewise, I've had a lot of trouble absorbing characters in the times I've tried to learn Mandarin in the past. I would use pinyin to learn how to pronounce things, and then I would enable "show pinyin and hanzi" on whatever app I was using, and then continue to just look at the pinyin instead of the character. I tried all sorts of stuff to make relying on the pinyin more annoying, but no amount of annoyance would result in me looking at the character rather than the pinyin.

After numerous failed attempts at learning the language, this book is what made things start moving again for me. My wife will regularly make fun of me for pointing to characters I encounter in the real world and using some strange, archaic combination of words to "read" it (I encountered a drugstore in Mountain View which had 天然 on the front, which I pointed to and said "heavenly sort of thing" instead of "natural" which she thought was funny). It was a lot of effort to learn in this totally decoupled way, and felt very strange, but it did allow me to start my regular study over from scratch without using pinyin at all except alongside the answers, which made me feel like I was actually doing it properly.

I have an anki deck for these. I just grabbed the most popular one in the shared decks, and it's working great. 

** Vocabulary Core

*** HelloChinese + Anki

I made an anki deck of the words from [[https://www.hellochinese.cc/][hellochinese]], helpfully compiled [[https://docs.google.com/spreadsheets/d/1PppWybtv_ch5QMqtWlU4kAm08uFuhYK-6HGVnGeT63Y/edit?usp=sharing][here]]. I like hellochinese a lot despite some of it's more bombastic claims ("30 minutes a day, fluent in 3 months!" yeah, right). But I think the app does not do it all -- it seems designed to help you be able to recognize things in context, or to understand what people are saying, rather than really producing any output yourself. I generally recommend it (it's been well worth the money for me) but I do think some external legwork of reviewing on anki rather than their very sparse daily drills is necessary to get appropriate value from it.

*** Remembering Pronounciation

I'm working on the [[https://planetbanatt.net/articles/marilyntrainer.html][Marilyn Method]] for encoding the pronounciation of characters. This is a nifty system that lets you encode any viable syllable in Mandarin to a person+location pairing, which you can use to create a mnemonic for the way to say whatever you're reading.

This pairs nicely with the whole "don't learn the pronounciation" thing in Heisig. I think it's helpful to "flatten" everything to tuples like this. Heisig deals with (character, meaning) tuples, this anki deck + mnemonic technique is useful for (meaning, pronounciation) tuples.

Normally for learning new words / foreign languages, the default recommendation is to use the substitute word method. This is much easier for languages that are not Chinese, where substitute word will inevitably destroy all information about the tones. This is certainly more involved, but hopefully it sticks a little better. 

** Speaking

Maria is fluent in Mandarin. It helps for this. I don't have any useful advice for you here. Perhaps if you are fortunate a wife will fall out of the sky for you, also. 

** Reading

[[https://duchinese.net/][Duchinese]] is pretty good from my cursory experiences. This is helpful for practicing actual reading (i.e. not just selecting between a number of options). Pulling stuff out of this to use in a real flashcard app is annoying, but the words are in plaintext in the page source of each story, so it is usable. 

** Mining

I'm not really at this stage yet, but it's useful to get stuff compiled anticipating it. A lot of this content is aimed more directly at learning Japanese but the overall idea can obviously be adapted for any language[fn:1]. 

[[https://yomitan.wiki/][Yomitan extension]]

[[https://soyuz18.notion.site/Sentence-mining-from-Netflix-and-YouTube-with-asbplayer-83a03590cd8349ba81ca10340645b565#92ca8ce0251f4eeba89776950b8cef11][Mining from Netflix with asbplayer + anki]]

[[https://www.youtube.com/watch?v=wSexzzsJSqA][animecards youtube tutorial]]

[[https://animecards.site/][animecards.site]]

*** Using Language Models for Mining

[[https://www.youtube.com/watch?v=St_Fk0_5jgA][Vaughn Gene]] has an interesting video on his approach to language learning which has some useful reference to getting value from language models as a language learner. An interesting strategy he mentions in this video is to ask a language model for some number of sentences surrounding a certain topic[fn:2].

I think this is an interesting approach -- I often see people complain about not being able to find 20 new sentences worth of anki cards in X hours of study, and it's probably pretty efficient to just front-load some minimum level of base learning and then to not stress as much during the mining process.

Using the language model this way feels more like generating a new unit of a textbook, just about some topic very unlikely to be in a textbook. For example: imagine a short textbook unit about "going to the mahjong parlor", complete with a bunch of vocabulary about gambling or whatever. That's closer to the ideal output here, a never ending textbook of straightforward sentences in your target language.

In any case, probably unnecessary for now.

** Addendum A: Foreign Language Study Goals 

/Goals 2026-03-24/

It would probably be helpful for me to write down what the point of all of this is, so I can refer back to it.

I don't have any plans to move to China or anything, and I don't spend a lot of time consuming Chinese media which would feel extra fun for me to consume without subtitles or translation. I do, however, have family members that speak Mandarin Chinese, so being able to interact with them properly is the highest priority item.

I am also anticipating eventually having children, who will likely need to learn some Chinese in order to interact with their family. The worst case scenario for me is living in a household where everybody speaks Mandarin except for me. I often lie awake at night panicking about such a future. It absolutely must not come to pass, so I must learn to read and write at least moderately well.

It is important for me to speak and understand Spanish as well. My Spanish could certainly use some work also, but I did speak a good amount of it in childhood (maybe less than I should have, but some). There will probably come a time where I add some spanish language core deck / sentence mining practices to my daily anki routine. But this is quite a bit less interesting than learning something as difficult as Mandarin, and probably doesn't require a big writeup. In any case, certainly more of a concern once my Mandarin comes anywhere close to my Spanish. 

I don't have any interest in taking proficiency exams. If you hear me refer to somethink like HSK or whatever, just assume it's a vague reference to either a skill level or a required level for a graded reader or something. 

* Footnotes

[fn:2] Pointed out in this video is that this is not the same as having a conversation with the language model per se. 
[fn:1] If for some reason I ever want to study for the GRE or the LSAT I think I have even heard of people using sentence mining decks for their native language. 
