#+TITLE: Thoughts on Media

* Media Thoughts

This is a page where I will collect some shorthand thoughts on stuff I read / watch / consume. I'll often link to full reviews from this page, but I want something a bit centralized in comparison to the links page.

** Books

*** The Memory Book

8/10 Reread this ahead of a brief stint reading about mnemonics. I gave this a high rating as a token of appreciation for being the entry door for me into mnemonics, but the content in this book can easily be condensed into 10 pages at most, and I think online tutorials are likely better in comparison to reading this. Large amounts of this book are dedicated to fluff lists of substitute words for names which were common in the 50s, and applying basic techniques to unusual stuff. This leads to some [[https://twitter.com/Ambisinister_/status/1742674217282478481/photo/1][hilarity]], but overall it's very easy to read and not a bad introduction.

Aside: this book takes a rather inflammatory stance against memory palaces, 

*** Memory Craft by Lynne Kelly

10/10 See [[https://planetbanatt.net/articles/memorycraft.html][Book Review: Memory Craft]]. Well researched, interesting, with coherent flow of ideas from beginning to end. I teetered on giving this a 10 (it's borderline), but I think the book was too absorbing for me to feel a 9 is justified. Lots here even for those who lack the desire to learn these techniques, more of a pop anthropology book than anything else.

*** Advanced Memory Palaces by Joe Reddington

8/10 Full book review coming soon, requires project.

Some good insights in this book about the limitations of memory palaces, the relationship between memory techniques and data structures used in computer science, and experimental techniques created by importing unused concepts from data structures research.

The most practically important thing in this book is the idea that memory palaces are just arrays, and that all of them are as such just mapping arbitrary content to an ordered list (in arrays this is usually the list of integers). This alone I think makes the book worth the price of admission, and I think this largely explains away most of the historical gap between /real places/ and /ficticious places/, especially among people with aphantasia. But as a general computer person I liked most of the content in this book.

*** One Hundred Leaves

7/10 Read this annotated reader of the /Hyakunin Isshu/ since I am kicking around the idea of writing an essay on /Chihayafuru/. The poems are really beautiful, and it's a lovely collection of poems, but I must admit that the aesthetics of Japanese poetry is really lost in translation for me -- I think with my rudimentary Japanese I can handle relatively simple wordplay which pops up in anime from time to time, but actual poems are really just a completely different beast; many of these lines often have three or even four readings which completely transform the meaning of the poem, making poetry in Japanese a lot more of an intellectual exercise than it tends to be considered in English speaking countries.

I still might write this essay, which would likely involve me actually memorizing these poems for real. That part actually does not seem so bad. At the end of the day Kana was right: deeply understanding the poems is much harder, and potentially much worthier, than just remembering what they say.

*** The Art of Memory by Frances Yates

8/10 A comprehensive and fundamental work about the history of memory techniques. I am really taken aback by how much this body of training represented an occult art throughout the arc of history. This book is certainly the book to get if you're interested in the history of memory techniques, but it lacks the enthusiasm of /Memory Craft/ by comparison. Whereas that work I thought the engagement with various mnemotechnic systems was almost overly gratuitous, in contrast Frances Yates writes from a purely academic viewpoint, completely openly devoid of any interest in learning the craft for herself. As much as I appreciate the history of the art; its origins in occult and religious practice and its downstream influence upon rhetoric, psychology, theology, and history; it was too distracting to be repeatedly confront the idea that someone could have written so many words on this topic and not held even the slightest interest in trying to test it yourself. 

** Anime

*** Lycoris Recoil

6.5/10 A show which does not know what it wants to be. Tone shifts do not feel justified and the [[https://en.wikipedia.org/wiki/Great_man_theory][great man theory]] thesis of the show doesn't feel earned. A victim of tell, don't show; overall forgettable through trying to pretend it has more to say than it does.

*** Death Note

9/10 I rewatched Death Note and it's both as good and bad as I remembered it. Death Note, to me, is one of the few bits of media whose importance is actually slightly bolstered by its own flaws. You really get the sense that if the show was written by someone just a little bit smarter, that it would have been more interesting, but I actually think that is explicitly /not/ the case, even if that would have made it much /better/. Light Yagami being written as a non-genius's mental picture of a genius makes his mistakes jump out and encourages you to roll your own solutions to the already very interesting premise, and the seemingly endless capacity this show has for letting people talk about it is something any anime could benefit from learning from.

Overall I think Death Note is a badly written show with an extremely interesting premise, and it's one of those shows which hammers home the unintuitive premise that poorly-written media can be good / well-written media can be bad. This is not the case for the vast majority of cases, but Death Note is a stand out example.

** Games

*** Final Fantasy 7 (PSX)

8/10 An ambitious art project which does not have a clear vision for why it is a video game. Beautiful soundtrack and handpainted backgrounds, extremely frustrating to navigate the environment, Classic final fantasy overly high encounter rate, fairly interesting characters, and clumsy dialogue. Willing to look the other way for stuff which can be explained away by localization failure, but too much of the character development feels like one person writing two characters with the same voice.

The real star of this game is the cinematic attacks; the summons are all outrageously beautiful and I often felt sad when I had to stop using some of them after obtaining a new one. Lots to be said about the various examples but the one which will stick with me forever is Safer Sephiroth's /Supernova/ which was certainly the most incredible attack that has ever hit me while playing any video game.

A lot to be said on the game as a piece of art, but as a video game it did not really work for me -- I often felt frustrated or annoyed by what was happening on screen, and I felt that it was really more of an opera than a video game. I did not feel this about final fantasy 6, which also had a higher encounter rate: I'm chopping this up to the relative open-endedness, and also perhaps the slightly different tone. Overall I continued to get the sense playing this game that I was playing a good game, but for some reason I found myself daydreaming about the next game I would get to play after completing it.

*** Metal Gear Solid (PSX)

7/10 Impressively overrated. Feel that this game is beloved for how quirky and ridiculous all the dialogue is, which is admittedly charming at times. But it just grew to be too grating after a while, and would regularly interfere with my enjoyment of the game. Extremely confused about the biology in this game: FOXDIE is explained in a stray codec discussion in a genuinely interesting manner which feels scientifically plausible, only for the central plot focus to throw in some nonsense about "dominant genes".

The game itself is fairly pedestrian, you're always getting hit by things offscreen or invisible, it's a pain in the neck to play, and you tend to feel like you're just waiting for the next codec rather than enjoying the game. It lives in an interesting middle ground, where it seems to not understand why it is a video game until it's slamming you in the face with metacommentary on being a video game (oooo I can see your saves oooo better switch to player 2). There's things to like about Metal Gear Solid, but generally speaking I think you can just watch the cutscenes on youtube or something.
