#+TITLE: Thoughts on Media

* Media Thoughts

This is a page where I will collect some shorthand thoughts on stuff I read / watch / consume. I'll often link to full reviews from this page, but I want something a bit centralized in comparison to the links page.

** Books

*** The Memory Book

8/10 Reread this ahead of a brief stint reading about mnemonics. I gave this a high rating as a token of appreciation for being the entry door for me into mnemonics, but the content in this book can easily be condensed into 10 pages at most, and I think online tutorials are likely better in comparison to reading this. Large amounts of this book are dedicated to fluff lists of substitute words for names which were common in the 50s, and applying basic techniques to unusual stuff. This leads to some [[https://twitter.com/Ambisinister_/status/1742674217282478481/photo/1][hilarity]], but overall it's very easy to read and not a bad introduction.

Aside: this book takes a rather inflammatory stance against memory palaces, a view which I consider fairly incorrect after spending a little bit of time on it. 

*** Memory Craft by Lynne Kelly

10/10 See [[https://planetbanatt.net/articles/memorycraft.html][Book Review: Memory Craft]]. Well researched, interesting, with coherent flow of ideas from beginning to end. I teetered on giving this a 10 (it's borderline), but I think the book was too absorbing for me to feel a 9 is justified. Lots here even for those who lack the desire to learn these techniques, more of a pop anthropology book than anything else.

*** Advanced Memory Palaces by Joe Reddington

8/10 Full book review coming soon, requires project.

Some good insights in this book about the limitations of memory palaces, the relationship between memory techniques and data structures used in computer science, and experimental techniques created by importing unused concepts from data structures research.

The most practically important thing in this book is the idea that memory palaces are just arrays, and that all of them are as such just mapping arbitrary content to an ordered list (in arrays this is usually the list of integers). This alone I think makes the book worth the price of admission, and I think this largely explains away most of the historical gap between /real places/ and /ficticious places/, especially among people with aphantasia. But as a general computer person I liked most of the content in this book.

*** One Hundred Leaves

7/10 Read this annotated reader of the /Hyakunin Isshu/ since I am kicking around the idea of writing an essay on /Chihayafuru/. The poems are really beautiful, and it's a lovely collection of poems, but I must admit that the aesthetics of Japanese poetry is really lost in translation for me -- I think with my rudimentary Japanese I can handle relatively simple wordplay which pops up in anime from time to time, but actual poems are really just a completely different beast; many of these lines often have three or even four readings which completely transform the meaning of the poem, making poetry in Japanese a lot more of an intellectual exercise than it tends to be considered in English speaking countries.

I still might write this essay, which would likely involve me actually memorizing these poems for real. That part actually does not seem so bad. At the end of the day Kana was right: deeply understanding the poems is much harder, and potentially much worthier, than just remembering what they say.

*** The Art of Memory by Frances Yates

8/10 A comprehensive and fundamental work about the history of memory techniques. I am really taken aback by how much this body of training represented an occult art throughout the arc of history. This book is certainly the book to get if you're interested in the history of memory techniques, but it lacks the enthusiasm of /Memory Craft/ by comparison. Whereas that work I thought the engagement with various mnemotechnic systems was almost overly gratuitous, in contrast Frances Yates writes from a purely academic viewpoint, completely openly devoid of any interest in learning the craft for herself. As much as I appreciate the history of the art; its origins in occult and religious practice and its downstream influence upon rhetoric, psychology, theology, and history; it was too distracting to be repeatedly confront the idea that someone could have written so many words on this topic and not held even the slightest interest in trying to test it yourself. 

** Anime

*** Lycoris Recoil

6.5/10 A show which does not know what it wants to be. Tone shifts do not feel justified and the [[https://en.wikipedia.org/wiki/Great_man_theory][great man theory]] thesis of the show doesn't feel earned. A victim of tell, don't show; overall forgettable through trying to pretend it has more to say than it does.

*** Death Note

9/10 I rewatched Death Note and it's both as good and bad as I remembered it. Death Note, to me, is one of the few bits of media whose importance is actually slightly bolstered by its own flaws. You really get the sense that if the show was written by someone just a little bit smarter, that it would have been more interesting, but I actually think that is explicitly /not/ the case, even if that would have made it much /better/. Light Yagami being written as a non-genius's mental picture of a genius makes his mistakes jump out and encourages you to roll your own solutions to the already very interesting premise, and the seemingly endless capacity this show has for letting people talk about it is something any anime could benefit from learning from.

Overall I think Death Note is a badly written show with an extremely interesting premise, and it's one of those shows which hammers home the unintuitive premise that poorly-written media can be good / well-written media can be bad. This is not the case for the vast majority of cases, but Death Note is a stand out example.

*** Sousou no Frieren

9/10 Frieren is one of the first shows I've watched in quite some time where I actually /like all the characters/, in particular that their motivations and decisions all feel both meaningful and sufficiently different from each other. Many of the subtler decisions made in this story are really delightful. The show taking a definitively mage-centric perspective means that Stark's development as a character exists quietly in the background, completely incomprehensible to the audience, which makes for an absolutely amazing gag. By the end of the show we can clearly identify some parts of Fern's development as a mage, but in comparison Stark just seems roughly "unbelievably strong" from his first appearance onscreen to the very end despite training with multiple legendary heroes offscreen during the course of the first season. I like to think of this as a sneaky shorthand for Frieren's lack of understanding of warriors in general: she always seems extremely unclear about Stark's specific capabilities despite extreme trust in him ("Just fall from the sky and land, Eisen could do it so you should be okay"), and by the end of the show we are sort of just used to seeing Stark succeed for some arcane unclear reason. I think this particular example is just one very small part of the show, but points to the subtle but definitive perspective-taking which appears all over the place in the writing -- it's really well crafted. 

I've heard a lot of people disparage this show as "slow fantasy slice of life" and I can't bring myself to agree with that criticism. I think where I've landed with this is that this show illustrates a difference between /experiencing the mundane/ and /not doing anything/. Even putting aside the obvious symbolic meaning of "a journey to heaven", it really does not sit right with me trying to wave away the events of the show as "nothing happening". Compared a slice of life show, it feels like an awful lot happens! It's just that a lot of it is the cast grappling with their feelings surrounding mundane events on their journey, rather than having them just beat up some monster. These criticisms feel really antithetical to the entire thesis of the show: it feels as if they come from people who are upset that the story is not about the journey of Himmel the Hero compared to, well, what happens beyond the journey's end. Turns out we have to keep living, for better or for worse. 

** Games

*** Final Fantasy 7 (PSX)

8/10 An ambitious art project which does not have a clear vision for why it is a video game. Beautiful soundtrack and handpainted backgrounds, extremely frustrating to navigate the environment, Classic final fantasy overly high encounter rate, fairly interesting characters, and clumsy dialogue. Willing to look the other way for stuff which can be explained away by localization failure, but too much of the character development feels like one person writing two characters with the same voice.

The real star of this game is the cinematic attacks; the summons are all outrageously beautiful and I often felt sad when I had to stop using some of them after obtaining a new one. Lots to be said about the various examples but the one which will stick with me forever is Safer Sephiroth's /Supernova/ which was certainly the most incredible attack that has ever hit me while playing any video game.

A lot to be said on the game as a piece of art, but as a video game it did not really work for me -- I often felt frustrated or annoyed by what was happening on screen, and I felt that it was really more of an opera than a video game. I did not feel this about final fantasy 6, which also had a higher encounter rate: I'm chopping this up to the relative open-endedness, and also perhaps the slightly different tone. Overall I continued to get the sense playing this game that I was playing a good game, but for some reason I found myself daydreaming about the next game I would get to play after completing it.

*** Metal Gear Solid (PSX)

7/10 Impressively overrated. Feel that this game is beloved for how quirky and ridiculous all the dialogue is, which is admittedly charming at times. But it just grew to be too grating after a while, and would regularly interfere with my enjoyment of the game. Extremely confused about the biology in this game: FOXDIE is explained in a stray codec discussion in a genuinely interesting manner which feels scientifically plausible, only for the central plot focus to throw in some nonsense about "dominant genes".

The game itself is fairly pedestrian, you're always getting hit by things offscreen or invisible, it's a pain in the neck to play, and you tend to feel like you're just waiting for the next codec rather than enjoying the game. It lives in an interesting middle ground, where it seems to not understand why it is a video game until it's slamming you in the face with metacommentary on being a video game (oooo I can see your saves oooo better switch to player 2). There's things to like about Metal Gear Solid, but generally speaking I think you can just watch the cutscenes on youtube or something.

*** Suikoden (PSX)

8/10 Funny to play this so soon after FF7, as it's a game from a similar time period with almost the exact opposite problems it. Playing /Suikoden/ kept me really engaged the whole time: the encounter rate was not too annoying, you could go out into the world and collect new friends for your army, there was lots to do and keeping track of what everybody expected of you was a really compelling little simulation for what it would feel like to actually /do leadership/ where 100+ people depend on you for things. The story was overall good, and although I thought it felt like a lot of what I imagine made /Water Margin/ a masterpiece was lost in translation, that what the adaptation into a game provided in exchange was worth it.

Where this game falls apart for me (i.e. why this heaping praise is attached to an 8/10) is in how the game actually functions. In terms of how the game was actually built, it's almost astoundingly poor for something this good. The sound design is absolutely atrocious, nearly every sound effect feels like a powerpoint clipart sound. Very early on you jump on a dragon, and the dragon's roar is a generic elephant trumpet noise. How is the dragon even producing that noise? It's all completely immersion breaking. The game is rife with menuing, making sure specific armor gets shuffled around to the right party member means you spend an inordinate amount of time counting beans compared to beating things up. In /Final Fantasy 7/, armor and weapons were specific to the party member. I remember thinking this was really annoying, but I've changed my mind after playing /Suikoden/, where a new piece of armor means you hand-me-down chain your best armor down to the 6th best armor, and then delete one item. Even this by itself wouldn't be so bad, but it's compounded by the fact that there's individual inventories for each character, which means you have to shuffle items between inventories before you even get to equip things (and that armor takes up valuable inventory spots).

Really interesting game overall, and in spite of it's flaws kept me engaged the full 15 or so hours I spent on it. 

*** Suikoden II (PSX)

10/10 /Suikoden II/ is /Suikoden/ with almost everything bad fixed and almost everything else improved. I knew this would be at least an easy 9 within the first ten minutes of playing it, just from the improvements made to menuing, audio, and running around on the map; all immediately and obviously fixed. What truly sets this apart from the first game is that, unlike what some might say about /Suikoden/, it's ultimately just another game about saving the world. You are a righteous rebel, and you have to overthrow a tyrannical corrupt government led by a terrible witch. In contrast, /Suikoden II/ is a game about political intrigue. The characters constantly doubt if what they are doing is "the right thing", and that's not just coming-of-age window dressing or manifestations of self-doubt, it's about actual consequences of actual actions, difficult and sometimes harmful tradeoffs necessary for leading people through hardship. You're not saving the world. That's what makes it great.

I think this is a low 10 -- it's no /Chrono Trigger/ -- but to give it any other rating would undervalue what a contribution this game was to the genre. The leadership themes are turned up to 11 from the first game, with the political struggle feeling much larger than any one character in the story. Luca Blight is a noteworthy example of the story abruptly maturing partway through the story. There's a cartoonishly evil guy in charge of the big bad opposing nation, and once you kill him everybody just assumes that the war is going to be over (as it did in the first game): the great evil has been vanquished. This awful guy is replaced with your best friend, and, surprise, the war doesn't end. Now you have to grapple with the fact that Highland is not run by a guy everybody in the world hates, but with a guy you spend the first act of the game growing specifically attached to. 

The decision to make the deuteragonist become King of Highland was an interesting one, serving to humanize the other side of what ultimately amounted to a futile political jostling. Jowy and Shu both have almost identical goals: namely, a single unifying nation which unites the entire region to prevent fighting. This common goal and a seeming lack of any huge ideological differences between highland and the city-state really adds a subtle note of tragedy to this whole story. It really feels like there's no need for any of the fighting at all, that if somehow both sides could become the unifying nation that everybody would be okay living in harmony. This is a pretty subtle point: this futility is not really brought to the forefront of attention, except in vain "why don't we stop fighting" dialogue options which never do anything, which is an interesting departure from the typical JRPG beating-over-the-head of whatever moral lesson is intended to be communicated. 

The game has some minor annoying flaws. The tactics segments were fun when they were not scripted in some way, which was an unfortunately large component of them. The ones which were essentially cutscenes were not so bad, but often there are units which are seemingly just invincible unless certain invisible criteria are met. It was not really clear about these hidden "win conditions" and I wasted a decent chunk of time on this. The Han fight near the end is another example of this sort of annoyance; I reached this fight at level 58 and all of my attacks dealt 0 damage even with correct rolls, which made me think I was missing some sort of hidden technique. It turned out to be that my weapon was not psharpened enough, which I didn't recognize since the game naturally suggests you should use the main hero as a healer / spellcaster type. The game is not perfect, but these are all mostly just minor details.

I could probably write more about this, but it would warrant its own writeup. For now, I consider this game the gem of the PSX library. It's either this or, like, /Tony Hawk's Pro Skater/.

*** Soul Blazer (SNES)

7/10 This game was more fun than I expected it to be -- it was the latest victim in my occasional habit of playing the first ten minutes of 30+ random emulated games until something captures my attention. It was a slightly clunky but engaging action-rpg with a relatively poor localization. It doesn't give you much to go off of to get started -- you get minimal backstory before being thrust into a dungeon virtually immediately. The music and the art are both great, and the strong points are in general pretty strong in spite of some flaws. The gameplay is fun in a mobile game sort of way (most enemies are defeated by standing in a safe spot where you can hit them and they cannot hit you, even the bosses, and the difficulty mostly comes from identifying this spot for each enemy type / for each boss. I liked it a lot more, for example, than /Secret of Mana/ which was probably overall more mechanically interesting but much more /annoying/. /Soul Blazer/ took a few things and did them fairly well, and I liked playing it.

Where this game really shines is in the meta-narrative elements, which are really satisfying. It's motivating to see all the towns get filled out as a consequence for your efforts, and it makes it feel like there's a /point/ to doing an otherwise relatively boring completionist playthrough -- there's people in the dungeon you have to save! I feel /DELTARUNE/ took some inspiration from this game, where the castle town being filled out is similarly charming. I expected to dump the game in 10 minutes (as I did for the previous 29 games of that session), but it grew on me more quickly than I anticipated. Not a bad game!

*** Shadowrun (SNES)

5/10 "Ahead of it's time" aptly describes /Shadowrun/, and it's a good example of why that is not always a good thing. The game is often lauded in all-time SNES game lists, and it makes sense that it appears there; it offers a unique fantasy-cyberpunk-noir setting, and an early example of a point-and-click isometric rpg.

The problem with Shadowrun is that it is a Super Nintendo game, meaning it is so, so unbearably ill-suited to deliver a point-and-click rpg experience. Cursor movement is awkward to the point of being maddening, the game regularly lags, the locations are not very memorable, and the game is clearly artificially padded by doing the same things over and over again. The combat is terrible, and there's an endless mountain of it. Being able to talk to any NPC about any topic is interesting, except that most NPCs only have something to say about 1 or 2 topics, and the rest is just shit you have to menu past to get to those things. I'm sure the novel this game was based on was pretty good, it had some interesting themes and I did like the setting, but the adaptation of this story to a video game was disappointing. 

*** Maire Tennis: Power Tour (GBA)

7/10 In a vacuum, this is a fun little arcadey NBA-jam type tennis game. It fits right in with the console releases of /Mario Tennis/, which I have some fond childhood attachment to, and it strikes a nice balance between the fun of real tennis and the amusing bullshit superpower power shots. Other games in this genre, in my opinion, tend to overdo it with the theatrical special attacks, the game becomes largely about setting up your specials compared to outmaneuvering your opponent, and the specials in this game were not too common and also mostly set up an advantage for you to win the point with a normal sequence. The controls are nice, it's not too long, it's pretty fun overall. Lobs are a little overpowered, and you can ace most of the CPUs if you put tons of stats into serve power. 

I have to say it though -- it is genuinely /so, so weird/ that Mario is in this game. You play through almost the entire game as a generic looking RPG character, and it's a generic "tennis rpg" type setting with minigames and tennis matches instead of combat, and it's pretty cute. Then in the final act of the game you get to /meet Mario/, who is like, a celebrity tennis player, or something. He talks like Mario, you know, he only says "let's a-go" and shit. Then you play like, a whole bonus act where you get to go to "Mario World" (not like, "the Mushroom Kingdom") and play against Bowser and stuff. It feels really tacked on and I assumed it was sort of like a Star Fox Adventures sort of deal where it was just an entirely different game until very late in development. But it wasn't even the [[https://www.youtube.com/watch?v=O1j3pcY7GlQ][first of these weird Mario Tennis games]]! There was a Gameboy Color game which was sort of the same thing, where you just play as like a random guy, and you play other random guys until Mario appears at the end. This older game doesn't have it's own wikipedia page, it's just [[https://en.wikipedia.org/wiki/Mario_Tennis#Handheld_version][tacked onto the N64 game]].

I love that this game exists. What a bizarre little game. 

