#+TITLE: Gaming Milestones

* Gaming Milestones

This is a page where I can put down some milestones for achievements I've made learning games.

** Melee

This is my main game.

My best result is [[https://start.gg/tournament/genesis-8/events/melee-singles/set/46437737][49th out of 1552]] at Genesis 8. My single best win is probably [[https://www.youtube.com/watch?v=kQByD2mPWnA][Ben]] in TMT ladder, or maybe [[https://quarterlyrapport.challonge.com/qr2ssbm][Beerman]] in 2016 (seems hard to evaluate now).

** ITG

*** Stamina

For ITG Stamina, I am a (194 | 16) player.

My first 16 was [[https://www.youtube.com/watch?v=Kt-KD-Oc7Co][[16] ITC Jams Vol 4]].

*** Tech

My best result for ITG Tech was ITL 2024, where I ended the tournament with [[https://itl2024.groovestats.com/entrant/116][305k Ranking Points]] which was good for 349th place out of roughly 1400 entrants.

I also played some doubles that tournament: I got 56th place out of the maybe 275ish people who submitted doubles scores. A highlight here was getting [[https://x.com/Ambisinister_/status/1792712314841637154][my first ITG Doubles 12]].

** MTG

September 2025 - [[https://x.com/Ambisinister_/status/1969178567960305859][Standard Mythic Rank]]

** Sound Voltex

I picked up some Sound Voltex since we have an offline cabinet at work.

VF ~12.01, I hit [[https://bsky.app/profile/ambisinister.planetbanatt.net/post/3lu2brzskpc2r][Dandelion]] on the offline cab. I mostly play 14-15s. 

** Speedruns

*** Nintendo World Championships

I played this for a short time. Some highlights:

- [[https://x.com/Ambisinister_/status/1825603761974423895][World Rank 80 on Competition #5]]
- [[https://x.com/Ambisinister_/status/1831541694879449196][S rank Legendary Trial]]

