#+TITLE: Notetaking

* A Notetaking Baseline for Academic Work

People online have various ideas on what devices and techniques constitute good notetaking. I am someone who reads and takes notes a fairly substantial amount every day, and whose livelihood is largely contingent on that process being fairly effective. However, none of these systems ever really stuck with me. It has been my experience that the only determining factor that really matters is whether I was paying attention while I was reading, and whether I regularly think about what I read after I read it. This is potentially troublesome to people attempting to sell you effective notetaking strategies.

What follows is my attempt at organizing notetaking into a system that (hopefully) has the following properties:

1. enables me to learn topics really, really well.
2. doesn't require a very tedious, unneeded components which discourage me from doing it
3. /unifies/ my /knowledge management/ -- largely invisibly connects things together for me
4. lets me evaluate if the newest shiny bauble is useful or would damage my process

** Remark: AI Cannot Learn For You

Many people have taken swings at incorporating LLMs into the notetaking process and for the most part all of these attempts have been pretty bad. The reason for this is very simple, and nicely illustrates the entire point of this post. Learning something new involves two fundamental steps: *exposure* and *encoding*, and any software-enabled notetaking system must absolutely, never, ever touch either of these two things. We are going to try to design a system which uses technology to help us learn, understand, and remember; but we need first to establish some baselines for what's kosher and what's harmful.

*** Exposure

The way to learn new things is to read. You /have/ to read. There are some things which loosely "count" as reading, like paying attention to lectures/videos, being tutored by someone, etc. But for the most part, there's rarely anything better than being exposed to an extremely dense block of information, organized with the intent to build understanding. If you do anything even vaguely academic for work, you should be reading pretty much all the time. 

Consider the common naive idea of using chatGPT to create flashcards from a textbook chapter you have read. On the surface this seems like a really great idea: we can even use cloze cards to directly rip out sentences and mask important key words to reduce the likelihood of llm hallucination. However, the big problem with this is that the language model does not actually have access to your internal body of knowledge, and cannot create cards that are the appropriate difficulty for you. For example, I recently read the [[https://arxiv.org/abs/2405.15793][SWE-Agent]] paper and tried to run this as an experiment[fn:3]. Example cards that this generated for me are below

#+BEGIN_QUOTE
{{c1::SWE-agent}} is an autonomous system that uses a {{c2::language model}} to interact with a computer to solve {{c3::software engineering tasks}}.

{{c1::SWE-agent}} uses an {{c2::ACI}} that enables an {{c3::LM}} to act as a {{c4::software engineering agent}}.
#+END_QUOTE

Which are, you know, fine. If I didn't already have some background in LLMs then maybe I could use some flashcards to tell me that SWE-agent is an LLM agent for software engineering. But this illustrates part of the problem: the things I want to remember in this paper are very specifically what its contents are compared to other papers, and what new concepts are introduced in this paper that I do not already know. In order to obtain this information *I need to read the paper* and then subsequently *I need to identify things I do not already know*.

The LLM cannot see inside my brain. If it did, it could read the paper for me and pull out specifically the concepts which I need to make flashcards for, and then make those for me. But here in actual current reality there is a necessary exposure to the concepts which I need to actually do myself. 

*** Encoding

Longtime readers know I have a passing interest in [[https://planetbanatt.net/articles/memory.html][memory sports]]. It was through a brief stint in memory sports where I really learned that /seeing something/ and /putting something in my memory/ are two separate processes, and the second one is a deliberate and active process.

The LLM flashcards app idea falls short in this second way, as well. People commonly tell you when using [[https://planetbanatt.net/articles/anki.html][flashcard systems]] that you're usually better off making your own cards, and this is a big part of why: making the card is a step where you are /actively putting/ this information into your memory. Letting a machine handle this step will rob you of a critical step in the process, which I have found usually defers this step to the first time you see the card[fn:1].

** Physically Taking the Notes

paper vs computer
https://journals.sagepub.com/doi/abs/10.1177/0956797614524581 
https://journals.sagepub.com/doi/10.1177/0956797620965541?icid=int.sj-abstract.similar-articles.3

I am greedy, so let's figure out a way to do everything.

*** Writing on A4 Paper

new thing I'm trying

[[https://www.amazon.com/LAMY-Color-Ballpoint-Brushed-L401/dp/B000UTKMDQ/ref=sr_1_1?crid=3VCHUTF8J2OZ2&dib=eyJ2IjoiMSJ9.AIpczuQX9COcBrJ6-rJreuf1r6d4pEUzDPyZPEqQe4aKBWUM-Vr44toBcgNSxa3_bL3hsR25APyHZOwQYI3SxPHJtVz-61nggVUu901voXpZma8HyDPRmMkz0bUQpeSf591sSv-Wwi1x2QKYqrYtK9WqVHS2KxvDIrHU6bZgmq1omT8s-KL4HkTqDxv9EnqrYOgMujXHI66vyYpNC7fKlPUcA_khkn0CeMJnO8OWmYCAM0z6erUmntWkVszJm3ZtBDF_g1Ke2BP8ityHK_QOE1jqi07L98KM1C2O0kWo1j8.nP2ou6FzJmf4t2EPbk4VQXFGXz3-rXrRNNNtY2bze6g&dib_tag=se&keywords=Lamy%2B2000%2BMultipen&qid=1718857367&s=office-products&sprefix=lamy%2B2000%2Bmultipen%2Coffice-products%2C134&sr=1-1&th=1][pen]] [[https://www.amazon.com/Lamy-logo-3-colours-multicoloured-ballpoint/dp/B002KK5YDQ/ref=cs_sr_dp_2?crid=YNUSZCI2NE00&dib=eyJ2IjoiMSJ9.ftVK5OPW-TgvQqD1g38rJeB-lwqaJYf1XjDx_twBuzBxaEa-jDcQ6kP1VsGJ6kr4PIcXpiqH7Gi6ffBIyBXyE0GDT0-RPbbD0DAJ5S3l2jHZyMznDaKWKncwnZwI9ti2GAT29grDsvSUgct8ibQz8FE_LnT85qT3KIA82eeEMNJmawt-6v6qjuTYEKX3xa5GfTsMZbbb1Tvc-DhS9bx77aKSU2GeP7nYfG-M8_dP3RI-wFDAV-jU_lMqMQ2MjaYXFs8dXvmP-Xa--OQX88W0JVjqi07L98KM1C2O0kWo1j8.8hGNvkAICkenlcqu1HpYhOngdeEprvypj4E8fdBZHdQ&dib_tag=se&keywords=lamy%2Blogo%2B3%2Bpen&qid=1718942889&sprefix=lamy%2Blogo%2B3%2Bpen%2Caps%2C144&sr=8-2&th=1][diff pen]] [[https://www.amazon.com/Stream-Prime-Ballpoint-colors-SXE3330005-24/dp/B08WX1KGKP/ref=sr_1_1?crid=2D99YYKYWIQTF&dib=eyJ2IjoiMSJ9.oA5EO4x-sCohV9uzc1HLK3C6cDtcA1hqwD-aUD76Zqz2qBkGuHATotaRekM-CEwDOwrvEaIL-SRlJOV0ldY2DS-kA2nOjHzpweUANsl2W5KQldZSLEB29BSUNjVVzEm51ArkYnTbrBwPlMeCi0wcCiqdGb2xnFv77iZqUJ8rHLyZ83u3O05VCZhmzwV0TvbmFHbi4AOCeSLjHMww2mVSCEtctIa5w-YJGa53zRaEmIkIontj8tIlGwNbopNkZIUN8xhMSrP-lviarvmyKU4MF6yCWrR3Ngap4muwju_LT4I.B0w0Wh-QHcVkUk3c-0EzWx00eWqJzx-OgS5cZNN6UFc&dib_tag=se&keywords=Uniball%2BJetstream%2BPrime&qid=1718943067&sprefix=uniball%2Bjetstream%2Bprime%2Caps%2C142&sr=8-1&th=1][less luxury pen]]
[[https://www.amazon.com/Hammermill-Paper-letter-Bright-Sheets/dp/B01MTJEHYA/ref=sr_1_2?crid=1IK57K0OJX7JN&dib=eyJ2IjoiMSJ9.BGp6pdQoiuBqqYAtiCHQxIBtE9uZQxWBbIn_2nekYn1sb3cEggE4yCM7PE4tl7MR81rvYQZ6phk7I6i6lP2wVL1tT8OAKBMOPOv12OZ_bx-t8XjOzTDyW0HYl3U--e5BGhBT_R4-4r-IIPMgLI03SNwnMB5BrcyFGQFGdlv47J_vC4eOpYQAiLQiuCIY-r0yHst-qIN8ruuPquaoJnafFhCrVr3Me7g7LDJDbT_0jaoLgbGSw4xp23sHohy9XZbsDWYCRsQAZDnzm9nCkJQUe3XiuVcvWHeJh-HqIqD8_W8.TsByK5ZCYAl2i09jyHOV1GSSURLNDbL-5Isbsylnx6Q&dib_tag=se&keywords=a4%2Bpaper&qid=1718857903&sprefix=a4%2Bpaper%2Caps%2C158&sr=8-2&th=1][paper]]
[[https://www.amazon.com/ProCase-Clipboard-Portfolio-Professional-Conference/dp/B0CHRTS4XM/ref=sr_1_8?crid=15CMK17DKKHA6&dib=eyJ2IjoiMSJ9.YdZKOKLGRUeW01KnygpE9AUvYbvWZyXG44eJqn9V0_wQN7O-KxLAHQ93YR732xyjnAm9vnxVg5N9Ggf6-Val2QZAOHgmYp4__t1tQQOs6-M_K_VL1ZO0UH-VdopZHc57mjMyYKktHMemkkewNAG1cGFHUfzW-VSN9JgSSvxex1IrP6xqfD6g6xcn-FQcozrjTrILKvnDT7N_CEcHwJCOiBiFjSrpkKc055EBnw_f2CE5lYYTwrYW-SxfwtmuuMpRHffvdl2IMdS9f2DSIyFNr9QZmiHsrrkdOBTU_FV4Vvw.TN9FD2__YnoXvf9_reyvVuMwiJ5vg17nJhn1qEBWX7I&dib_tag=se&keywords=folder%2Bclipboard&qid=1718857927&sprefix=folder%2Bclipboard%2Caps%2C144&sr=8-8&th=1][clipcase thing]]

**** Remark: Nice Stationary is the Mind Killer

I am a sucker for nice notebooks and stuff. I always buy them and think that I am going to spend all my time filling them with beautiful thoughts that I can go back through later and enjoy reading. This presents a problem -- I don't want to use the stationary unless my thoughts are beautiful and interesting. Notes are best taken when they are about something you are clueless about. They represent the stage of learning where you are at your dumbest possible with respect to understanding a topic, and the entire purpose of them is to destroy the lack of understanding.

"Scratch Paper" on the other hand, is perfect for notes. You just write on it, as ugly as possible, to dump your thoughts and perform some act of active encoding and compression. You should be so comfortable with this that it would seem normal enough to destroy these notes later due to being not useful anymore. Stuff should be crossed out, stuff should be wrong; it ought to be chaotic and messy as you fight through understanding something new.

What needs to be beautiful is the /synthesis/ of what you are learning with what you already know. Beautiful notes are a strange concept to me: anything sufficiently beautiful seems to lack the prerequisite struggle to warrant notes being taken on the topic in the first place.

**** Formatting Notes

***** always title at top of first page

***** Box -> anki flashcard

***** always tl;dr at the bottom of the last page

*** Typing

org-mode is really useful for people who produce lots of words

*** Yapping

Blogposts in my experience are really good.

** Pipelining

Where LLMs /can/ be useful for a notetaking system is /connecting components together/. 

*** Digitizing Written Notes with Multimodal LLMs

The reason I took such care to include the anki and tldr stuff is because we are going to pipe this into an LLM to turn it to text.

Specifically, we input a bundle of all the pictures in order, and we ask it to do five things:

1. In notes file, we add a new header with the title at the top of the first page[fn:2]
2. Under that header, we add the tl;dr from the bottom of the last page
3. Under that tldr, we add a csv block with our anki cards (and send that to anki)
4. Digitize the notes to be like I drew them on a computer
5. OCR the notes into a txt file for searching purposes

** Comparison to "Study Devices"

The above represents a minimum bar for me to consider using a tool which claims to want to insert itself into my process of study. e-ink devices, for example, often have clunky notetaking capabilities that claim to hold everything together for you in a way that makes it valuable somehow.

* Footnotes

[fn:3] Prompt:

Attached is a pdf I am reading. I would like you to help me make flashcards to study for a test.

I would like the following:

1. Create an outline of the pdf provided which captures all of the major details. This should be in bullet-point format, and should allow me to skim through it and immediately remember the general contents of the pdf (e.g. for a research paper, do not say intro, related work, experiments, results, discussion, conclusion, etc; instead each section should be like "Experiment: adding l2 regularization to loss function" etc).
2. For each of these sections, pull out a subset of sentences which represent a detailed overview of that section. This should contain each "atomic" unit of information, as defined by Pitor Wozniak's 20 rules of knowledge formulation. Basically: each of these sentences should contain all of the "new facts" contained in that section, which I am unlikely to already know.
3. Make anki cloze deletion cards from these sentences. Do this by wrapping specific important words or phrases in curly braces. For example, for the sentence "The capital of Burkina Faso is Ouagadougou" can be turned into two cards like so: "The capital of {{c1::Burkina Faso}} is {{c2::Ouagadougou}}" where c1 will obscure Burkina Faso and c2 will obscure Ouagadougou.

Please note that I am specifically interested in being assisted with the rote memory component of studying for this test. I have faith that I could answer how/why/conceptual questions on this topic, but that isn't well suited for flashcards which are specifically just drilling my rote memorization. As such, try to avoid "conceptual cards" which are easy to guess or intuit by understanding -- each cloze deletion should be a concept that I should get wrong with maximum probability if I did not memorize the topic in sufficiently high resolution. 

Aim to let me recall the technical and historical details of this pdf with roughly perfect precision.

[fn:2] Also put the date here

[fn:1] I have written some scripts which will use llms to make cloze cards based on my clipboard contents if I press a hotkey, and I've found that I'll often want to go in and edit new cards the first time I see them anyways, which sort of defeats the purpose. 
