#+TITLE: The Parable of the Monster
* The Parable of the Monster

There once was a monster. It lived in the mountains, and every winter it would descend into the village to eat the townspeople. It would eat, and eat, until its belly was full, and then it would go back to the mountains to wait for the next winter.

The townspeople did not like the monster. They led peaceful lives in the village throughout the year. They would dance, and play, and they loved each other. But every year, without fail, the monster would come one winter day.

It was hard for the other villages to understand. "Our village does not have a monster problem," they would say. "Surely, you must be antagonizing the monster." But they did not. The townspeople did not like the monster, but it was rare for the townspeople to talk about it. It was, after all, an unhappy topic, full of memories of loved ones long since digested. "Why do you stay in the village?" they would ask. "You could simply move to another village, and then you would not be eaten by the monster." But the townspeople were born in the village; they loved the village and all its people, and there were enough of them where it was unlikely that they would be the ones to be eaten, when winter came. They believed the monster should move, and not themselves.

There were many attempts made, over the years, for the village to defend itself from the monster. Many walls constructed, many sacrifices made, many rituals carried out. A few times, they confused the monster, and that brought the village great joy. But most times, the monster simply ignored the townspeople, and ate them anyways. It is very hard, after all, to know what a monster is thinking.

There was a clever man in the village, who thought he could control the monster. One winter, after the monster had devoured its fill, the clever man followed the monster back into the mountains. He climbed, and climbed, growing tired, and frostbitten by the snow. At last he arrived at the monster's lair, where it lie sleeping. The clever man stood tall, and shouted:

"O, great being, king of the mountains, terror of the village. I humbly present myself before you, a simple representative of the village you so often visit. I beg of you, lend me your ear!"

The monster awoke from its drowsy slumber and looked at the clever man, wordlessly. Its belly was full, and it had no appetite for eating the clever man. But it was the first time one had come to visit it, in its lair. It was interesting to the monster. It continued to examine the clever man.

"O, great one, I offer a bargain which I hope satisfies your beastly desires. We townspeople are tired of being eaten, but we recognize that your hunger pays our desires no mind. So, we will prepare a bountiful harvest next winter, of as much livestock as you can eat. You can eat your fill, and we will not resist. I merely ask for two things -- first, that you do not eat the townspeople; and second, that you provide me with some proof of our meeting here today, such that I can show the other townspeople as a marker of your generosity."

The monster looked and looked at this unusual townsperson. Many townspeople would speak to the monster, before it ate them, but none had ever made a long journey just to do so. After the clever man had finished speaking, the monster turned its head towards a pile of glittering scales, shed from the monster's forever-growing body. The clever man followed its gaze, and nodded. He went to the pile of scales, and took one - a large, shimmering scale, one unmistakably from the monster. With the scale in hand, the clever man left the monster, and began the long journey home.

---

The clever man wasted no time after returning to the village. He triumphantly rose the scale in his hands, and shouted "behold, I have convinced the monster to stop eating us! Our village will prosper forever!" Some townspeople saw the scale and started to cry, grateful that they would not be eaten. Other townspeople were skeptical: "The monster has eaten many of us every year. Are you certain the monster is listening to you?" But the clever man was the one with the scale, and the skeptics had nothing of the sort.

The clever man took control of all the agriculture in the village. He directed the farmhands, he told them what crops to farm, what animals to raise. If they complained, he would brandish the scale, and say "I can only protect those who listen to the commands of the monster." The clever man ate like a king, from the fruits of the farmhands' labor, and the village was grateful to him - the one who would save the village from the monster once and for all.

At long last, winter came for the village, and the monster grew hungry once more. Some townspeople went into hiding, as was customary. Other townspeople went about their daily lives, convinced the times of being eaten were no more. The monster approached the village, and the clever man was there to greet it, scale raised to the sky. "O, great being, I am certain you remember our arrangement," the clever man shouted as it approached. "We have prepared livestock for you, and we hope it is to your liking. Please, enjoy our harvest for as long as you would--"

--**CRUNCH**

Oh, how the monster had been waiting for this day. The clever man's legs dangled in its mouth, lifeless and limp.
