* Range

Please see my goodreads review for a broader overview of this book.

What follows in this review is a brief overview of specific ideas in the book which I think are worth writing down -- the above can be viewed as the big-picture review of the book, whereas the below can be thought of as a sort of prose outline of notes for the book. I'm planning on going back and finding the papers which I have labeled as "citations", but for now I'll just leave them as they are here.

** Introduction: Roger vs. Tiger

The book begins with a comparison between Roger Federer and Tiger Woods. Both world champions, Tiger was groomed from birth to be good at golf whereas Federer played tons of sports and eventually decided he liked tennis the best, rather late in life. Tiger represents the Gladwell "Deliberate Practice" and "10,000 hours" rules, but Roger does not, and there's contentious reserch about a "sampling period" being useful for up-and-comers during selection of a sport. Compare to the Pat Tillman foundation, which comprises accomplished military veterans amidst career switches. 

Citations
Late Specialization: The Key to Success
Making it to the Top in Team Sports: Start Later, Intensify, and Be Determined
German national team soccer study

** Chapter 1: The Cult of the Head Start

Lazlo Polgar is a frequently cited figure in the learning-skills-very-well literature, mostly because of his book /Bring Up Genius!/ where he talks about how he was able to raise all his daughters to be highly elite chess players by specializing heavily from birth. Books like /Talent is Overrated/ frequently cite this concept, but it's contentious when you try to generalize to other activities for samples greater than a single family. In particular, the Kahneman and Klein 2009 idea of *kind learning environments* and *wicked learning environments* is a critical one, corresponding to environments where pattern recognition is pretty much the entire game, versus environments where the reward signal is sparse and hard to figure out. Some of the research in AI is referenced here, and broadly speaking the more wicked an environment is the more likely it would be a hard problem for AI to defeat humans at, and vice versa. The starcraft example is often touted as reinforcement learning being able to improve at wicked problems but I still feel pretty strongly about it being IBM Watson-style superhuman biological performance rather than superior strategy or reasoning. 

Citations
Most of the canonical expertise literature is cited in this chapter: Klein's NDM, de Groot / Chase et al "chunking" studies, Treffert's work on savants

Schwartz: how to not teach people to discover rules
Connoly and Gobet career streams

** Chapter 2: How the Wicked World Was Made

The flynn effect is a byproduct of global culture getting progressively more oriented towards abstract categorical thinking, even when more crystallized intellect measures like math and reading scores don't improve at all. The idea here is "scientific spectacles" which is, to use machine learning speak, overfitting to a world which uses abstract categories, and thereby scoring higher on tests which measure abstract categorical thinking. There are some "adversarial attacks" which arise from this, like the Ebbinghaus illusion, but it does improve IQ scores (analogy mine). "No tool is omnicompetent"

** Chapter 3: When Less of the Same Is More

The figlie was famously comprised of orphans, often with disabilities, who were taught to play many instruments and were a world-class musical troupe with Vivaldi writing pieces for them to play. A brief discussion of the relatively psycho "Battle Hymn of the Tiger Mother". A lot of the literature (see: cambridge handbook on expertise and expert performance) on musical performance focuses on classical training, which is a much kinder learning environment compared to other musical disciplines based on improvisation, and the two are notably different when it comes to where the specialization period begins. Bunch of examples of musicians who started late. 

** Chapter 4: Learning, Fast and Slow

Public education frequently overfits to getting answers right by learning how to query the teacher and solve problems that will appear in front of them very soon, but don't generalize well to new problems. Higher performing countries are typically operating inside much more wicked learning environments, which allow students to generalize better and make connections which allow them to solve new problems. Critically, you learn the best when you are stressing the boundaries and actually pushing some degree of desirable difficulty (obvious analogy: lifting weights). There's some discussion on the spacing effect, which is obviously well documented (see gwerns Spaced Repetition writeup https://www.gwern.net/Spaced-repetition). Head Start programs have a notable fadeout effect where other kids catch up (Duncan and Bailey 2017). Generalization is the most important thing.

Kornell animal cognition research about memorizing lists with hints harming performance
Kornell and Metcalfe vocabulary study which demonstrated randomly guessing meaning of new words first increased retention (hypercorrection)
Kornell and Bjork's interleaving mixed-practice study, outperforms blocked practice despite doing way worse in training and feeling like they are worse at it.

** Chapter 5: Thinking Outside Experience

Kepler was able to grapple with new fields of science by making an impressive number of analogies, and analogies are extremely useful tools for helping conceptualize abstract concepts. Teams with varied specializations typically perform better at solving previously unsolved problems compared to teams comprised of many from the same specialization. In machine learning parlance, this is because /ensembles/ perform better with /decorrelated errors/ -- if all of your agents are making the same mistakes, then having 9 of them is hardly any better than having just 1 of them, but if your agents make mistakes in different spots, then the collection of their answers is likely to be more accurate then any individual one's answers. 

Citations
Duncker 1930
Gentner ambiguous sorting task
Kevin Dunbar productive labs 1990 (definitely read this later)

** Chapter 6: The Trouble with Too Much Grit

/Grit/ is often mentioned as a good thing, but jumping between fields and tasks can occasionally just be seen as optimizing ruthlessly for "Match Quality" (see: Ofer Malmud's work). If you fit better in field B than field A, then leaving field A doesn't make you stupid, it makes you smart. “The benefits to increased match quality... outweigh the greater loss in skills.” Put in a somewhat depressing way, talent probably helps, but finding the thing you're most talented at is probably a better use of your time compared to just tunnel visioning on one thing. West point cadets more likely to get big scholarships from the military are much more likely to actually just leave the military, because they can probably do better elsewhere, which is annoying for the military since they would prefer to give scholarships to potential career officers which are virtually impossible to identify.

Citations
Very famous coin flip study - Levitt 

** Chapter 7: Flirting with Your Possible Selves

Most people think they're at the endpoint of changing themselves, but they're basically never right (the End of History Illusion). This chapter is mostly anecdotes, but the gist of it is that you should feel good about flirting with the idea of redefinining yourself, because it's sometimes very hard to know how much you will like something.

Todd Rose Dark Horse Project
"Context Principle" Ogas and Rose 2007 - people are frequently different personalities depending on what situation where they are in.
Marshmallow Test

** Chapter 8: The Outsider Advantage

It's frequent that fields often need a fresh perspective on a problem everybody with appropriate expertise is too entrenched to solve (/beginner's mind/). Sometimes this is due to outsiders just being gifted (there was a paper I read once about physics students frequently making huge breakthroughs once they switch to obscure fields, and the conclusion was a very striking "gifted individuals gravitate towards fields where they will make the least impact", but I can't find it so maybe I dreamt it or something) but a lot of the time it's just that using new tools to solve an existing problem is necessary, and outside the scope of expert knowledge of that field. /InnoCentive/ is an example of this sort of thinking taken to the extreme, where most of the solvers do better the further they are from their field. /Kaggle/ is also mentioned here, but my personal opinion is that the representation is overblown -- Kaggle winners very rarely make huge meaningful breakthroughs and the leaderboard is more about hyperparameter tuning established best-models with maybe some small creative components involved. 

Anyways, central thesis of this chapter is that knowledge generated by specialists are useful fuel for generalists to connect the dots between seemingly unrelated fields.

** Chapter 9: Lateral Thinking with Withered Technology

History of Nintendo, which pivot many times from hanafuda playing cards to, ultimately, video games. I actually didn't know a lot of the history of this company, which was fun to hear about. Gunpei Yokoi was pivotal in the ultimate move towards toys and eventually games, and was the original source of Nintendo's persistent attitude about using older technology in new ways rather than trying to compete at the edge technologically ("Lateral thinking with withered technology"). Yokoi was famous for encouraging even the dumbest sounding ideas to be voiced at meetings, because random things being linked together was so important to their business model. 

Freeman Dyson wrote in 2009 about "Frogs vs Birds", which should both exist to advance science (one looks at big pictures, one looks at details in mud). Andy Ouderkirk mentions 3M's invention process was heavily dominated by polymaths or "T-shaped people" who had some expertise in one area but dabbled in lots of other stuff and leveraged other people's expertise in intelligent ways. Bunch of smaller anecdotes (comic books, comedy).

** Chapter 10: Fooled by Expertise

Hyperspecialists very rarely generalize, and make horrible predictors outside their very narrow field (and even frequently inside their own field). /Superforecasters/ is a book I've been meaning to read, but the ultimate tl;dr on it is that the best forecasters read many fields voraciously and work together like an ensemble with very decorrelated errors, sharing information and updating their beliefs. (foxes vs hedgehogs)

If you want your opinion to be closer to correct, you need to be actively looking to falsify your own beliefs as much as possible and change your mind as much as necessary.

active open-mindedness - Jonathan Baron

** Chapter 11: Learning to Drop Your Familiar Tools

The Carter Racing study is a phenomenal case study for being aware of information you have and don't have. They had examples of temperature data during the rocket booster failures, where the temperature of failures during testing failed a bunch between 53 degrees and 71 degrees and the frequency didn’t seem to increase as it got colder so people at NASA thought it would probably be ok even though it was going to be very cold that day. But if you include the data from the non-failed tests and the temperature, you realize easily that every launch under 65 degrees would always fail every single try, and that you didn’t see the relationship because you didn’t have any negative examples. Critically, if you only have positive examples, you sort of just have no information unless you are extremely in distribution.

There's a lot of anecdotes about being comfortable abandoning your familiar skillsets, but the anecdotes fall flat for me because a lot of them reek of hindsight bias. You can likely always find something small which can make you nervous enough if n=2 is a sample size of weird events enough to make you uncomfortable, so treating this challenger blowby situation as a lapse in judgement rather than a sort of weighted random guess is a little ludicrous to me. It's certainly nicer to NASA compared to just missing data in the Carter Racing version, but the claim that the decision to abandon procedure based on this hunch is just amazingly easy to say in hindsight knowing that ended up being the exact thing that went wrong. Same deal with Lesmes anecdote.

Main points are nice, but the anecdotes were weak in this chapter and there was comparatively little science in it. 

** Chapter 12: Deliberate Amateurs

Finding joy in experimentation is pretty important! "Don't end up a clone of your thesis adviser" is great advice. There's some points about base rate neglect in here which I don't think is super well represented since I think the research about that problem suggests that it's just posed in a confusing way (Tennenbaum and Goodman have a paper somewhere about reframing the problem, still with percentages, that most science people get right immediately). This was the chapter I felt the most strongly about with regards to cogsci though, like the point about most disciplines being like guilds which teach a repertoire or trade rather than solving the problems with the best possible tools.

** Conclusion: Expanding Your Range

Don't give up, frequently people with range have super flops and unfinished projects but that just makes it more nice when your good idea ends up as good as it does. 
