#+TITLE: Drawing on the Right Side of the Brain

* Book Review: Drawing on the Right Side of the Brain

This is a book of drawing exercises. I won't beat around the bush here: the majority of this book is pop psychology filler which does not hold up to modern reproduction efforts, and there are several irrelevant tangents about unrelated topice (e.g. art teachers in public education not being able to draw). As a book, it is not great, probably not a book well-suited for cognitive scientists in the current era.

But embedded in this not-so-great book are a bunch of drawing exercises with this incorrect science used to vaguely explain the use. It feels only fair to judge this book based on it's actual merit, that is, whether or not you come out the other end with the ability to draw. For acquiring skills, even poor analogies which don't reflect reality can sometimes be helpful frameworks for learning something new. Does that hold true here?
 
** How to Start Drawing

- Preinstruction Drawings: Self-Portrait, Face from Memory, Drawing of Hand
- Vase-Head Illusion
- Upside Down Drawing (1 Picasso, 2 other random drawings)
- Trace picture of hand, freehand draw that drawing right-side up
- Pure Contour Drawing (Draw looking away from object)
- Crosshair Viewfinder Modified Contour Drawing of Hand
- Viewfinder Chair Negative Space drawing
- Perspective Hallway Drawing
- Corner of Room 2-point perspective w/ sighting + viewfinder
- Corner of Room 2-point perspective w/ sighting, no viewfinder
- Sighting Drawing in 2-point perspective
- Copy Mdm Pierre Gautreau drawing
- Draw a side profile of any person
- Copy Steichen self portrait
- Crosshatching exercise
- Self portrait with lighting

** It's Just 40 Hours Away

This book gives the impression of being an abbreviated summary of a 5-day, 40-hour workshop where participants would learn to draw using exercises similar to the ones in this book. 

I have [[https://planetbanatt.net/articles/leetcode.html][written elsewhere]] about my foundational belief that learning anything requires focused effort spent on deliberate exercises. Drawing is something which for me felt somehow exempt from this process: something where the effort required to become passable at drawing is an hour-count in the thousands, a skill which I have mentally binned as having relatively [[https://en.wikipedia.org/wiki/Opportunity_cost][high opportunity cost]].

However, a lesson I keep learning is that [[https://www.reddit.com/r/HipHopImages/comments/2h2y9c/everything_in_the_world_is_exactly_the_same/][Everything in the World is Exactly the Same]]. 40 hours will not turn you professional at anything, but it's very rare for a skill to be /so hard/ that 40 hours will not turn you into /someone who does it/. In my case, I wanted to understand line art and perspective, so that I could think about image generation models in a way which would seem useful to somebody who understands line art and perspective, rather than as an artistic layperson. 

** Is "Democratizing Art" a Sham?

Proponents of AI-based image generation tools often point to a rhetorical point that tools like diffusion models "democratize art", i.e. that they allow people with no skills to create something without spending lots of time becoming good at drawing first. This turn of phrase is something I've always found doubly offensive to people in the art world: first, that it posits that their skills have become (or will become) useless and outdated; second, that it places the operation of a diffusion model on the same level, creatively, as drawing a new composition from scratch.

Both of these, I think, are trivially untrue (and, in my view, a point for artists). However, I think a lot of these tools get off on the wrong foot with artists by virtue of being created by and oriented towards users with no art skills. This has created a polarizing environment, where artists refuse to use this "deeply evil and offensive" tool, and researchers continue directing their attention towards capabilities useful for people who will actually use the tools (i.e. away from artists). People who use diffusion models /specifically/ want to use them to /avoid/ learning to draw, aiming towards a future where such a thing would be /explicitly unnecessary/.

I do not believe it needs to be this way! It seems very likely that these tools can be used /much better/ by people who have any capability to evaluate errors in drawings. Tools like controlnet, inpainting, and lora can be used to coax increasingly more precise outputs out of a diffusion model, and it's always felt to me that artist-oriented generative AI tools would be helpful in the same way digital art in general was helpful. For a variety of reasons, this is unpopular to say, and makes both the artists and diffusion model users very upset.

I felt that this was not possible to resolve, so I endeavored to become an artist myself, starting with this book. 
