#+TITLE: Deep Work Critique
* Maybe We All Just Need To Touch Some Grass: a Critique of Cal Newport's "Deep Work"

#+BEGIN_QUOTE
Draft: v0.1 | Posted: n/a | Updated: n/a | confidence of success: 75% | estimated time to completion: n/a | importance: low
#+END_QUOTE

** Intro

I spent some time recently in Shanendoah national park in Virginia, and there was a moment in my trip which in particular stuck out to me as noteworthy. I had just reached the summit of Bearfence, and I was peering out over the top of this tall, tall mountain and thinking to myself about how cool the view was. After a moment, I felt a brief flash of boredom, and instinctively reached into my pocket to look at my phone, only to feel a private sense of embarassment to find that the only thing in my pocket was my flashlight.

See, a big draw of my recent trip to Shanendoah national park was that deep inside the park there was little to no cell phone reception, which meant that my four day camping trip was effectively a four day social media unplug as well. Throughout this trip I frequently felt as if I was bonking my head against fixed-action patterns I had developed around the use of my phone, a sort of trial by fire for unlearning these patterns altogether. 



** Spoons, and Ego Depletion

** Do you love concentrating, or do you just hate technology

gell-mann amnesia

journalists using twitter 




* Footnotes

