#+TITLE: Wang Feng Memory Lecture Translation

* Intro

I encountered this lecture series on youtube after scrolling through some memory sports websites I was interested in. Specifically, there was a 7-part lecture given by Wang Feng, the once world memory champion, delivered entirely in Chinese with no subtitles. There was some frustration that no translation was provided, so I wanted to do something useful and use transcription tools to figure out what was in the lecture.

Discussion about these videos can be found in [[https://forum.artofmemory.com/t/wang-feng-memory-system/26868/43][this thread]]: 

The videos can be found here: [[https://www.youtube.com/watch?v=4cOOiJEB56I][part 1]], [[https://www.youtube.com/watch?v=p4YFpxW1j8w][part 2]], [[https://www.youtube.com/watch?v=bDzUIxixv-c][part 3]], [[https://www.youtube.com/watch?v=zxDyLCsy1Gw][part 4]], [[https://www.youtube.com/watch?v=9kXntpDDYEU][part 5]], [[https://www.youtube.com/watch?v=-JeCBndMMUc][part 6]], [[https://www.youtube.com/watch?v=bUxNwMsBcjs][part 7]].

Below is my attempt at turning this lecture into something readable in English. I used OpenAI Whisper to transcribe and then translate the lecture directly from the audio, and then used GPT-4 to format it into somewhat more readable paragraphs. There are some pretty obvious translation errors in the below, so I've added some screenshots + occasional inline commentary, as well as commentary at the end. For some of the slides, I asked my Chinese-speaking relatives 

tl;dr, this lecture is a pretty normal overview of standard fare memory techniques, and Wang Feng was just very good at using them compared to other competitors. There's not really significant alpha in this lecture, if that is what you are looking for, but if you want to introduce these topics to a chinese-speaking audience with examples more in line with their experience, it seems good.

* Lecture

** Introducing Wang Feng

This is a large-scale mental competition, the China Mental Competition. In this competition, Wang Feng, with his steady performance, has won 7 medals in the 10 major competitions. The overall ranking is tied with his master Yuan Wenkui, who became the overall runner-up in China. Last November, he participated in the World Mental Competition held in London, England. The World Mental Competition is the most influential national competition in the field of mental fitness.

In 2006, he participated in the World Mental Competition held in 30 countries around the world. He represents the world's highest level of international mental competition in mental fitness. Wang Feng, as the first participant, unexpectedly achieved excellent results, becoming the biggest black horse in the world. He is the youngest Chinese athlete in the world. He won the single world champion of the Chinese poker project and broke the world record with 1,984 numbers in an hour. Wang Feng is the fifth in the world and China's number one world mentalist. Wang Feng is the ninth in the world, and the first Chinese to enter the top 10 in the world.

Wang Feng is still working hard on mental fitness and is ready to compete in the World Mental Competition this year. In addition, Wang Feng is also a disciple of Zhaozhou, a high school student, and a world mentalist who has brought more to China. Next, let's give a round of applause to the world mentalist, Wang Feng. Thank you, everyone.

** Tao Te Ching Recall

Due to the delay in the lecture tonight, I think I need to give you an explanation. Actually, since I decided to hold this lecture, I have been struggling and struggling. After our association applied for the venue, I heard yesterday that Professor Ma Lianxiang of the School of Philosophy was going to give a lecture here. Later, the people of our association called the school committee and said that after the school committee learned about the situation, they decided to give the venue to our association. So this venue did indeed come from Guiyin. Today, I rushed over and put the computer down, but I couldn't turn it on. So I couldn't broadcast the lecture I prepared. Fortunately, there was a backup, so that I could give you a normal lecture tonight.

Since everyone has waited for me for so long, and came here to listen to my lecture, I can assure you that as long as you come here today, I will definitely let you gain something. I won't let you down. Thank you. Before I start the lecture, I guess many people are curious about my memory. So let's have a little performance first.

Today, I will be demonstrating memory techniques using Lao Tzu's 'Tao Te Ching'. We'll focus on two types of memory-related tasks. The first involves identifying specific content: you can ask me about the contents of any chapter or paragraph in the text, and I will tell you what it contains. This isn't about recalling the number of pages, but the actual content.

Alternatively, you can challenge my memory in a different way: mention any part of the text, and I will tell you exactly on which page and paragraph it appears. This will showcase my ability to recall the placement of text within the book.

As part of the demonstration, the relevant passages will be highlighted in black on the screen. You'll also see me writing down the page numbers corresponding to Lao Tzu's writings as I recall them. We have these two types of challenges prepared. If anyone has questions or would like to test my memory, please feel free to raise your hand. Let's begin.

/The rest of this segment is a back and forth between Wang Feng and the audience, most of which is inaudible. Ostensibly, he gets them correct./

** Memorizing Names and Faces

/note: there seems to be some missing transition here, but we are learning about names + faces memory now./

*Slide: a woman*

How do you feel when you see this woman? Do you like her? Yes, you do. I think when you see her, the first thing you'll say is "Wow, beautiful!" What are the characteristics of this woman? First of all, she has a smile on her face, right? And also, you may find she wears a lot of accessories, right? These are like candies. So, you can think of this woman when you see her, she has so many candies on her body, and you will laugh.

*Slide: a different woman*

Next one. How do you feel when you see this woman? Do you like her? Yes, you do. Wow, very good. You have already done the first step. She looks a bit dark, and this image... Let's see her name again. Xiao Zhang Fei. Xiao Zhang Fei. To remember her, you can remember the famous Zhang Fei. Maybe this is Zhang Fei's daughter, Xiao Zhang Fei.

Okay, let's see this one. How do you feel when you see this woman? Her face is very dark, right? This woman looks more serious. This one is more difficult than the previous one. Let's see her name again. Let's see her name again. Do you have any idea? Do you have any idea?

*Slide: a man crossing his arms*

Speaking of Jin, what do you think of this man? Qing Jin. Qing Jin. So when you think about it, the most important thing is to think of those abstract words as a specific name. For example, when you see Jin, if you want it to be specific, it must be Jin. Right? You want to visualize something related to the word 'Jin'. So, Hong, you can think of Hong. You can think of this person. You see, he is facing this way. In fact, it feels like he is standing next to a mirror. The outline outside is a square. So you can think of he is standing in front of a square red mirror to look at the mirror or to look at the mirror. He is a little serious.

/note: I believe there's some sort of wordplay here? It doesn't translate well/

*Slide: a man wearing sunglasses*

Okay, next one. Okay, next one. Come on, you can think of a name. This person has an outline. So, Guan Shi Qiang. Guan Shi, what do you think of? Guan Shi, has an outline. What? An outline of a soldier. An outline of a soldier. What do you think of? Your hair is too long, isn't it? Okay, Guan Shi, what else can you think of? Write it down. Okay, very good. Let's see. When you were a child, what did you see when you saw Guan Shi Yin? I mean, how did he look like Guan Shi Yin? I didn't expect that even Guan Shi Yin thought that his outline was very strong. Very strong, very beautiful, isn't it? So, this is Guan Shi Qiang.

Okay, now, let's go back to this person and see if you remember. Come on, put it down. You can put it down. Let me drink some water. Okay, now, let's see if we can remember what his name was tomorrow.

/Note: here they flip through the images, and the crowd murmurs seemingly following the anchors used to memorize all the names./

*Slide: Memorizing Peoples Names and Faces in Real Life*

*Large scale, multi-level information: sounds, feelings, smells/body odor, occupation, hobbies, location met, experiences*

Okay, now, when we meet a new person, we can use some characteristics of the person himself to help us. So, what are these characteristics? For example, the voice of a person can be very bright or very sweet. These are your own thoughts. Then, emotions. Look at this person. What kind of person do you think he is? Do you like him? Do you hate him? Something like this. Then, smell. What kind of perfume or other smells does he wear? Then, his hobbies, his experiences, all of these can be connected to his name. In other words, you can process his name with your thoughts. Then, when you think about it, you can connect it with your own thoughts.

The last one is that some people have a strange name. It sounds a little uncomfortable. In this case, you can ask people what the meaning of this name is. For example, if you talk about a topic, the other person will help you remember the other person's name. In general, if his name has such a meaning, he will be happy to share it with you, right? The other one is that the more you talk, the more you remember. For example, after you have finished talking to a certain person, and you are talking to the person next to you.

You can think about what he said just now. We can directly replace it with his name. For example, what did this person say? What do you think about this person? Do you like this person? You can replace it with his name. In this way, you can increase your impact. The other one is that when people hear your name, they will remember it and repeat it. They will also feel very happy. Therefore, you will have a better and more pleasant interaction in the future, right?

The fifth point is that you can make use of your meditation and review to make new memories. For example, after you have finished talking to him, you may have to start eating or doing something else in the middle. In this process, you can recall some characteristics of that person's name, that person's occupation, and so on. The last one is that you can go back to the photo and organize the video. You can write the message in the video and add it to your memory.

I want to emphasize that you will receive a lot of business cards in the future. I suggest that you organize the business cards in a special way. For example, you can organize them by occupation, age, and so on. In this way, when you encounter discrimination, you can easily find the person you want to find or help. If you take a business card and put it anywhere, when you encounter discrimination, you can easily find the person you want to find or help. You just need to pay attention to this.

/note: 'encounter discrimination' here seems to refer to needing to pick out a specific person you met./

** Using Pegs

Okay, let's move on to the next one. The next thing I want to teach you is a little bit of professionalism in memory.

*Slides:*

*01 - Tree*

First we see that the code for 1 is a tree. Why? Can you think of it? Yes, it looks like a 1, right? Could you think of it as a 0? It must be a 1, right?

*02 - Two Bells*

Two is the image of bells. Then the next one.

*03 - Tripod Stool*

Three, right? Can you think of it as anything else? 

*04 - Car with Four Wheels*

Then four. Four wheels.

*05 - Glove with 5 Fingers*

Five.

*06 - 6 Shooter Gun*

This one is a bit difficult. Is there anyone who knows it? Very good, I heard you: it's because there are 6 bullets in the gun.

*07 - Hoe (bent gardening tool)*

This one is the most popular in primary school.

*08 - Roller Blades (8 Wheels)*

Why is this one eight? Because of the wheels.

*09 - A cat (9 lives)*

Why is this 9? Oh, because cats have nine lives.

*10 - Baseball Bat + Ball (shaped like 10)*

Next. You don't have to say this. Now let's go back from 01 to 10. 01. 02. 03. 04. 05. 06. 07. 08. 09. 10. Remember it.

Have you finished reading this? This little girl was surrounded by a piece of paper. Oh, she was attracted by the paper, right? What do you think of this little girl? Do you believe that everyone here can do it? Do you believe that after I finish the class, you will know whether you can do it or not? In fact, in the process of memorizing, she must have used the code. Next, I will analyze how to use the code.

*Slide: The first 10 of the [[https://en.wikipedia.org/wiki/Thirty-Six_Stratagems][Thirty-Six Stratagems]]* 

1. 瞒天过海 to cross the sea by a trick (idiom) / to achieve one's aim by underhanded means
2. 围魏救赵 lit. to besiege 魏 and rescue 趙｜赵 (idiom) / fig. to relieve a besieged ally by attacking the home base of the besiegers
3. 借刀杀人 to lend sb a knife to kill sb / to get sb else to do one's dirty work / to attack using the strength of another (idiom)
4. 以逸待劳 to wait at one's ease for the exhausted enemy / to nurture one's strength and bide one's time (idiom)
5. 趁火打劫 lit. to loot a burning house (idiom) / fig. to take advantage of sb's misfortune
6. 声东击西 to threaten the east and strike to the west (idiom) / to create a diversion
7. 无中生有 to create something from nothing (idiom)
8. 暗渡陈仓 lit. secretly crossing the Wei River 渭河 at Chencang (idiom, refers to a stratagem used by Liu Bang 劉邦｜刘邦 in 206 BC against Xiang Yu 項羽｜项羽 of Chu) / fig. to feign one thing while doing another / to cheat under cover of a diversion
9. 隔岸观火 to watch the fires burning across the river / to delay entering the fray until all others have been exhausted by fighting amongst themselves (idiom)
10.笑里藏刀 lit. a dagger hidden in smiles (idiom); friendly manners belying hypocritical intentions / when the fox preaches, look to the geese

What you see now is from the 36 stratagems. Have you finished reading? Have you finished reading? You have finished reading, right? OK. It is still the first step. The next step is to memorize the information and carry out a forced processing. What do you think of the sea across the sky? The sea across the sky. In fact, it is easy to understand from the dictionary. The sea across the sky. How do you relate to the tree? We can think of a tree. It grows very high and very big. Yes. Then it covers the sky. What do we do under the tree? We cross the sea, right?

<...>

I have already done all of this, I have memorized the 36 stratagems. I also have 100 pictures, not just ten. The 100 pictures means I have more things to encode with. But I still use this method. That is to say, I connect the words with numbers and codes. That is to say, in Chinese, when you type a letter, I can think of what picture is connected with that number, and tell you where it is. Also, when you type a number, you can think of the code, which connects to the picture. I can memorize in both ways.

/Note: the next bit, Wang Feng descibes using [[https://artofmemory.com/blog/mnemonic-links/][the link system]] to memorize idioms by linking the characters one after the other. This does not translate well at all, but it's nothing different from normal./

Now you know the way to use these codes to memorize things. So, it is easy to learn the technique of memory. In addition, I feel sorry to say that there are not many people who master the technique of memory now. For example, I would like to promote the technique of memory. Although I have experienced many difficulties, I still insist on teaching it. I hope more people can benefit from the technique of memory.

** Chinese Major System

/Note: this part has Wang Feng generating little stories for three digit numbers by reading the numbers aloud and changing the tones around + making up names for people based on combining the words for the numbers. It's functionally very similar to the major system used by memory competitors in English, but the translation is somewhat awkward as a result. The important takeaway here is: encoding numbers as words or people, and imagining them instead of the numbers themselves./

*Slide: 5185389015966*

/Note: Wang Feng breaks this into 518, 538, 901, 59, and 66. He comes up with specific substitute words for each of these, and links them together with the story below. I cannot figure out how he arrived at these from the translations, because the api will hear him say the numbers over and over again. The important thing here is that the Chinese equivalent of the major system is easier to understand compared to for English./

Since we are talking about stories, let's start with this one. A widow named Wu (/note: Wu means 5/). Why did she say, I want to send it? Because she drank a bottle of medicine, right? We can also think of 59, because we just said there was no dog. We can think of that she said, I want to send it because there was no dog. It's very popular. But how do we connect this story? We can think of a widow named Wu. She drank a bottle of medicine because there was no dog. She said, I want to send it. After she drank the medicine, she got up and went to Wuchang train station to walk. Can you think of a widow named Wu? She is a drunkard. Can you remember?

Now let's go over the other stories again. Close your eyes and don't look at the screen. First is 518. Then... Let's go in order. First is 518. Next is 538. Then 901. Then 59. Then 66. Very good. It seems that everyone has already remembered these contents.

** Method of Loci Using The Body

Alright, I'd like everyone in the audience to stand up. Don't ask me why. After I finish speaking, you will know why I am telling you this. So what you need to do now is to follow me and write it down in your mind. First, touch your head. Everything starts from the head, so you must touch your head. Okay, it's done. Then let's pinch your ears. Hey, audience. You pinch your ears. You don't want to listen to me, do you? Okay, let's touch your eyes. Touch your eyelids. If you don't have eyelids, let's start with the upper eyelids. Okay, let's touch your nose. Let's see how high your nose is. Let's see how high your nose is. Okay, let's touch your mouth. Do you want to try wiping your mouth? If you don't want to, let's do it now. Okay, let's touch your neck. Then, stretch your arms. Okay, let's do it again. Next, I won't demonstrate. You can just do it with your legs. Remember, your whole body should be like this. Don't bend your back. Okay, let's open our big mouth. Then, let's do a knee exercise. Are you happy now? If you are happy, let's do more exercises.

Okay, good. Just now, we did a small clean-up. Now, let's think about what we did just now. Let's start from the beginning. First, touch your eyes. Touch your neck. What's under your neck? Right? Then? <...> Okay, let's do it again. Start from your feet. Feet. Knees. Thighs. Waist. Arms. Neck. Mouth. Nose. Eyes. Ears. Hair. Okay, please sit down.

The next information may be a little confusing. Please raise your hand if you can remember the order of the twelve constellations. Okay. It seems that only a few students can remember. Then, do you have a common topic with these two students or these two students with other students? You can't talk about constellations. Let's memorize the twelve constellations together. How do we do it? We just did a little exercise. Now we will use the body part to memorize them all. First, we will do the joint processing of the information in the memory.

What do you think when you see the white sheep? Sometimes I teach some students. When they talk about the sheep, they tell me about the white sheep. I say, what does the white sheep look like? So when I see the white sheep, I may think of the sheep's feet. I also think of the white, fat, curly hair. Right? What we are going to do is to connect with our head. What do you think? Good. I heard it. It is said that our hair is white and round. It looks like a sheep's hair, right? Good. Remember that our head looks like a sheep's hair. This is the white sheep constellation.

Next, we will look at the golden cow constellation. When we talk about the golden cow constellation, we may only use the word golden cow. Because the last two characters are the word constellation. What do you think of the golden cow? Right. The special feature of the golden cow is its pair of feet, right? Right. We can't see the feet. Next, we are going to use the horse's ears. How does it look like? Let me give you a little hint. The cow's feet are on both sides of the head, right? Right. You got it, right? You got it, right? We also have a pair of cow's feet. We also have a pair of cow's feet. It is the Golden Cow. In our ears, a pair of cow's feet is extended.

<...>

It's like this. The first is Pisces. The second is Aquarius. The third is Capricorn. The fourth is Sagittarius. The fifth is Aquarius. And then, and then, and then.

* My Commentary

There are some relatively simple takeaways from this lecture, since most of the lecture is covering some pretty straightforward common methods for memory.

*We can memorize names and faces by associating their names with characteristics about their face*. I am very bad at this, but my understanding is that the way memory sports people do this event is pretty much the same in the west.

*If everybody knew what their names meant, that would be an easy question to ask*. I'm reminded of people in Japan who have to explain which characters their name is written with, which has always struck me as a lot of additional information to receive about a stranger but likely makes it much easier to remember someone's name when you meet them again.

*We can link numbers together using substitute words*. This seems somewhat easier to do in Mandarin, since 0-9 are all single syllables and you can easily change just tones to get easy substitute words. That is, Ling, yi, er, san, si, wu, liu, qi, ba, and jiu make up 0-9, and because there are four tones every two numbers can yield a wider variety of possible substitute words. One example is 13 -> yi san -> 逸散 (yì sàn) meaning "to vaporize". You can make this even wider by using syllables that sound close to one number and not the others (e.g. jiu -> gou as in the lecture). I am still a beginner at this sort of thing myself, but inventing words via the major system is a bit of a pain in the neck for me, and I can see how simply just reading the numbers aloud with different tones would be straightforward and good.

*You have finished reading, right? OK. It is still the first step. The next step is to memorize the information and carry out a forced processing*. This one stuck with me, more on a broader post about my attempt at learning memory techniques later.

*The body is a location also*. The last part of this is a method of loci demonstration which uses a meditative pass through the body as a "route", which is an interesting take compared to using rooms and roads and stuff. Otherwise, it's pretty similar. We define a path through the body, and we "place" images in parts of the body via exaggerated replacement.

*The techniques are pretty much the same*. There's not really anything in this lecture which is abnormal for the modern memory competitor. I hear that Wang Feng reached sub-2:00 speed cards after practicing from zero for 20 days, at roughly 6-7 hours per day, so like most things like this it seems like you just get better by practicing a lot. 
