#+TITLE: Medium Choice

* Selecting Medium for Media

All mediums of media have tradeoffs. When I evaluate media, I often express frustration or praise for media which "understands why it is [a video game / an anime / etc]".

Media which is immediately better after being adapted to a different medium (i.e. a television adaptation of a cinematic video game) are by and large /poor media/ even if they are /good stories/ -- and on the flipside, media which does not survive adaptation to other mediums (e.g. /Avatar: The Last Airbender/ as a cartoon vs a live-action film) are good examples of media which has selected the correct medium for their intended purpose. This is part of why video game movie adaptations are often extremely bad: they are an attempt to translate an interactive medium to something explicitly non-interactive. If the outcome is bad, that often counterintuitively /explicitly/ suggests that the original is good, despite frequent criticisms that poor movie adaptation means "the story sucks". 

** Meaningful Interactions

Video Games are an interactive form of multimedia. If you abstract this part away (i.e. via watching somebody else play through the game with no commentary), then video games are minimally different from other visual multimedia mediums. Many games seem specifically optimized for the experience of /being watched/ rather than /being played/, and this is almost always a net negative effect upon the final product.

To point to some concrete examples, let's refer to one of the most story-driven genres of video games: JRPGs. These games are often 30+ hours long, and often force the player to read hundreds of lines of dialogue or watch many hours of cutscenes. By itself, this is a neutral thing about the genre: it can be good or bad. But a question which is useful for evaluating the relative quality of a JRPG is "why is this a JRPG and not a [novel / movie / etc]".

Narrowing in on this particular question, a good answer to this question will almost invariably use the interactive component of the medium in a very good way. In the /pokemon/ games, this is usually about a collect-a-thon experience mixed with a relatively complicated, layered rock-paper-scissors battle system. In /Undertale/, there is an entire forgiveness theme which is explored in every fight, with different endings based on the behaviors exhibited by the player in these "lowly" interactions. In /Suikoden/, the player will attempt to gather people to join their army, involving them going around and talking to people themselves. 

But a lot of these games do not have a satisfying answer to this question. Nay, a lot of them feel like they have not thought about this question at all. Games following a linear story rail, with generic random encounters which have no real purpose other than to pad the game's length. You get the sense playing these games that the "game" is the cutscenes and the dialogue, and that all of the encounters are just "spacers" which exist to make you wait before the next part of the game.

