#+TITLE: The Dark Forest Hypothesis

* The Dark Forest Hypothesis for Works In Progress

Today, OpenAI announced [[https://openai.com/index/navier-stokes-solution/][a solution for the Navier-Stokes Millennium Prize problem]]. This has made a lot of people very angry and been widely regarded as a bad move.

In true 2026 AI fashion, this particular result carried with it a substantial degree of [[https://cims.nyu.edu/~tristanb/statement.pdf][attribution drama]], and it appears that this result was obtained by OpenAI using a super powerful internal model, burning through millions of dollars in compute in a short time to achieve it. The actors in our story have claimed or denied varying levels of foul play ranging from scooping to outright plagiarism. Somehow we have achieved the impossible: we have solved Navier-Stokes and managed to make that fact extremely annoying, sustaining reputational damage on all sides.

The development of powerful AIs -- some would even say /superintelligent/ ones -- is going to change norms about how work is performed in general. That is probably bad. 

** The Best-Case Above-Board Behaviors Are Still Bad

#+BEGIN_EXPORT html
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Some more technical points:<br><br> (a) We began working on the Millennium problems due to viral twitter rumors that Anthropic had resolved 2 Millenium problems. Our aim was to see whether our system was also capable of this impressive feat, especially given our excitement regarding…</p>&mdash; Sebastien Bubeck (@SebastienBubeck) <a href="https://x.com/SebastienBubeck/status/2097379415747342689?ref_src=twsrc%5Etfw">September 8, 2026</a></blockquote> <script async src="https://platform.x.com/widgets.js" charset="utf-8"></script>
#+END_EXPORT

There are some half-baked claims that OpenAI used Tristan Buckmaster's codex chats to steal his results, whether intentionally (by accessing his chats directly), unintentionally (by a rogue agent moving laterally through OpenAI's internal infrastructure to obtain critical information to solve an otherwise unsolvable problem), or implicitly (by Buckmaster forgetting to opt-out of his data being used for model training, and then used to improve the model). For the most part, these claims seem [[https://x.com/_sholtodouglas/status/2097218240397410733][mostly unimportant]] to me, being either unlikely, catastrophic, or both.

However, OpenAI's own story, per their own admission, is roughly the following:

1. They heard Anthropic was about to solve Navier-Stokes
2. They rushed to try to solve Navier-Stokes leveraging the approaches of the mathematicians who they believed had solved it
3. They solved Navier-Stokes and generously tried to give concurrent publication credit
4. They realized Buckmaster and Levent had not actually solved NS, which made things a bit awkward, especially since a competitor was involved

#+BEGIN_EXPORT html
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">I spent much of the weekend talking with the team who did this work. Seb--and everyone else--acted with integrity and generosity throughout.<br><br>Initially we believed the other team had also solved the problem. We wanted to collaborate and do a joint release. <br><br>When we learned that… <a href="https://t.co/XESh5oFHHE">https://t.co/XESh5oFHHE</a></p>&mdash; Sam Altman (@sama) <a href="https://x.com/sama/status/2097385167002415140?ref_src=twsrc%5Etfw">September 8, 2026</a></blockquote> <script async src="https://platform.x.com/widgets.js" charset="utf-8"></script>
#+END_EXPORT

#+BEGIN_EXPORT html
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">not at all a good read. what is happening here is that both labs would clearly like to find a human proxy to give most of the credit to. they find it more palatable and somewhat less self promotional than saying “our swarm of machines has solved the historic problem and…</p>&mdash; roon (@tszzl) <a href="https://x.com/tszzl/status/2097420747853402515?ref_src=twsrc%5Etfw">September 8, 2026</a></blockquote> <script async src="https://platform.x.com/widgets.js" charset="utf-8"></script>
#+END_EXPORT

I think taking this reading, it's fair to come away from the situation with the read that OpenAI's behavior was mostly above board. But, well, it's above board only barely. OpenAI [[https://x.com/polynoamial/status/2093460474738393511][could not solve the problem back in August]], and made a clear and deliberate effort to scoop the result [[https://x.com/polynoamial/status/2097215233119211902][within the last week]], with a number of involved people posting this sort of playful bragging to gloat about it. Buckmaster and Alpoge seem to be running with the insinuation that [[https://x.com/__alpoge__/status/2097383870773748190][their in-progress results were trained upon]], which I think is A: unlikely to be true enough to move the needle on actually solving it, and B: not the part of this drama that I'm directly interested in unpacking.

The whole situation is an interesting microcosm of the AI race in general. Both labs seem to be [[https://x.com/_sholtodouglas/status/2097224624274911368][wistfully wishing]] that [[https://x.com/polynoamial/status/2097225279366414541][they could coordinate]], but ultimately they are enemies with unassailable cultural norms, and a good result for one team is considered bad for the other. People emerge from the woodwork to point out [[https://x.com/dheeraj_nagaraj/status/2097266146445774924][the people involved were rude to them in the past]], people weigh in about [[https://x.com/quantian1/status/2097477759958130712][the reputations of the people involved]], people seem more interested in the drama than in the amazing technical results, and everything eventually explodes.

#+BEGIN_EXPORT html
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">wow so much drama about navier stokes. had no idea things could blow up so infinitely in such a finite time.</p>&mdash; Slater Stich (@slaterstich) <a href="https://x.com/slaterstich/status/2097219795724939436?ref_src=twsrc%5Etfw">September 8, 2026</a></blockquote> <script async src="https://platform.x.com/widgets.js" charset="utf-8"></script>
#+END_EXPORT

** The Dark Forest Hypothesis

The [[https://en.wikipedia.org/wiki/Dark_forest_hypothesis][dark forest hypothesis]] posits that the universe is teeming with intelligent life, but most of that life is attempting to evade detection in order to avoid being summarily destroyed by a more technically advanced civilization. 

We may soon live in a future where well-resourced groups equipped with superintelligent AI and near-endless compute budgets can make nearly anything happen near-instantaneously. Assuming OpenAI's account is true, they cut in front of two well-resourced mathematicians working on a year-long-plus effort in a single week, [[https://x.com/polynoamial/status/2097375837670785447][burning through tens of millions of dollars]]. In such a future you can only do two things: you can do a preemptive strike, or you can evade detection.

Even in a world where Buckmaster et al had a fully-formed NS solution, OpenAI chased after them, sparing no expense, in hopes that they could attach their names to that result. If they made any error, it's that they allowed a rumor to spread that they were close to solving it, and in doing so directed the Alien Death Laser at their work-in-progress. I am reminded of a particularly antisocial social media phenomenon, where people will take an artist's work-in-progress drawing or sketch, "finish it" with image-to-image models, and post the result as their own. This isn't against the law per se, but it does kind of suck, and the takeaway is that you probably shouldn't post WIP drawings if this would bother you.

So too it will soon be with all work that can be performed on a computer. Indeed, OpenAI's behavior probably can be read as extra prosocial from the perspective of Those Who Wield The Alien Death Laser. They could have probably just posted their own solution first, and thems the breaks. We should probably be prepared for that future, if such capabilities ever become so widespread that any antisocial NEET can scoop any WIP work just as easily as handing a sketch to a diffusion model.
