#+TITLE: Marty Supreme Review

* Marty Supreme Review

I watched Marty supreme on the plane on the way to visit my in-laws. Overall, as you would expect from Safdie, the entire movie felt sickeningly uncomfortable from start to finish. 

I think it compares favorably to prior works like Uncut Gems, since it’s helpfully told from the completely delusional perspective of Marty rather than from the slightly more detached perspective of the people around him. The film ends with Marty getting what feels like a happy ending, like a big meaningful victory. But really, the film’s ending isn’t happy at all. He can’t win the championship. Nothing works out. He has to get home empty handed, and he probably ends up in prison shortly after (or worse, working back at the shoe shop).

But if you’re Marty you’ve never cared about the outside world at all. You have the biggest dream possible, right now, and you will continue having it totally consume you right up until the moment it stops being possible. It will consume everything until you have to give up, and then it feels narratively like it was never a big conviction you had at all. Doing a table tennis act for the globetrotters is beneath you until it isn’t. There’s no way you’ll do the exhibition, until you do. The whole film is about getting to play in the championship until it isn’t. We end up downgrading our dream all the way down to winning a best-of-one exhibition match against someone we lost to at a previous tournament, and then we go home to settle down with our manipulative ex-girlfriend. Emotional orchestral swells, and then the film cuts to credits triumphantly.

On the surface this film is about sacrificing things to achieve your dreams, but what the film is really about is giving up on them without even realizing we did so. Marty never reconnects with his friend after the taxi incident, Marty never wins the championship, the orange balls end up strewn across the streets of New York. Everything was a complete waste of time, and we accomplished almost nothing of value. But we end the film on what feels like a nice win, a glorious win. It’s a win that at the start of the film would have been almost insultingly paltry.

As usual with these sorts of films, I think it’s probably really easy to ignore all of this and think something shaped like “Marty wants to escape a mundane life, so he sacrifices everything in order for his big chance at glory, and in the end he achieves his dream.” But what “his dream” actually is shifts around the entire film, and it doesn’t feel focused or pointed towards anything in particular other than continuing to play table tennis well. In the end, being good at table tennis is mostly just an excuse for Marty to fuck his whole life up in exchange for nothing. 

In this way Endo is a nice Foil to Marty, because he makes the inverse decisions to Marty at almost every turn and is summarily rewarded with the achieving of all of his dreams. His victory makes him a national hero in his home country, the same way Marty brings up repeatedly in the beginning of the film. He works as a humble craftsman in the same way Marty refuses to work at a mundane job. He doesn’t have any of the bluster or confidence that Marty displays, he doesn’t even have any lines the whole film. Endo is the one making table tennis work, winning the championship, achieving the dream. But his advantage using the unfamiliar foam paddle erodes over the course of the film just enough for Marty to win a single set, which Marty celebrates by lying on the floor in almost the same exact manner Endo did win the championship.

Marty spends most of the film preoccupied with appearing to be more rich and famous than he actually is, and completely refusing to do anything in support of his table tennis dream other than play table tennis. He has to pay off huge fines for his poor behavior and fraudulent expensing, he spends half the film seducing a washed up actress, his only ideas for making money involve his job being winning at table tennis. He is much less focused than Endo, when you think about it, and he really does not practice table tennis that much throughout the film’s runtime. By the point values of each set, it really did seem like Marty was slow figuring out how to adjust to the foam paddles. It was genuinely possible that with more practice he would have just understood what to do; he may have already been generally better than Endo to begin with. 

But that doesn’t really matter too much. The best he can manage is the exhibition set. Throughout the film he completely throws away his table tennis dream, for nothing, just like how he’s already fucking everything else in his life up. If /Challengers/ was a film about losers winning, /Marty Supreme/ is a film about winners losing.

That said, there was some stuff in this film which seemed really strange. I really don’t know what was up with the vampire line, if it was supposed to be metaphorical for the struggle against capitalism or whatever. I did briefly entertain the idea of us abruptly genre shifting into high fantasy and about Rockwell being an evil pen salesman vampire who can doom Marty to an eternity of hell on earth, but it doesn’t really do anything to the movie. Marty laughs it off as it’s obviously pretty out there, but I think we’ve already placed Marty in a position where he would gladly trade his soul entirely away for a single opportunity to finish this meaningless exhibition set anyways, so it seems like it wouldn’t add too much to the movie. “You will never be happy” brother, are we watching the same movie? Marty wasn’t gonna be happy anyways. 

Overall I thought it was a pretty good film. If you like these sorts of movies where every character is a bad person the whole runtime, it’s hard to top this.
