#+TITLE:What makes games “hard”?

* What Makes Games Hard

Multiplayer games are often flippantly labeled as easy or hard by their playerbases, which is funny if you turn the concept over in your head for a bit. The concept of a game’s inherent difficulty is really easy to understand for a single player game, where you can intuitively conceptualize the difficulty of the objectives you’re presented with. But with a multiplayer game, the obstacles are other players. In a very real sense, all multiplayer games are more or less “the same difficulty,” since all obstacles are applied to every player. 

How do we deal with this? What makes a multiplayer game “hard”? I thought it might be interesting to create a rough taxonomy of mechanisms that could make multiplayer games different difficulties from each other, to try to answer this.

** The Skill Ceiling 

A very easy one that people often jump to is measuring the skill ceiling of a particular game. If you compare a total beginner with the best player in the world, how wide is that gap? If that gap is really small, then the game is probably easy. If that gap is really large, then the game is probably hard. This is super straightforward to understand, but the most divorced from the average player’s actual playing experience, since opportunities for beginners to play elite players are usually scarce.

This axis will describe a game as more difficult if the game is very optimized and competitive, and especially if the ceiling is difficult or impossible to saturate. A game will generally grow more difficult over time as people get better at it (for example, League of Legends), but some games saturate super fast (for example, Rock Paper Scissors). Conversely, this axis will describe a game as easier if there is no robust, high level gameplay, even if other elements of the game are challenging or confusing. 

** The Skill Median

Another way multiplayer games can be hard is by instead considering the skill median, or perhaps, if you prefer, the Nth percentile where N is your threshold for respecting players of that skill level. Perhaps the skill ceiling is modestly high, but just reaching the intermediate level is a lifelong journey. If you were to drop everything and tried to learn /Street Fighter 6/, how long would it take for you to start going 2-2 at local tournaments? How long would this take for /Super Smash Bros. Melee/? This is a similar axis to the skill ceiling, but more directly conditioned on the typical player’s journey: rather than “how good can you get?” it’s more like “how good are people, generally?”

A game with a rich and already established metagame, as with the skill ceiling, can often grow to be more difficult over time along this axis. But sometimes considering this lens is a little strange. One unusual thing about this axis is that a game can become /easier/ by becoming /more popular/ — a game with a huge player pool of beginners will be easier to navigate as a beginner compared to one where the worst players still playing are multi-year veterans.

** Path-Agnostic Improvement 

A third way multiplayer games can be hard is by the relative value of effort being extremely wide. If Alice spends 1 hour playing the game normally, and Bob spends 1 hour improving in the theoretically optimal manner, how much better will Bob be after 1000 hours? Some games really punish you for wasting time on the wrong things, and other games let you improve mostly just as a straightforward function of how many hours you’ve spent on it, even if that skill curve goes extremely high.

There are many factors which contribute to how path agnostic the improvement path is. One key factor is if the game can be framed as a Kind learning environment: i.e. one where you get clear reward signals and can improve by just maintaining high exposure to the common patterns. These are things where “see X -> get Y” relationships are easy to understand, like in chess puzzles or in rhythm games: X will always produce Y, so improving at the game becomes a game of recognizing a large set of possible X.

On the flip side, some games are what is called Wicked learning environments. These are games which have sparse, probabilistic, or out-of-distribution reward structures. In these sorts of environments, instead of “see X -> get Y” you get something like “see X -> sometimes get Y, sometimes get Z.” There’s an additional layer where you have to estimate what the outcome of your action will be, and it makes the “natural exposure” improvement methods much less effective. Some games will really punish you for going down the wrong rabbit holes, and it’s extremely common for players to plateau despite intense efforts, or improve at very different rates.

Games which are popular, alive, and well-resourced will sometimes have “canonical improvement paths” which will make the game easier under this lens. These games can still be very difficult, especially if you play them naively, but a game with clear and readily available answers to questions like “should I do X” can be considered easier than a game where the responsibility lies on the player to figure that out for themselves.

** Physical and Psychological Demand

Games can of course be hard for mechanical or intellectual reasons, also. A game which requires physical athleticism (e.g. sports), dexterity (e.g. rhythm geames), emotional management (e.g. poker), memory (e.g. bridge), and so on, can be said to be difficult along this particular axis.

This one is also straightforward to understand, because this is the primary way that single player games are made to be difficult: via a difficult obstacle. Many multiplayer games require both players to navigate obstacles or challenges that contribute to the challenge, sometimes in an asymmetric way (e.g. a game with two different characters, a sport where two players have differing athleticism).

People go back and forth about how much this contributes to a game being considered difficult. People who play very physically demanding games like to point to it as a reason their game is hard (either to play or to learn), but it does smokescreen the multiplayer component of a game’s difficulty somewhat. There are many times a player in a physically demanding game will say something like “I should have won but I missed my inputs” which calls into question to what degree this is actually considered in the real-world difficulty assessments encountered in these sorts of games.

** Generalizability From Other Games

Some games are aimed at players of a specific genre, and carry with them some properties that allows players of that genre to adapt to their game very quickly. In this sense, some games are simply easier by design for certain players than others, which makes estimating the difficulty complicated. 

This is less of a direct “reason” a game can be hard, but it’s an important addendum because some games are difficult “first-genre” games but are otherwise not so difficult. Fighting games are a great example of this: adapting to a new fighting game is much, much easier than learning your very first fighting game. Are these games “hard”? Well it depends on who you are.

Games with relatively low generalizability flatten this variance between players substantially. While players who have gotten good at another game will still likely have advantages from very general game-learning structures they’ve developed, it will still be comparatively light compared to, say, someone good at Street Fighter 6 learning how to play Third Strike.

** In Which Way Are Games Hard?

Many hard multiplayer games are hard because they do one of these things to an extreme degree, rather than checking every box. Chess, for example, is difficult primarily because the top players are extremely far along an extremely brutal skill curve, despite the environment being kinder than something like Tennis or Melee. Understanding this taxonomy helps us have clear vision into *why* hard games are hard, which is useful.

To me, the hardest games are ones where the game supports very high skill, the community maintains a very high skill floor, improving at the game is highly path dependent, and the game is extremely demanding. This is, for example, why I think it makes a lot of sense to call /Super Smash Bros. Melee/ a very difficult game: it is hard in most ways multiplayer games /can/ be hard.

But the intent is not to make sweeping statements about which games are harder than which other games. Buried in this taxonomy is conditioning upon the perspective-takers particular goals with the game in question. Somebody trying to play on their small town’s Rec league baseball team is probably going to have very different ideas about how hard it is to hit a fastball compared to an MLB player, even if the context is ostensibly the same. 

Multiplayer games can be labeled easy or hard depending on a variety of design factors, which are all useful to keep in mind during these sorts of conversations. The grass is always greener: it’s easy to imagine that any effort you spent on your game would have been better spent on some other, vaguely easier game, if you only liked it better. But, unfortunately, in the end the hardest possible game is the one you can’t stomach to play at all. 
