#+TITLE: Deltarune Chapter 5 Ramblings

* Rambling About Deltarune Chapter 5

I [[https://bsky.app/profile/ambisinister.planetbanatt.net/post/3mp3xcrme4c24][expressed on bluesky]] a lot of my admiration for Toby Fox as a game developer / in general as an artist. But I wanted to talk a little bit at length about my thoughts on chapter 5.

I think people are missing something about the weird route. People are understandably drawing parallels to the undertale genocide route, which is a thing you sort of decide to do as morbid curiosity. This makes sense because the game is a deconstruction of the rpg genre, and killing monsters is a “normal” behavior that is being explicitly carved out. 

But Deltarune is not a normal RPG being deconstructed! The weird route is this thing you really have to far out of your way to do, and the narrative totally lacks any of the judgmental perspective on what you’re doing relative to the genocide route. There’s no implicit momentum towards this arc from the start of the game, compared to Undertale which expects the median player to accidentally kill Toriel and then revert the save to undo it.

The place my mind always goes when thinking about the weird route is “why would the player want to do this?” I am in general less interested in predicting specifically what will happen and more interested in figuring out why you would want to do this in the first place.

I remain unconvinced that this is just something in the game to occupy the satisfaction of the sickos who just want to see everything in the game. This was true enough for undertale, but it was pretty open about telling you that that’s what it was for. I think with the release of chapter 5 I have updated pretty heavily towards the idea that there is some goal that the weird route fulfills, that a normal player might reasonably consider worth the cost. 

Thinking back to the mantle game, the clear intent seems to be to communicate the existence of the weird route to an otherwise normal player. I guess there is a George Mallory sort of “because it’s there” aspect to this, but putting myself in the shoes of such a player, if I am being told “there is a way you can kill everybody, and yourself” my first response would be “why the heck would I want to do that?” 

So far, the reason you would want to do that is so you can torture Noelle, for some reason. This is pretty similar to the type of motivation that would bring you to perform the Genocide route in Undertale (I.e. you are a sicko) so I think up to now this has gone mostly unquestioned. But now something interesting has finally happened: we have skipped chapters 5 and 6 with this route, potentially some portion of chapter 7 also. It seems sensible to think that this is the entire point of the route, that we would /want/ to /not/ do these chapters, by any means necessary.

It’s hard to really guess what this actually means. Maybe Susie is going to die and then the weird route will sacrifice everything else in exchange for saving her. This doesn’t feel especially convincing to me (you do kill the Susie sprite in the mantle game) but it is one example of the type of thing I could imagine “worth it” in exchange for making the vibes completely terrible. 

I think I’ll be pretty disappointed if the end of the normal game turns out unambiguously positive, and the weird route ends up just being something you can do to make all the characters miserable. Probably the best twist I can envision is something that makes me think that maybe all of this yields the best outcome after all. Even maybe in a sort of irrational “let’s prevent Aerith from dying in FF7” sort of way.
