#+TITLE: Games As Ecosystems

* Games are Media Ecosystems, Not Software

** Introduction

I've seen a lot of fear and uncertainty regarding how LLMs will change the landscape for games. In particular there's a specific /type/ of fear which I think is misplaced: the idea that video game developers will be "replaced" by AIs which will make everything de novo for each individual user.

There are a lot of fields where this sort of fear has merit, but for gaming I believe it to be misplaced. Elucidating that opinion seems like it might be a good exercise for outlining how I think about games, and how I view AI's role in the industry in the near future. 

** The Arguments

LLMs and adjacent technologies continue to improve month over month, and are increasingly able to one-shot complicated problems. It's straightforward to project that this improvement will continue happening, and not-so-straightforward to determine all of the second-order effects that follow those improvements. LLMs might eat software, math, and other similar domains with verifiable modelable outcomes.

You could make the argument that they will eat the gaming industry, also. If you imagine some sort of superintelligent AI system that knows your specific preferences and can easily one-shot a complex piece of software, it's not so difficult to conclude that AIs could make entire video games tailor-made for your specific interests, perfectly to your taste, potentially for pennies on the dollar compared to development costs for video games in 2026.

The primary error in this line of thinking is mentally abstracting video games as /a piece of software/ and not as a /media ecosystem/. It's certainly possible that advanced AI systems could one-shot video games exactly as described, it is not even necessarily /wrong/ per se. But it is a category error to tie this to the death of the industry, because people do not engage with games in the same way they engage with regular software.

** Why Do People Get Good At Basketball?

Imagine that we create a super powerful AI which can invent new sports. These sports are COOLER and BETTER than all the existing sports. The AI can create a super interesting sport just for you, guaranteed to be more fun than any sport out there. Indeed, it can do this for everybody. 8.3 billion new sports created, one for each human on Earth, all way better than anything out there now.

The problem with this, of course, is that you need other people to play a sport. Someone out there is going to have to take one for the team, and play your inferior dream sport instead of their superior dream sport, just for you to play it at all. Even if your dream sport is a single-player sort of deal, like rock climbing or archery, the existence of the Other is necessary contextualization for you to understand your own journey through the sport. What things are possible for humans? What does it mean to be average, or strong?

Even totally siloed sports like powerlifting require this sort of contextualization from the Other in order to become navigable. What are good milestones for lifters? How different are athletes of different genders? What are the records for each movement? What movements are the most important? It's true that you can probably go to the gym and just randomly lift things in random ways, but that's not really how any gym-goer engages with the gym. The presence of the Other is felt, even when minimized as much as possible.

In many ways, these takes about LLMs eating the game industry do not answer the question of "why do people get good at basketball?" There are probably lots of really good answers to this question, unique to each player's personal journey through the sport. But if you squint, a whole lot of them seem roughly like "because lots of other people get good at basketball, too."

** Why Do People Read /The Hobbit/?

Imagine that we create a super powerful AI which can write new books. These books are COOLER and BETTER than all the books that have been written before. The AI can write a super interesting book just for you, guaranteed to be deeper and more profound than any book out there. Indeed, it can do this for everybody. 8.3 billion new books created, one for each human on Earth, all way better than anything out there now.

Unlike with the sport, you don't really need other people to read a book. You can just read it, and that's that. In this hypothetical world where LLMs can write beautiful, superhuman, perfectly targeted prose, it is not too big of a stretch to imagine people would prefer reading AI-generated works to human ones.

The problem is what you do after you have completed reading the book. Nobody read the book before you did, because it did not exist before you read it. Nobody knows anything about it, nothing about the characters, nothing about the themes, nothing at all. It does not exist in the shared consciousness of the outside world. Maybe you could share that book with some other people, who are now subjected to reading a book which is targeted at you, and not at them. 

In this way, the fear that personalized, AI-generated narratives will replace human writers is making a similar category error as the "superior basketball" take above. It characterizes the reason that you would read a book as "to be entertained" totally in a vacuum isolated from other people. Furthermore, it characterizes the reason you would /write/ a book as "to entertain people," and telling a story which doesn't communicate anything or have any real point to it. In reality, writers tell stories that are wrapped around their personal worldviews, and readers engage with these stories by attempting to twist their own worldviews around the events in the story. "Superhuman writing will make people stop writing" reads as "people will stop having opinions" and "Superhuman writing will make people stop reading human writing" reads as "people will stop caring about other peoples' opinions."

** All Art Is Argumentative

Games are an interactive form of art. There are many famous maxims about whether art can exist independent of its surrounding context. [[https://usabroad.unibo.it/article/view/7177/7504][W.E.B Du Bois]] made an argument in 1926 that "All art is propaganda and ever must be, despite the wailing of the purists," which was famously echoed by [[https://archive.org/details/AllArtIsPropagandaCriticalEssays/page/n9/mode/2up][George Orwell]] in an essay about Charles Dickens. In contemporary art conversations, this usually gets reworded to "all art is political," usually attributed to [[https://novacharlotte.com/2026/02/02/the-politics-of-art/][Toni Morrison]].

But this isn't necessarily ubiquitous. Briefly walking through arguments about [[https://en.wikipedia.org/wiki/Art_for_art%27s_sake][art for art's sake]], there is also the belief that quote-unquote "true art" should exist independent of all social values or surrounding context. Many people have been arguing about this for hundreds of years, and they still do today.

So I'll stop just short of saying all art is political by saying instead that all art is /argumentative/. This is a weaker and easier-to-understand claim compared to analyzing the political ramifications of every choice in a piece of art, and more neatly allows us to understand what this could mean for Video Games As Art. /Making things/ in general requires you to make decisions, all intended to communicate /something/ instead of /something else/[fn:1].

Video games are created in order to be played by other people[fn:2]. In this sense, decisions like "what genre should the game be" or "which mechanics should be built into this game" are decisions that reflect the creator's beliefs about how the Other will engage with their art. That is, they are /arguments/.

These arguments create a shared social context which is necessary for navigating the ecosystem. This is straightforward to understand for multiplayer games (which require the Other) and narrative-based games (which are preauthored, shared social contexts), but is true even for games where the experience differs from playthrough to playthrough. Rougelikes like /[[https://en.wikipedia.org/wiki/The_Binding_of_Isaac_(video_game)][The Binding of Isaac]]/, for example, are procedurally generated and different every time, but have a mechanical layer underneath which are easily identifiable as /Isaac/. This is true for sandbox games like [[https://en.wikipedia.org/wiki/Minecraft][Minecraft]], simulation games like [[https://en.wikipedia.org/wiki/Dwarf_Fortress][Dwarf Fortress]], and even emerged as a core component of how people engaged with Latitude's [[https://en.wikipedia.org/wiki/AI_Dungeon][AI Dungeon]].

Even in these sorts of games, where the intended gameplay experience is not explicitly pre-authored in any way, the space of possible gameplay is constrained by a designer who made decisions to shape the possible problems, challenges, experiences. This, in turn, gives us a way to talk about our games with other people who weren't there for them. All of this is downstream of decisions that are made by the gamedevs, which are then inflicted upon the audience.

Bespoke, single-user games lack this social context, they lack the /Isaac/. For these games to develop the necessary social context, they would need to be shared. The player would need to share the mechanism for their experience, they would need to feel a need for other people to experience a game crafted around their own preferences, wrapped around their own worldviews. That is, well, the games industry. 

** Is Superhuman AI "Useless" for Making Games?

There is a false dichotomy which emerges when engaging with this topic: that is, superintelligent AI will either completely devour the games industry, or it's useless and will do nothing at all. Both of these seem plainly unlikely to me. Obviously, there are nuances, as there always are. AI-generated personally targeted bespoke games will indeed likely be possible in the relatively near future, and it's important to engage with what sorts of things this actually will change. This list is nonzero, and I don't want the argument to be misconstrued as "LLMs will do nothing to the games industry."

There are some corners of the industry which are directly threatened by this sort of capability. Studios which make comparatively low-effort video games tied to some already existing IP, for example, are going to have a difficult time finding work: most of the heavy lifting for these products is done by the original IP they are attached to, and the value of replacement-level software which wraps around it is going to quickly evaporate. Things which are shaped like this are going to be easy for consumers to just create themselves, and the sections above mostly do not apply.

Powerful AIs are still going to be valuable and important for the development of regular games, also. Software becoming cheaper, faster, and easier to produce is going to substantially improve games, and make less technical people more capable of influencing the development process. If AI-generated superhuman writing becomes possible[fn:3], that will of course be super valuable also. I'd go so far as to say that a superintelligent AI as-is popularly imagined will substantially transform nearly every role involved with making a game exist, start-to-finish. Things like "agency" or "taste" or potentially even "imagination" are not necessarily qualities which are impossible for AIs to replicate. I don't subscribe to these beliefs that any role is totally immune from influence from these systems, especially as they grow more powerful. 

But AIs cannot play the games for you, and AIs are not your audience[fn:4]. People do not play games on islands isolated from the rest of humanity. As long as people are out there forming opinions about media ecosystems, as long as people have opinions about other people's opinions, the "games industry" will continue to exist, even if every role transforms irrecognizably. This goes for every little corner of what goes into making a game: the need for artists, the need for musicians, the need for developers, the need for designers, and so on. Even if all of these roles are "performed" by AIs in a technical sense, the end product is something intended to be experienced by a human being, with embodiment, with flesh and blood and emotions and limitations. 

* Footnotes

[fn:4] There is a particular objection that I think potentially warrants further thought, which is the idea of the Simulated Other. It's possible that in some future that AIs could be buying and playing games for themselves, that your audience as a gamedev could be AIs instead of people, and that people who want to talk about their experiences with generated content would just talk about those experiences with AI instead of with other people. I suppose this is, in principle, possible. But it feels a bit too dystopian to me: I suspect that in such a world where people prefer to not engage with each other about media, we would have larger existential problems to worry about than what is happening to the games industry. In any case, the median sentiment around AI seems very negative to me overall, so it's difficult for me to imagine a path from here to there, unlike the more technical components of the game development pipeline. 

[fn:3] This potentially is much harder than it sounds, especially if AI writing remains [[http://pangram.com/][easy to detect]] and noticeably kind of icky to read. 

[fn:2] This may potentially not be perfectly true, i.e. games which are "intended to create playthroughs which are then watched," but this is perhaps a topic of discussion for another post. 

[fn:1] People will occasionally draw nonsense in an attempt to demonstrate that it's possible to make art with no political undertones whatsoever. These conversations usually devolve into arguing about whether or not "deliberately making art with no political undertones" is, itself, a political act, but it's pretty evident these pieces are argumentative even if they are not political. 
