#+TITLE: Remembering Simplified Hanzi

* Remembering Simplified Hanzi Volume 1 Review

I recently completed Remembering Simplified Hanzi Volume 1, which provides a meaning-first overview of 1500 simplified characters for Mandarin Chinese.

The main premise of this book is that it decomposes the characters of Simplified Chinese into /radicals/, which it will compose together to create more and more characters. The book will slowly introduce new components, and then combine them with characters and radicals you've already seen before, in order to form new characters.

However, learning a large number of characters in this intuitive way means that you learn the characters in rough order of complexity, and not in order of how useful or common the word is. You'll learn the characters for "politics" or "righteousness" before you learn the characters for "I" or "green", and critically the book does not contain information on how to pronounce the characters at all.

You are expected to learn all of this stuff later, after completing the book. I am currently in this stage: I can recognize the characters, but cannot read them, and this feels very strange. If my Anki stats are to be believed, reaching this point represented about 90 hours of effort over the course of about 150 days[fn:1].

My anki deck still has a number of cards which are labeled "learning" and not yet "mature". But I figured it would be good to outline some of my thoughts on the book, and on the approach as a whole. 

** 100 Hours In Exchange For No Chinese

The strangest thing about having completed this book is that I don't really feel meaningfully better at Mandarin Chinese, or even really /reading/ Mandarin Chinese very much at all. I suppose this could be considered one of the largest weaknesses of the approach -- it's roughly 100 hours of work in exchange for future Chinese learning efforts to be marginally easier.

It's really hard to evaluate whether or not this is actually good or bad, or whether porting the approach over from Heisig's original Remembering The Kanji makes sense for Simplified Hanzi or not. Much spirited discussion about this has been had among the broader language learning community, and I think overall it was good that I just picked something and ran with it instead of getting overly mired in the details of picking one approach over the other.

Being frank about it: Remembering Simplified Hanzi is frustrating and boring. There are basically no "quick wins" or "positive reward signal" throughout this process much at all, and you don't come out the other side "knowing 1500 characters" in any meaningful sense of that phrase. Graded readers limited to 1500 characters will be way too hard for you. Graded readers with 300 characters will probably be way too hard for you, for that matter.

Not knowing how to pronounce the characters is perhaps an even larger barrier now than it was when the book was released, since "writing the hanzi" in modern settings usually involves you typing the pinyin into a keyboard and selecting the character from a list that appears. RSH is much more slanted for allowing the student to physically write the characters proficiently, with a much lower emphasis on recognizing the characters compared to producing them from the keyword. Frequently I have to resort to handwriting the character into Pleco in order to look up how to pronounce it, which feels pretty unusual. 

** RSH As a Marshmallow Test

[[https://en.wikipedia.org/wiki/Stanford_marshmallow_experiment][The famous Stanford Marshmallow experiment]] was one of the most iconic studies on delayed gratification, which insinuated that being willing to delay immediate rewards in exchange for greater rewards later predicted a bunch of good things about the participant[fn:2].

Throughout this process working through this book, I felt that most of what I doing was delaying this gratification for a very, very long time. Whenever I encountered characters working through HelloChinese, it became very, very easy to remember how to pronounce them if I didn't have to also memorize what the word meant. This is probably the strongest point in favor of the book, and of the entire approach: within the boundaries of this 1500 character subset, it feels a lot more like "learning a regular language" like Spanish or something, since there's a straightforward sound-meaning pair to remember instead of a sound-character-meaning tuple.

I think RSH (or related approaches) are probably the right call for a number of very specific groups: heritage speakers who can already speak Mandarin but cannot read or write, people who are marrying into Chinese families[fn:3], or self-learners who are super disciplined and willing to project themselves learning actively even years into the future. For students in traditional learning environments I could imagine this being confusing or even harmful, since you could likely pass exam questions not knowing how to speak out the answers you write down. 

** Ultimately, It Does Work

I made a number of little failures to learn Mandarin over the course of my twenties, which were mostly related to my total inability to ignore pinyin. Getting through this book is THE THING that made me stop doing this, even with characters that I absorbed only somewhat vaguely.

I have had some experience with memory techniques (that I have [[https://planetbanatt.net/articles/memorycraft.html][written about]] in the past) so I was pretty confident from the beginning that this approach would work well. 1500 characters was certainly the largest corpus of information I have attempted to memorize using these sorts of strategies, so scaling it up this much exposed a lot of issues with mental images being too similar to each other and causing hash collisions. My ability to absorb characters well definitely slowed as I neared the end of the book, but the approach is sensible and works well.

I do not think the RSH approach is perfect. I think there's many parts of it which use archaic terms (hootenanny, for example) which is a common criticism I see of the book. Likewise, Hanzi frequently have pronounciation components which act as hints to how to speak them, and it feels like this could have been sensibly incorporated without too much distraction, but the book largely punts this as "not my problem". However, learning new words using the characters you learn through this book becomes much, much easier, and I am expecting this to carry me forwards as I continue to improve my Chinese bit by bit.

At some point I am expecting to delete the RSH anki deck off of my phone, in favor of getting exposure to the characters by reading them in text. Something about that feels a little sad, after spending so much time on the drills. 

** Conclusion

It's hard to say if it would have been more efficient to just spend this roughly 100 hours learning Mandarin in a somewhat more normal way. I'd probably know way more words, and be more comfortable speaking. I'd probably be better at reading, too. But I think working through RSH was the right call, for me.

The decision to work through this book feels a little bit like the decision to go to college before working, or to join the workforce and begin earning money right away. People certainly argue about this all the time, and have various arguments that you should do one or the other.

I think, having gone to college, I don't spend too much time thinking about whether I regret that decision or not. It feels like I got through a big /thing/ that I worked hard for, and that feels good. It feels good that I can commit to these sorts of long, boring, frustrating projects, and I'd like to think that ability to commit is predictive of my future success learning things that are high-duration, high-boredom, high-frustration.

I made 1500 new friends -- now I just need to figure out how to remember all their names. 

* Footnotes

[fn:3] i.e. myself -- I don't know if I could reasonably get through this book for Japanese despite the approach likely being even better, since I could just get discouraged and convince myself that my passing interest in Japanese was just a fad. Chinese is certainly not going away for me any time soon so hundreds of days was a relatively small commitment all things considered.

[fn:2] Like all psychology, hard to replicate.

[fn:1] It felt like a really big time commitment, but I suppose I recently put 20 hours into Mother 3 over the course of about 10 days. It was just less fun, which made it feel larger.
