#+TITLE: Project Hail Mary

* Project Hail Mary Review

I watched this film on a plane to Seattle, so it is possible there are some elements I did not appreciate properly (e.g. the film score). But overall I thought this was charming and compelling, even if some components felt a bit handwaved to me. More or less, I thought the science fiction components of the film were lazy, despite the adventure components of the film being cute and charming. I thought the takeaways were sort of clashy with the tone of the film, but that it was at least well made overall. 

** Grace as the Wholesome Misanthrope

Grace is sort of a child of Omelas throughout the film’s runtime. The two fundamental things about him are that he’s a total loser, and that he’s very useful to other people. This makes him a bit of a target: he is never allowed to just live, value must be siphoned from him at all times, and he must never, ever be rewarded for any of his work or decisions. The film feels strange to analyze through this lens; subjected to forced martyrdom, Grace is unable to help himself from being useful to the very end, and is only rewarded when he turns his back on humanity in order to save his friend (but not without completing the mission first, of course). Practically every human character talks down to him in most of his human interactions in the film, e.g. scientists calling his experiments “crude and primitive, but replicable”, Stratt[fn:1] telling him “you’re smart, you’ll figure it out”, Carl telling him “you know who you are. You’ll do great.” 

Rocky in comparison is constantly dousing Grace with praise for his usefulness the whole film, calling him stuff like “the bravest human he’s ever met” in a clear half-joke near the end. It’s interesting seeing Rocky take on the role for Grace that seemingly Grace was taking for himself. When something dangerous happens during the fishing mission he urges Grace to abort the mission so they can just try again later, to which he replies “I don’t think there’s a later” for some vague and undisclosed reason, not unlike the way he was treated on Earth. There is a strange sense that Grace believes they were all right to treat him that way, that he was rightfully martyred, with no need for “my god, why have you forsaken me”

It was not even clearly explained why Grace was alone in the ship to begin with. This felt like a lazy rhetorical device to have him remember stuff more slowly than he would have, and to prevent any story beats where he would positively connect with another human. I initially thought there was some sort of crazy timeskip or huge accident, but it really seems like the three were supposed to work together at the work site until they solved it themselves, then die together. Instead they were dead from the very first shot of the film. It turns out they just didn't survive the long coma, so they contributed nothing to the film at all. Thank goodness Grace survived though, since he was essential to the whole operation! It is total nonsense -- if the other two crew were so expendable that their deaths wouldn't harm the mission, they shouldn't have gone in the first place, they died for no reason at all[fn:2]. If the crew were each independently able to do the mission if Grace had died instead, then there was absolutely no need for Grace to be forcibly drugged and martyred in the first place. The crew's entire narrative purpose in the film is to die immediately, and to contribute nothing. Again: compelling adventure plot point, lazy science fiction.

In the end, Grace gets rewarded by getting to be a schoolteacher on Erid, all of his human students being replaced with the young aliens. There's a sort of sober note to this despite the positive musical swells. The one positive connective tissue between Grace and humanity was his job as a schoolteacher, but that was more about him performing that role than it was about his relationships to other humans. Watching the ending, you get the sense that Grace would have preferred it if none of his students were human in the first place. Cutting back to Earth, everything is totally ruined, a huge contrast to how Erid looks, but at least they can start rebuilding thanks to Grace's successful journey. Everybody gets to feel like they were right all along. 

** Rocky is Not an Alien, But a Dog

Rocky was a cute character, perhaps too cute. I liked the machine translation plot point that they established at first, but over time it definitely came through that Rocky was based on a hugely wide array of anthropomorphic assumptions. Word substitution bits were obviously just English with an alien cypher on top of it, Rocky seemed too readily able to understand emotions like confusion or amazement, and even little assumptions like “Rocky needs to eat”, “Rocky has a single mate”, and “Rocky has excellent auditory perception”. He really felt more like a dog than an alien (which I believe is directly intended, see “you don’t even have a dog” when they were strong-arming him to accept the mission. He has one now!). There’s even an assumption that he would die exposed to Grace’s atmosphere, but actually it’s more like he just gets badly injured and then ends up totally fine later somehow. I thought that Rocky's body was going to assume the role of Wilson from Cast Away for the remainder of the runtime, but it turned out that he just needed a little more time to recover. Lazy, but we can't have Grace's dog just die in this wholesome film.

Grace's original thesis, that lifeforms could in principle be possible without water, has some interesting wrinkles in the film which are not present in the original book. In the book, this is something which is just proven wrong over and over again: Earth life is made of water, astrophage is made of water, and even Rocky is made of water. However, in the film this last one is never stated, which adds a very interesting note of subtext to his relationship with Rocky. In the film, Rocky does seem to be, well, some sort of big sentient rock. But all Grace seems interested in about him is actually understanding him: reverse engineering the language, learning about Rocky’s personality, observations about his hearing and intelligence, and so on. The film does not acknowledge the possibility that Rocky is non-water-based at all, completely refusing to take the opportunity to use Rocky to validate Grace. This is an example of why I keep going back and forth between calling parts of this film "lazy" and also "compelling," since it seems like a lot of effort went into crafting /Project Hail Mary/ as an adventure film, even sanding over the science fiction components to make those elements all less interesting. I do actually think this is a good change compared to the source material: Grace’s correct thesis lives totally inside the subtext of the film, since bringing it forward would cheapen their relationship. Grace does not love Rocky because Rocky represents a validation of his worldview, he loves him because there's a bond they develop during the runtime.

Accordingly, Rocky is much nicer to Grace than virtually any human is throughout the entire film. There’s limited exception to this with Carl, who serves as a pretty interesting foil to Rocky. Carl and Grace understand each other virtually immediately, but in the end Carl does aid in his betrayal. A question I had throughout the film was “why does Grace even want to go home?” When Rocky gives him the fuel to go home, he seems mostly just happy that he won’t immediately die after the end of the mission. When he has to choose between Rocky and Earth it’s a super easy choice, and when he’s safe and sound on Erid he’s appropriately hesitant to return home. I originally thought this was going to be a thematic weakness of the film, so I was pleasantly surprised when Rocky giving the fuel to Grace ended up saving both of their lives (by putting lots of astrophage away from the taumoeba) instead of being a comparatively low-cost sacrifice. 

** Conclusion

Project Hail Mary was a pretty interesting film. It was fun! But it seemed like it was mostly a children's movie with science fiction window dressing. Like many other general-audience-but-mostly-for-teens films (e.g. Barbie (2023)) it suffers from too many decisions being shallow and poorly thought through, and thinking about the movie too hard will make the entire film's thesis become confusing and often contradictory (e.g. /Barbie/ is a film about upholding the gendered power structure of another world). It's best watched as a movie about a guy trying to save the world with the help of his enthusiastic non-human companion, with beautiful space opera cinematography and Ryan Gosling in the lead role. Nothing more, nothing less. If that sounds fun, you'll probably have fun. 

* Footnotes

[fn:2] Getting ahead of the objections here, I do understand that various things went wrong due to Grace being required to learn how to perform the other roles, and I do understand that Rocky's unplanned addition effectively replaces Grace's crew with another engineer. Being a little more direct, the mission's [[https://en.wikipedia.org/wiki/Bus_factor][bus factor]] was 1, and the person who did not die happened to be the only one whose presence was not redundant or salvageable. If Yao and Grace had died instead, Olesya would just be lost in space until she died as well. Instead what we get is Grace encountering two dead bodies, saying "I have no idea who you people are", and then burying their bodies through the airlock in a sort of burial-at-sea. Had either of them survived, none of the core ideas of the film work anymore, so it was really important that they were both disposable and also non-essential, which I did not like. 

[fn:1] Stratt's relationship with Grace was praised by other reviewers, but personally I found this relationship to still be outrageously flat. There are a few scenes where it seems like Stratt and Grace are opening up to each other, but the power imbalance between the two means that it never graduates beyond a Boss-Employee relationship (and of course in the film Stratt betrays him in the end)
