#+TITLE: Intermediate-Professional Level

* The Intermediate Professional

I’ve been learning some drawing recently. I watched [[https://www.youtube.com/watch?v=NxsSVW1C39M][a video]] about how to learn basic shapes, building up to drawing a basic human figure in 30 days.

This video had a very strange conclusion. It ends by saying the following:

- If you want to ascend from intermediate artist to advance artist, you need talent and artistic sense. For some, no amount of practice will ever make this happen.
- However, you only need to reach intermediate level to work professionally as an artist.

This was a very jarring pair of things to hear so close together. Normally, you are used to hearing one or the other (i.e. that anyone can reach any level at anything with enough effort, or that professionals in competitive fields are at least at the advanced level). Seeing them paired really does communicate a lot, in a funny way. Anybody can “make it” even with no talent, it’s just that you only need the intermediate level to make it. 

I started randomly drawing recently because I was motivated by playing deltarune chapter 5, more specifically because I admire Toby Fox. Toby doesn’t even do the art for his games ([[https://en.wikipedia.org/wiki/Temmie_Chang][Temmie Chang]] does, of course). But I think that whenever he shares his [[https://x.com/tobyfox/status/1939307524442017864?lang=en][amateurish concept art]], I always feel like it all looks like it was very fun to draw.

In general I am the type of guy who tends to like to do things with the explicit goal in mind of achieving a very high skill level. I tend to like things I’m well-suited for, and dislike things that don’t come naturally to me. But recently I’ve been thinking a lot about what things are worth doing even just with the explicit intent of capping out at the intermediate level. I’ve gone well into my adult life being completely unable to draw at a level even small children easily achieve. It’s possible that just thirty days of moderate effort could get me able to draw silly little comics, or sketches of characters I like. There’s probably a lot of stuff like this, where the path to the advanced level seems extremely daunting, but everything I want to do with it just lives in the intermediate level anyways.
