#+TITLE: 36th Chamber

* The 36th Chamber of Shaolin

I watched this recently, and it was a genuinely insane movie to watch right after /Marty Supreme/. Liu Yu-de is powerless to defeat General Tien Ta, and wishes he knew kung fu so he can defend himself. So he journeys to the temple, and learns kung fu. He spends 6 years ambitiously studying kung fu, getting through almost all the chambers of the temple which all teach a single thing, gets very good at it, then goes to defeat Tien Ta. He then opens a new chamber where he teaches kung fu to laypeople so they can defend themselves, the titular 36th temple. The end.

If that description seems short, that's because almost the entire film's runtime is just him spending the entire time learning kung fu, and getting through the chambers. The /purpose/ of all of this is so he can defeat Tien Ta and prevent the tyranny of future Tien Tas. But this stuff is mostly just the outer layers of the movie, only really in the beginning and the ending. He can only do this stuff if he becomes a master, and he becomes a master in a completely reasonable, but commendably fast amount of time. He doesn't even ascend to the 35th chamber, which lets you unlock special Chi powers.

It feels like movie is communicating something like "you can get good at really hard things if you just spend a few years working very hard at it" and for that reason it's one of my favorite films I've seen in a long time. It's a love letter to /grinding/. The scenes where he's shadowboxing in the bamboo groves against the discipline chief juxtoposed with those moves being more complex in reality are some of the coolest representations I've seen in a film like this.

People generally don't get good at things because they don't like to envision the path of mediocrity necessary to cross to become as good as they want. But that path is usually very crossable. You just have to start the journey, and not give up.
