#+TITLE: Mother 3 Review

* Mother 3 Review

I finally played all the way through Mother 3, so I wanted to write down some of my thoughts about the game. Overall I thought it was pretty excellent; the music, gameplay, and story were all great start to finish. This short writeup contains heavy spoilers for the game. 

** Playthrough + Rough Edges

I played through the game in a little over 20 hours, which I gather is on the slightly faster side for a first playthrough. I played through the game on my phone via retroarch, using the fan translation patch (obviously), and I did not use savestates or anything like that. There are some rough edges that come from using touchscreen controls but nothing that caused too much trouble. 

I think in terms of stuff I did not love, I thought the game had pretty bad pacing problems throughout, possibly related to my playthrough being a little faster than average. The game warns you pretty early that you’ll be underleveled if you run past enemies and skip fights, but even frequently going out of my way to fight enemies I felt severely underleveled for the first seven chapters.

Likewise I found the way losing works in this game to be extremely irritating. If you lose a battle, you will respawn at the last save with full health and PP, with all the experience you earned, but without the items you used in the fight. This generally is fine since lots of save points are coincident with hot springs or revitalization machines, but in the situations where that’s not the case are pretty annoying. It was common for me to enter boss fights and feel like my best option was to deliberately lose as fast as possible as a sort of “bootleg hot spring”. 

Likewise, god forbid you use an item in a boss fight and then lose, since now you’ll have to do that fight without that item. This introduces a second problem with saving: there are two “ways” you can use a save. You can hit “continue” and respawn with your experience but without your items, or you could hard reset your game and respawn with your items but without your experience. I can kind of understand why you couldn’t let the player have both, but gating the more natural behavior behind a hard reset was clunky and I would have preferred if this was just a real option in the game over menu (thankfully I only used this briefly about two times). 

I think at first I was mostly willing to look past the pacing problems by attributing them to my lack of grinding. I didn’t really want to be the guy who said “this JRPG sucks because I didn’t want to grind”. I felt that almost every boss from chapter 2 onwards was borderline romhack difficult, and I won almost all of the big fights after depleting my entire inventory and having 3/4 of my party dead. But then the game gives you PK Starstorm and PK Love Omega at about the same time, which immediately made the game way too easy. I thought this was sort of a shame, since the difficulty level dropped dramatically right at the end, with the most difficult bosses. The Barrier Trio and the Chapter 7 Masked Man were way harder than the climactic final bosses, which I thought was a bit strange.

The game does try to lightly prevent you from spamming PK Love Omega and PK Starstorm by giving climactic bosses PSI Counter shields, but this happens roughly when you get PSI Lifeup Omega, and you will surely have enough health to live through full party mortal damage and heal the whole party right after anyways. It feels lame complaining about having powers which are too strong, but it felt like there would have been a more even pacing throughout chapter 8 if forgetfulness was a more common status ailment instead. 

** Strangeness Is Multifaceted

The most charming and memorable thing about Mother 3 is how strange it is. There are frequent comparisons drawn between it and the Toby Fox games, but I think the particular flavor of strangeness feels fairly distinct — Mother 3 feels more like a game from a world where games are just strange like this, rather than an “especially strange game”. It’s rare for Mother 3 to wink at the camera much at all, even when it’s being coy or breaking the fourth wall. 

The strangeness is simply core to the entire gameplay, so much so that it all just becomes normal, even without any effort spent suspending disbelief. Of course all of the music has wonky, stumbling time signatures, how else would the central battle mechanic get more difficult otherwise? Of course the enemies and environments are unsettling and weird, that’s the entire point of Porky’s characterization. This is probably why the game has gone so long without any real hope for an official English localization. Plenty of stuff in the game feels dated, but the idea of censoring the game without compromising the vision of the entire thing does not seem super feasible. It’s laughable to imagine a mangled version of the game with all the queer themes removed, for example. 

You would expect a game with the strangeness turned up to 11 to have some sort of message like "strangeness is good" but surprisingly this is not the case. While the strangeness is the focal point of the game, it can often be both good and bad, sometimes both at the same time. On that front, the [[https://mother3.fobby.net/interview/][Shigesato Itoi interview about the development of Mother 3]] is illuminating, and I'll be referencing lines from it frequently throughout this post.

#+BEGIN_QUOTE
Itoi - One of the underlying themes of MOTHER 3 is that there are two feelings--like, "C'mon, it's just a game," and, "C'mon, be serious, this is a game here."

...

Itoi - MOTHER 3 might not appeal as much to people who can't enjoy gray areas. They'd just want to demand that characters are either good guys or bad guys. (laughs)
#+END_QUOTE

One clear example is the way Itoi describes the Magypsies as "like Chimeras, a fusion of man and woman" which certainly brings this particular idea to the forefront[fn:1]. The Chimera, despite being the main vehicle for creating enemies in the game, also protects the Earth and safeguards psychic powers.

#+BEGIN_QUOTE
Itoi -  It's because the world in the game is so macho. The good guys in the game are strong and they fight. The same goes for the bad guys. So in other words, it's set up so that might equals right. "Power is Beautiful." And amid all of that, there are these non-men yet non-women people who have already gone so far as to accept their fate of death. If these characters really existed... I would want people who play MOTHER 3 not to act hostile towards them. I would want them to have fun together in a world they both share.
#+END_QUOTE

This is part of what made the game feel very special to me: in spite of the strangeness it didn't feel especially like a game which was made /to celebrate strangeness/. Things that are strange simply exist in the world, and you are supposed to understand that /that's just how the world is/, and understand that sharing the world with this strangeness is your duty as a player (or more broadly, as a person).

Duster being disabled is another good example of this. Characters will regularly talk about his leg in the same breath they talk about his quite renowned ability to play Bass, or his inconsistent ability to be a good thief:

#+BEGIN_QUOTE
- Why did you give Duster a bad leg?

Itoi - I figure that because there are handicapped people in our world, it would also be part of the world of MOTHER 3. After all, there's no way that any two people have the same physique or even the same personality. Just like with the Magypsies, I included Duster so we could have someone with bad breath, a disabled leg, and living as a thief. The MOTHER 3 world is all about having friends like them. Perhaps you could call them symbols of not rejecting such people.
#+END_QUOTE

** Shigesato Itoi

Itoi is a pretty interesting guy. His [[https://en.wikipedia.org/wiki/Shigesato_Itoi][Wikipedia page]] is this eclectic mash of a lot of different things. He's a famous essayist, he is an actor who has done voice and live action work, he founded Ape, Inc. which would go on to make stuff like the Pokemon TCG, and of course he was the lead writer for the Mother series.

There's a bunch of additional random stuff in here also -- for example, he is the president of the Japan Monopoly Association and placed 8th in the Monopoly World Championships in 1992. You get the impression, reading all of this, of a person who is always doing things, even totally unrelated things. Having such a whimsical career must make being alive such a joy. 

At one point, he had a chance encounter with American game developer Toby Fox.

#+BEGIN_EXPORT html
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Today when I was walking around Tokyo, I happened to find a Hobonichi event (Shigesato Itoi’s company). Then, I happened to meet Shigesato Itoi (MOTHER&#39;s creator). He told everyone I was an awesome game designer. I’m happy... <br><br>This world is made of strange coincidences, huh</p>&mdash; tobyfox (@tobyfox) <a href="https://x.com/tobyfox/status/1004666083792412672?ref_src=twsrc%5Etfw">June 7, 2018</a></blockquote> <script async src="https://platform.x.com/widgets.js" charset="utf-8"></script>
#+END_EXPORT

I think comparing these two is pretty interesting. It's very clear Fox has substantial admiration for Itoi, given how he got his start hanging out in the starmen.net forums. In a [[https://undertale.tumblr.com/post/150397346860/retrospective-on-undertales-popularity][1-year retrospective after releasing UNDERTALE]]:

#+BEGIN_QUOTE
Someday, UNDERTALE will fade from people’s minds. But, I’m sure in 10 years[fn:2], some kid who played UNDERTALE will create a game that surpasses it…

I look forward to playing that.
#+END_QUOTE

It's amusing to consider Itoi created a Japanese video game franchise which makes heavy callbacks to American culture, and that Fox created an American video game franchise which makes heavy callbacks to Japanese culture. In general I view Toby Fox's body of work as similarly eclectic to Itoi, although perhaps smaller, due to him not being 77 years old. Likewise, it's amusing to consider a world where Toby Fox actualizes as much random ambition as Itoi -- maybe he will spend his 40s getting unbelievably good at Monopoly. 

** PSI

#+BEGIN_QUOTE
- The way you learn PSI is portrayed a little differently this time.
  
Itoi:   It's like, umm... It's like menstruation.

- ???

Itoi:   One of my themes is representing the physiology of the human body. It's a lot like the Asthma Spray. A character will start sweating while realizing PSI, almost like with a teething fever. Whenever a human being develops or learns a new ability, the body really takes a beating. I've had this experience myself--whenever I'm feeling sluggish and exhausted, it's absolutely certain that good things will follow. When you're given an overwhelming problem you just can't deal with, the only way to cope with it is to completely mobilize your heart and your mind and make a strenuous effort to get through it.
#+END_QUOTE

The way psychic powers are treated in Mother 3 is more interesting than the other entries in the series. Compared to Earthbound, learning new powers is disruptive and annoying. Since it generally seems limited to the Magypsies and their students, there seems to be more clear commentary on who can use PSI and why that may be, compared to earlier installments.

Fassad's character is a pretty heavyhanded about this. The reveal at the end that he's the final magypsy puts a lot of things in perspective. Throughout the game we see Fassad slowly transform to a more and more grotesque perversion of his former self, but the final reveal shows us that he's already extremely transformed by the time we see him for the very first time. It can be inferred that he stopped doing drag when he began to be corrupted by Porky, which can be read as a loose sort of detransition commentary.

** Closing Thoughts

There certainly is a lot to dig into with this game. The various interviews mention [[https://en.wikipedia.org/wiki/The_Notebook_(1986_novel)][Le Grand Cahier]] and [[https://en.wikipedia.org/wiki/Tannish%C5%8D][The Tannishō]] as important contexts for how he chose to write Mother 3, and I'm sure there are closer readings of this game possible with people who are well-read enough to go band for band with Itoi. I'm sure I could flesh out my thoughts on PSI or Itoi's career much more than I have briefly outlined here, but this is just my thoughts a day after playing it. 

I doubt anyone reading really needs my endorsement to play a game as critically acclaimed as Mother 3, but the game is indeed as good as the big cult following would suggest. The fan translation is excellent, and you can play it all on your phone, it turns out, so there's really no reason to let this one go unplayed. 

* Footnotes

[fn:2] When you're 25 years old I'm sure 10 years feels like a really long time, but it is very funny looking at this quote 10 years later. The spirit of the quote is still powerful and everything, it's just... maybe it would be more like 25 years. 

[fn:1] Itoi gives scattered credit to different people for the creation of these guys. It's nebulous how much of the idea came directly from him, as he references the concept artist for "the real credit" and also mentions that Shogo Sakai, the composer for the game, was the originator for their names being the [[https://en.wikipedia.org/wiki/Mode_(music)][musical modes]]. 
