#+TITLE: Dead Games

* Lamenting dead games

It’s 2004. I’m playing my favorite game in my basement, on the family computer. I am having fun, an almost sickening amount of fun, the type of fun that feels like I’ve eaten a bowl of candy instead of dinner, and I’m going to get yelled at later for it. Nothing beats this. Maybe nothing will ever beat this. 

It’s 2026. Dead games are a dime a dozen. Maybe in 2004 we hadn’t quite reached it yet, but in 2026 we are living in a fully post-scarcity entertainment environment. There are more games than any one person could ever play in a lifetime. The feeds simply never, ever end. They’re talking about making them generate more entertainment somehow, just to make it even a little bit more infinite. I think about that game I liked in 2004. Nobody plays it anymore, really. I wasn’t crazy about the sequel, but I guess it wasn’t really aimed at me. 

On a whim I boot it up on my computer, now comically overpowered to run a game this old. The game doesn’t boot properly at first. I have to run it in compatibility mode for Windows XP. The game springs to life in front of me and the memories all flood back to me. It really does all still hold up even now. I tab over to the game’s multiplayer, and there’s a server with four other people playing. They’re all much better than me. But it still reminds me of 2004. In 2004 I was very good at this game. I was, like, maybe 95th percentile at it. Now I’m the worst of the five people on the server still playing it. I try briefly to come up with some tortured way to describe my skill level as anything better than 0th percentile.

I smile a little bit thinking about it. There was a time when I really, really cared about being good at this game. I attached a lot of my identity to it, probably way more than I should have. Being good at it meant that I could tell myself that I was smart, that I was better at learning than other players, that I could command my body better than them, that I could make the objects on my screen dance around in a way that they couldn’t. It felt good, back then. It feels good now just remembering it. 

A part of me thinks about how it might be doable to get back into it, to try to feel that feeling again. But, I quickly realize, it wouldn’t feel quite the same, to get good at something after most people are done caring about it. As much as I want to believe otherwise, some part of it still required the other people involved. My choices here are to either pursue this fully personal journey nobody else would care about, or to instead get good at whatever bullshit people are playing nowadays.

After a few hours I close the game. My familiar desktop fills my screen again, ripping me back to 2026. A sheepish embarrassment creeps up on me. There was a time where I earnestly wanted to be a professional player at this game, where people would actually pay you real money just for being so good at the game. I still believe deep down that if I threw everything else away that I could have been a pro, actually; that I had the real talent necessary for it, that I just needed hours I didn’t have. I try not to litigate that thought just in case it would lead me to conclude I am just coping about it. In any case, nobody is a pro at this game anymore. Anyone who was good enough at it probably jumped to being a pro at the sequel. I briefly wonder if the people still playing it are better than the pros were back then. Ehh, probably, I guess. The old pros would probably be good too though, if they came back.

A thought crosses my mind. Maybe I actually regret playing this game? I spent so much time learning everything about it that I could. So much of my brain is permanently etched with little factoids about this game, so much stuff that is pretty much useless now. It was so awesome then, it felt worth learning and practicing and getting good at. All for nothing, I guess. Maybe I should have spent the time on something useful, something which would have lasted, which…

I shake my head rapidly. Get a grip, dude. It was a video game that I loved playing. It’s a game that I loved every millisecond I spent playing. I have nothing but beautiful memories of all those many many hours. Even the unhappy memories are beautiful. Erasing them would be erasing a huge and fundamental part of the experiences that made me me, and none of that is regrettable just because the attention economy and the market value of skill both shifted away from this particular game. I’m just getting in my own head about this game I loved being dead, and wishing that I never loved it instead of wishing it weren’t dead. 

I did like it, back then. Hell, I liked it just now, just a few minutes ago. Maybe I’ll still try to find some excuses to play it every now and then. I open up my Discord and see my friends have been messaging me. They want me to try this new game they’ve all been playing. Maybe this one will be fun too.
