#+TITLE: About Me
* About/Contact
  :PROPERTIES:
  :CUSTOM_ID: aboutcontact
  :END:

Hello!

** Self

I'm Eryk. I am a research scientist at [[https://en.wikipedia.org/wiki/Riot_Games][Riot Games]]. I did my
undergraduate degree in Cognitive Science at Yale University (Class of
2017), and did my masters degree in Artificial Intelligence at Johns
Hopkins University (Class of 2024). My work touches a lot of topics in
deep learning, specifically in spots where it could potentially add
value to [[https://planetbanatt.net/articles/usefulgames.html][games]]. I am often referred to online as "Ambisinister" or
sometimes just "Ambi"[fn:1].

** Content
   :PROPERTIES:
   :CUSTOM_ID: content
   :END:

I use this website as a way to help me think about things. Scattered
across this website are writings on various topics like machine
learning, cognitive science, programming, video games, multimedia,
energy drinks, anime, and all sorts of other things. This website is a
big digital notebook that I use so I have easy access from any device
to thoughts I have had before, even in cases where they are
[[https://planetbanatt.net/articles/energydrink.html][potentially]] [[https://planetbanatt.net/articles/huel.html][silly]]. /Writing is thinking/, so a useful framework for
understanding this website is that it contains my thinking, and is
therefore always subject to change.

As a result, I keep no chronology of the posts I put on here, roughly
by design -- I have an explicit dislike for blogs, since I want both
the reader and myself to revisit any page on here in 5/10/20
years. What works best for me is if I keep all of these thoughts in a
large collection of plaintext files on my computer, and automatically
generate the website from these files[fn:2].

If you want to understand /what I am up to/, I do try to maintain a
relatively light log of my inputs/outputs over on the [[https://planetbanatt.net/links.html][links page]], but
since this is performed by hand there's no guarantee it will be
comprehensive, it mostly serves as a way for me to save things I want
to remember + keep myself accountable doing things.

** Learning By Accumulation
   :PROPERTIES:
   :CUSTOM_ID: learning-by-accumulation
   :END:

This is a sort of meta-skill I developed during my college years that
has served me extremely well up to now. Before I started learning to do
this, I would think of project ideas and more or less immediately
discard them, since I didn't yet have the relevant skillset to
accomplish it and felt that acquiring that skillset would be too much of
an investment. Something like "make a machine learning classifier for
seeding tournament brackets" felt impossible to me, since I was under
the erroneous assumption that I would need to learn mountains of machine
learning to "become worthy" of doing a project on machine learning. In
short, I felt that I didn't deserve to use tools that I had not yet
mastered completely.

Luckily, I realized, that's not really the case! Becoming functional and
mediocre at pretty much anything is within reach for pretty much anyone,
and if you're doing it for the sake of a project and not a career then
it's often practical to only acquire what you need to accomplish your
goal. This can often lead you to a more passionate interest in your
subject that you otherwise would have had (i.e. making something cool to
gauge your interest in a subject, then deciding that it was extremely
cool and learning more about it).

The nice thing about this is that your skillset and knowledge don't go
away after you finish your project. By doing many things, you learn to
do many things, and thereby gain access to even more things you wouldn't
have even thought of had you not done the first thing. As they say, once
you're given a hammer, nails start popping up all over the place.

It seems like a pretty obvious thing to say, but you won't believe how
often I see people place this sort of self-imposed barrier to action
upon themselves. People who show up to SSBM tournaments after spending a
year practicing by themselves, since they didn't feel "good enough to
play with real players", or people who refuse to do anything vaguely
math-related since they're afraid of numbers.

Also important to note is that learning in this way will often put you
face-to-face with failure. It's important to realize that this is okay!
Having consistent output is more important than making sure all your
output is good, since you have no obligation to share every single
failure you have. Trying something too hard and messing up still nets
you experience points in the real world, and as Neal Stephenson put it:
"hey, at least a wild-goose chase gives you some exercise."

** Disagreeing with Me
   :PROPERTIES:
   :CUSTOM_ID: disagreeing-with-me
   :END:

You may eventually find a point on which you disagree with me on,
perhaps extremely strongly. For these events, please consult the
following directions:

For smaller disagreements, I would suggest just confronting me about
them. I have a stronger interest in holding accurate beliefs than
defending my own beliefs, so there's a very real chance that you'll be
able to change my mind, and even if you're certain I won't be able to
change yours I would probably appreciate the opportunity to challenge my
own beliefs and make them more accurate. You can do this at virtually
any time, and I will not request time to prepare myself since if I need
preparation then I probably don't have a very solid grasp of why I
believe the thing anyways.

For larger disagreements, we can settle it like gentlemen/women and have
a good, honest duel over it. I propose a set of three games, each best
of three. one in a game of my own choosing (most likely Super Smash
Brothers Melee), one game of your choosing, and a game in the middle
(let's say, rock paper scissors). For these disagreements, I suggest a
training period of one month in which I can learn your game and you can
learn mine, and at the end of the month we duel and the winner would be
declared the victor, being definitively and objectively correct at
whatever squabble we were having. I am reasonably competent at many
games, but I am not amazing at any of them, so I find this to be a fair
victory condition.

For the biggest, most impossible to resolve disagreements, I am willing
to accept a challenge to a fair and honorable boxing match to the death.
Please only use this option for the most passionate beliefs you have,
those because of which my existence completely invalidates yours. I
reserve the right to tap out at any time (with the condition that you
are declared right, of course). However, this will require a full year
of training, in which I will have enough time to get in decent shape,
learn some sort of martial arts, and come to terms with the fragility of
life. Like I mentioned, though, most things probably would be better
suited for the previous condition with the three video games, so please
choose those as a default option.

** Getting in Touch with Me
   :PROPERTIES:
   :CUSTOM_ID: getting-in-touch-with-me
   :END:

If you want to talk to me about academics or any of my more serious
projects, feel free to shoot me an email at erykbanatt@gmail.com

You can find me on twitter
[[https://www.twitter.com/ambisinister_][@ambisinister_]].

* Footnotes

[fn:2] If you've poked around the source for these pages and been mortified, please understand that this is why the pages are like that. This is all hacked together from the org export function in my emacs configuration, and it's a miracle any of it works at all -- this website is not meant to be a showcase of my ability to do webdev, it's meant to be a maximally frictionless way for me to type plaintext into emacs and post that somewhere.

[fn:1] Specifically, this is [[https://liquipedia.net/smash/Ambisinister][my gamertag]] (adj. Clumsy or Unskilled with both hands), but you can just think of it as a common nickname I am often called. 
