* Monthly Links

This page is mostly a log in which I keep links to things I've read,
made, done, etc. It's separated by month, along with my goals for the
next month, and should be end up being in reverse chronological order

** 2019
*** January 2019
**** Goals for February
     - *Decide which project to tackle next, begin working* I'm bouncing around a couple of fun ideas so I need to pick one; I'll probably end up picking the one that ends up the more technically challenging, for obvious reasons.
     - *Spend some time on organization* I've let my organization escape me a little bit so it'll be good to spend a little time to get everything back in place.
     - *Nail down some IRL goals this month*
**** Things I've Made
     - [[http://planetbanatt.net/articles/personainsmash.html][Predicting Personality with Playstyle in Super Smash Brothers]] People have been kicking around this question for ages so I did some research to get to the bottom of it. I opened the survey on January 8th, closed the survey on January 10th and began writing, and then posted this essay on January 18th, which means I turned around this project in roughly one week which I'm very proud of. 

**** Things I've Consumed
     - [[https://www.youtube.com/watch?v%3DGyUcwsjyd8Q][OCARINA OF TIME - A Masterclass in Subtext]] A documentary about subtext in OoT; one of the most well-edited and moving pieces of content I've seen in so, so long. Sort of like my [[http://planetbanatt.net/articles/pingpongzen.html][Ping Pong essay]] but so well crafted that I got self conscious thinking about my own content.
     - [[https://www.youtube.com/watch?v%3DHEfHFsfGXjs][The most unexpected answer to a counting puzzle]] 3Blue1Brown really hits it out of the park with this video, one of the weirdest math problems I've ever seen in my entire life. [[https://www.youtube.com/watch?v%3DjsYwFizhncE][Answer]]. [[https://www.youtube.com/watch?v%3DbrU5yLm9DZM][Answer 2]].
     - [[https://www.youtube.com/watch?v%3DXbNWFQ4jqpQ][Bob$ on Crush vs lloD]] one of the best SSBM analysis videos I've seen in some time.


** 2018

*** December 2018
**** Goals for December
     - *Resume Reading* as I completely and abruptly stopped reading in favor of working on the Homestuck project
     - *Enroll in an online class* since my younger brother got this for me for christmas, have to decide what I want to take, though
     - *Practice a bit for Genesis 6*

**** Things I've Made
     - [[http://planetbanatt.net/articles/visualdistance.html][Locating Visual Jokes in Homestuck with Rudimentary Computer Vision]] probably the fastest I've ever completed a project of this rigor, which was really exciting! The project took me about a month and a half and I was really committed to completing it before the year ended, which I thankfully was able to accomplish. Definitely among the more technically interesting projects I've done, performed [[https://www.reddit.com/r/homestuck/comments/aas7fb/locating_visual_jokes_in_homestuck_with/][moderately well]] on the /r/homestuck subreddit. 

**** Things I've Consumed
      - [[https://www.youtube.com/watch?v%3D0dX-Pc4nPMQ][Big Fish & Begonia]] one of the most moving films I've seen in a long time. As far as I know this is the first film from this studio and I think that if they continue making films of this quality they could establish themselves as a worthy rival to Studio Ghibli in time. Started out as a [[https://vimeo.com/67224050][flash animation]] in 2004 which is actually just wild to me.
      - [[https://escholarship.org/uc/item/9050x4r4][Reproducible Research: the Bottom Line]] paper about Claerbout's Principle, which roughly states "a paper about a computational result is advertising, the actual scholarship is in the coding environment"
      - [[https://www.youtube.com/watch?v%3DhpIs__45t5I][Justin Verlander's Impossible Inning: A Study in Velocity and Spin Rate | Baseball Bits]] randomly stumbled into this and I love the way it's put together. The music was great, also!
      - [[https://www.youtube.com/watch?v%3Dv1Mjc4zNfY4][The Conservation of The Assassination of Archimedes Narrated Version]] I love watching people skilled at their craft do their thing
      - [[https://www.youtube.com/watch?v%3DGknVZeFJ2Ug][Getting Better Faster - Painting with 80/20 Rule]] A really fun video about using quick sketch painting to study your failures in novel contexts as many times as possible within a short window.
      - [[https://www.youtube.com/watch?v%3DMijmeoH9LT4][Characters, Symbols, and the Unicode Miracle]] a cool and clear explanation of an otherwise mundane topic

**** Reflections

The links page has become, weirdly enough, one of my favorite projects. I'm reminded of a suggestion I heard a long time ago (I think it was from Day[9] but I am unsure) to keep a journal full of awesome things you have done so you can look back at it whenever you feel down about yourself. It's really cool being able to flip through and at a glance see where all your time in a year went, which months were strong and which were weak, etc. 

A useful thing I can do here is briefly reflect on 2018 and how it squared with what my goals were for the year:

I read 11/30 books, 9 reviewed on [[https://www.goodreads.com/user/show/25277520-eryk-banatt][my goodreads page]], one being a re-read (Once a Runner), and one being Anokh's /The Book of Melee/ which I obviously won't review extensively due to it being currently unreleased.

I wrote 7 longform posts on this website (Homestuck CV, STARS ALIGNED annotations, Celeste Review, Anki notes, Projects page, Boredom Types rant, Making Sense of Melee), I made 6 videos (Shinelock Punishes, Box Practical Tech, Bombs over Battlefield, Shine 2018 Clips, STARS ALIGNED, Stray Saturday), I made semi-regular appearances on the /Melee Stats Podcast/, and I revamped this website to be a lot more efficient (i.e. easier to read, mobile friendly, auto-generated from org mode documents, better in general overall). My original goal was just "15 longform posts" which I set rather aggressively to encourage shorter writings (i.e. ones that don't require months of work like Making Sense of Melee, the Homestuck CV project, STARS ALIGNED and it's annotations etc) so I it'll be okay if I cheat a little bit and consider this goal met just via converting quantity of work from one format to another.

I'm unsure if I'd consider myself the fittest I've ever been but I've made some substantial progress on that front and I'm pretty satisfied with that. I think I need to learn how to balance the different types of training into somethat that works for me because it's hard to me to juggle everything (e.g. I stop running if I go to the gym more, I stop going to the gym if I focus on rock climbing, etc). 

I think overall I'm pleased with how I was able to focus on goals I defined myself throughout 2018. I had a lot to show for my use of free time in 2018, and probably are most proud of [[http://planetbanatt.net/articles/ambistats.html][these]] [[https://www.youtube.com/watch?v%3DOGpB5d5nuPg][three]] [[http://planetbanatt.net/articles/visualdistance.html][projects]]. I think I could've done more - in particular there are two projects I started that fell through mostly due to my decision to focus on Melee a bit more during the summer (between EVO / Shine / Big House / etc). Likewise I didn't do anywhere near enough reading, at least as far as books go. I was mostly good about staying on task but there were a few months where I felt like I accomplished almost nothing. These were generally in the summer, and in general I found it difficult to get back into the swing of independent work after doing any sort of travelling. 

Anyways, 2019 goals:
- Dramatically restructure life to spend higher percentage of time doing things I find interesting instead of just a few hours a day
- Complete 15 projects, four of them being "large projects", at least five of them including a longform writing component
- Read 20 books
- Become strong


*** November 2018
**** Brief Updates
     - *Started some cool things but haven't completed them*
     - *Have been doing a lot of reading but haven't finished any books*
**** Goals for December
     - *Complete both books currently reading*
     - *Complete short-medium difficulty project and writeup* Pretty happy to be able to jog my memory of something I learned in school years ago.
     - *Reassess goals from end of year 2017* I was way off, but not so way off that I feel discouraged about it.
     - *Come up with new goals*
**** Things I've Made
     - [[https://www.youtube.com/watch?v%3DHOSbE9PMDK0][Stray Saturday]] very short highlight reel of some cool melee clips from one saturday's worth of games with my friends.
**** Things I've Consumed
***** Papers
- [[https://docs.google.com/document/d/1f4P-L8RHc5hhjYk4wP4lVNCeRpXJx7h5CxWdbIjcXZ4/mobilebasic][Climbing the Ladder: An analysis of Class Divides in Player Communities]] Cool paper by Demise of the DCSS community about Social Capital in gaming communities (I think WIP?), basic idea is that players become better at games and this accrues them social capital in their scenes, which makes them more authoritative in discussions. 

"I wish to clarify that an inherent danger of climbing the social ladder in small communities is that a player can lose sight of the intense sway that they hold. Even falsities can be accepted by the weaker party when enough people gather around the stronger individual. Those with high capital should seek to view discourse in light of their own authority, and consider whether or not their opinion is actually correct or if their authority has preceded them."
- [[https://arxiv.org/abs/1811.07153][Robust Website Fingerprinting Through the Cache Occupancy Channel]] This is horrifying! tl;dr you can look into the cache of the user on your site to look at what they have open on their other tabs, which is highly effective on both normal web browsers /and Tor/. If you're gonna do something illegal make sure you close that fbi.com tab first.
***** Videos
- [[https://www.youtube.com/watch?v=5CzURm7OpAA][DEF CON 23 - Robinson and Mitchell - Knocking my neighbors kids cruddy drone offline]] amazingly witty talk about security vulnerabilities of two types of drones, comedic timing of the presentation is super on point
- [[https://www.youtube.com/watch?v=ZWQ0591PAxM][How we fit an NES game into 40 Kilobytes]] absolutely fascinating video about space optimizations in development of a small NES game
- [[https://www.youtube.com/watch?v%3DJpaq0QkepgA][ey! Look for patterns]] finding shorthand patterns to identify things without going through huge hassles to confirm things saves lots of times
- [[https://nyaa.si/view/1097157][Pop Team Epic - 01 - entirely encoded inside subtitle file]] What the F*$k?, subtitle files can draw vector graphics so somebody encoded an episode of this show entirely via subtitle file, over top of a blank black screen video file
- [[https://www.youtube.com/watch?v=2XGYr9_BiEU][BREADSWORD - Satoshi Kon and why Love is All You need episode 1 - Perfect Blue]] "Tadokoro covets the image of Mima. Rumi covets Mima's image."
- [[https://www.youtube.com/watch?v%3D5oNB6tlSZ2A][Fighting in the Age of Loneliness]] Jon Bois x Felix Biederman five-part collab documentary about Mixed Martial Arts. Surprisingly moving, wonderfully directed. 


*** October 2018
**** Brief Updates
     - *Attended The Big House 8* got 97th place which is pretty solid for me; I can be so much better than I currently am and I have lots of footage to review. In general this low-pressure headspace I was in was very good and is worth experimenting with more. [[https://www.youtube.com/playlist?list%3DPLczW29iRM_QdoOL7Oy4bm0b6-BCkmSlCz][bracket matches]]
     - *Updated the iframe CSS on this website* Youtube videos / gfycats no longer look completely stupid, nor are they insanely vertically stretched on mobile.
     - *Began taking Creatine* been thinking about taking this since I’ve heard mixed things about its effect on cognition (mostly during sleep deprivation) but now that I’m lifting weights 3x/week I figured it was worth taking regularly. Hard to separate out what is from creatine and what is from just getting stronger, but the water retention effect was much stronger than I anticipated.
**** Goals for November
     - *Practice Coding*
     - *Make Things*
**** Things I've made
     - [[http://planetbanatt.net/articles/humantheorytas.html][STARS ALIGNED - A Human Theory TAS Combo Video]] Project I've been working on for a few months (maybe since June? I've had the idea for a very long time but I think June is when I started outlining the idea). Reception to this has been really positive and I'm very happy with all the kind words people have been sending my way :) Some related links are the [[https://www.youtube.com/watch?v%3DOGpB5d5nuPg][video]], the [[http://planetbanatt.net/articles/humantheorytas.html][annotated writeup]], the [[https://twitter.com/Ambisinister_/status/1051596459378917377][twitter thread]], and the [[https://www.reddit.com/r/SSBM/comments/9o6wv0/stars_aligned_a_human_theory_tas_combo_video/][Reddit Thread]] (Reached #1 on /r/ssbm)
     - [[http://planetbanatt.net/articles/celeste.html][Just Breathe. Celeste is Game of the Decade]] long-form review of Celeste which touches upon most of my thoughts about the game. It's incredible and you should play it.
**** Things I've consumed
***** Games
      - [[https://www.deltarune.com/][deltarune - Chapter 1]] Very cute, and I think a surprisingly worthy followup to UNDERTALE so far. May or may not be part of a big writeup I'm planning, but my impressions after chapter 1 are: absolutely fire [[https://www.youtube.com/watch?v%3DeeXFCM1e-zM][OST]], overall somewhat less lovable characters but some [[https://twitter.com/Ambisinister_/status/1058158724290879493][gems]], the Suzy/Lance dynamic was hilarious and cute, the linear storytelling is a big departure and makes me think we're in for a ride (and probably a dark one), it's free??, the ending caught me entirely off guard, can't wait for chapter 2.
***** Video
      - [[https://www.youtube.com/watch?v%3DXwCK1z3wT8g][Mike Dawes - Somebody That I Used To Know]] I love this sort of multi-layered solo performances, reminds me of [[https://www.youtube.com/watch?v%3D_DfQC5qHhbo][John Mayer's Live Solo of Neon]] which might be my favorite solo performance ever
      - [[https://www.youtube.com/watch?v%3Dc2zIto55QlQ][JENKEM - Matt Tomasello AKA "Rodney Mullen on Bath Salts"]] Shoestring engineering meets Skateboarding Part. One of the most creative videos I've seen in a long time!
      - [[https://www.youtube.com/watch?v%3DKFNxJVTJleE][How Gamers Killed Ultima Online's Virtual Ecology]] Richard Garriott explains how his team programmed a whole system of ecology in Ultima Online so that the AI Creatures would interact with each other, and how the playerbase just killed every killable creature possible, completely destroying this feature altogether. Humans love destruction!
      - [[https://www.youtube.com/watch?v%3DirNoHfnLXRM][Pain Elemental Reveals the Last Official Secret of Doom 2]] An RTA Viable strategy to obtain a Secret in Doom 2 previously thought to be unattainable without cheats was discovered, completely invalidating every 100% Speedrun of the game over 2 decades after the game came out.
      - [[https://www.youtube.com/watch?v%3DD3AXIGmBfa8][Sparkee - Something About Us]] Funky cover of this song
      - [[https://www.youtube.com/watch?v%3DGTcM7ydgAwo][Cigarettes, Slots, and Other Things that Aren't Addictive]] Good video essay on the problem of corporate-funded research
      - [[https://www.youtube.com/watch?v%3Dr_rSQ5lDltQ][Boiling a Live Lobster in Hennessy by Chef Henny]] It's been a long time since I've seen a video that subverted my expectations so many times in a row.
      - [[https://www.youtube.com/watch?v%3DLNidsMesxSE][Animation Bootcamp: An Indie Approach to Procedural Animation]] David Rosen of Wolfire Game talks about his procedural animation techniques for Overgrowth. I'm really impressed by how much of this task can be abstracted away to programming.
***** Books
      - [[https://bignokh.com/][The Book of Melee]] I was an alpha reader for Anokh Palakurthi's Melee upcoming 2019 nonfiction book chronicling the history of SSBM. Think it's likely to be an enjoyable read for people who follow the scene, since there's a number of really interesting little anecdotes you probably didn't know about the game. 


*** September 2018
**** Goals for October
     - *Go to The Big House 8* just have a good time, stop worrying so much about how you perform when you can't even go to locals.
     - *Lift weights again* need to get back on a beginner program and get back to where I was before. I'm not exactly untrained (I do still climb) but I'm not where I used to be and I realized I got complacent with my health goals after I lost the weight I gained second half of school.
     - *Read books* I'd like to finish Psychology Applied to Modern Life at minimum, preferably more.
     - *Finish 2-3 of my mostly finished projects* this includes my Celeste longform review, the secret video project, and the stamina bracket research, among other stray ones.
**** Things I've Made
     - [[https://twitter.com/Ambisinister_/status/1041095080881389568][Powershot shenanigans]] little TAS clip about charge shot bouncing off of shield and getting powershielded from a weird angle, seemed pretty popular!
**** Things I've Consumed
     - [[https://www.youtube.com/watch?v%3DLfX2kS7WkA0][Kirby Air Ride City Trial TAS - Achivements]] This is the mode I and everyone I know played most when this game came out so I'm glad somebody made a good TAS of it instead of focusing on the courses instead.
     - [[https://www.youtube.com/watch?v%3Ds6rQ1UHKFV8][Bottle cap pitching]] This is so cool and it looks really fun actually! I sort of want to learn to do it but I'd need two other people to be convinced to practice it which seems unlikely.
     - [[https://www.youtube.com/watch?v%3DYNrL8CQbECw][Poker Players Replay Their Most Memorable Hands | The New Yorker]] I love listening to Poker players talk about Poker because there's just so much *thought* involved. My favorite by far was Jamie Kerstetter's hand which just filled me with uncontrollable anxiety listening to it.
     - *Celeste* the best game I've played in a long time; a full review is coming soon.


*** August 2018
**** Brief Updates
     - *Went to Evo 2018* I played pretty terrible at the tournament, which was very disappointing, but seeing my friends for the first time in almost a year was so exciting and I left with a decent idea of what I want to work on. [[https://twitter.com/Ambisinister_/status/1026513823052705792][Reflection tweets]]
     - *Went to Shine 2018* Didn't do too hot in bracket but had some decent [[https://www.youtube.com/watch?v%3DPGGGjR7rk_g&list%3DPLczW29iRM_QcE7pINKBdnApPAJFUfszqB][Money Matches]] despite not being particularly winning. 
     - *Bouldering* I climbed a bunch of V3s at Origin Climbing Gym in Las Vegas during Evo, but I'm pretty confident that the grades at that gym were pretty soft. Climbed a number of V3s at assorted gyms but no overhangs.
**** Goals for September
     - *Reorient*
**** Things I've Made
***** Videos
      - [[https://www.youtube.com/watch?v%3DBQ5tkDACqoU][Shine 2018 Clips]] not technically put out this month but recorded this month, just some funny stray clips from recorded sets at this tournament.
**** Things I've Consumed
***** Web
      - [[https://blog.openai.com/openai-five-benchmark/][OpenAI Dota 2 Benchmark Results]] I was skeptical that openAI would be able to defeat strong human opponents but they proved me wrong; they mostly lost to professional teams but were able to soundly win against really strong human opponents which is super exciting!
      - [[https://www.youtube.com/watch?v=oJ9H0INZ2_s][Short Film - Graeme Obree, Athlete or Genius?]] former world record holder in time trial cycling famous for building handlebars out of washing machine scrap metal to contort his body into more aerodynamic positions, twice changing the regulations for which bikes are legal in competitive cycling - they get him in a wind tunnel to test it and his body positions save roughly 60 and 10 watts compared to the standard position, which shows a lot about how important aerodynamics are to the sport.
      - [[https://www.researchgate.net/profile/Christopher_Mesagno/publication/233936536_xx2011_Mesagno_et_al_2011_Choking/data/0912f50d24db974236000000/xx2011-Mesagno-et-al-2011-Choking.pdf][Self-Presentation Origins of Choking: Evidence From Separate Pressure Manipulations]] cool paper on choking under pressure, highly linked towards concerns of self-presentation
      - [[https://www.reddit.com/r/SSBM/comments/97tqva/top_1000_melee_win_percentage_leaderboards/?st%3DJKX17V6I&sh%3D5af12945][MyHandsHurt]] another person did a look at a bunch of smash.gg data and came to similarly weak conclusions about things as I did in Making Sense of Melee, most notably the rise of Hanky Panky
      - [[https://www.youtube.com/watch?v%3DPCBTZh41Ris&feature%3Dyoutu.be&t%3D2m13s][Everybody Dance Now]] and [[https://arxiv.org/pdf/1808.07371.pdf][Paper]] holy shittttt GANS ARE SO COOL
      - [[https://www.youtube.com/watch?v%3DA8zWWp0akUU][What if English Were Phonetically Consistent?]] cute video
      - [[https://www.youtube.com/watch?v%3Dec7Iwlo2ets][Fox vs Ice Climbers Analysis: Fiction vs ARMY at Nimbus 29]] lots of useful information about this matchup
      - [[https://github.com/kotritrona/osumapper][osumapper - an automatic beatmap generator using Tensorflow / Deep Learning]] this was one of the ideas in my ideas document so I'm both sad that somebody beat me to it and happy that my idea was validated as an interesting one.


*** July 2018
**** Brief Updates
- *Sent a V3 Problem* Didn't get a video recording of it, but I sent an interesting slab problem at The Gravity Vault in Randor, PA. In my send I got stuck on the last move for maybe three full minutes before getting past it with a weird coordination mantle + pistol squat move, which I felt really good about even though it suggests my move into the last move was probably not super optimal.
- *Sent another, different V3 Problem* Video [[https://www.youtube.com/watch?v%3Dzvj-iehyW9g][here]], another relatively easy problem which I abused my height to make easier. I want to send this cleaner (as I did with that [[https://www.youtube.com/watch?v%3D4rmQWE4jCbY][super weird teal V2]] that everyone at my gym hates, myself included). I really liked the mini cut-loose move near the end but I think this climb would be easier with better footwork especially after the third hand move (flag is unnecessary). I think a footswap after the fifth hand move -> move right foot to hold right next to it skips the need for cutting loose, but I could be misunderstanding how good the holds are from that position from this video. Overall I think definitely a relatively easy v3 which I think is appropriate for what I consider my current level at climbing (V2+/V3-)
- *Practiced a bunch for Evo 2018* I'm very excited for this event and I think I'm in pretty good form for it - I'm unsure if I'll do well or not but I'm looking forward to playing a lot of great melee with strong players and having a good time in Las Vegas.

**** Goals for August
- *Play Well at Evo 2018, get hours in against new, strong players*
- *Send two more V3s, one of which must be a roof/overhang* 
- *Cut weight back down to 150-153 range*
- *Resume work on programming work*
- *Begin work on secret SSBM video project*

**** Things I've Made
- [[http://www.planetbanatt.net/articles/anki.html][Notes on Spaced Repetition]] Some running notes for my anki card usage, which I will probably update as I get new useful thoughts on using it
- [[http://www.planetbanatt.net/articles/omron.html][How Variable are Omron Scales?]] I got back up to 160 so I ran some measurements on my bodyfat / muscle percentages and they were much better than the last time I was this weight, which is very exciting and motivating
- [[https://twitter.com/ThePGstats/status/1014931922299088898][MPGR Summer Top 50 Ballot]] After a bunch of discussion, PGR ended up sticking with the ballot system instead of using the algorithmic ranking. I was a panelist this season, and spent a good amount of time making this ballot (which will remain hidden to avoid external pressure influencing my vote). 
- [[https://www.twitch.tv/videos/289261916][MPGR Roundtable Part 2: #40-31]] I appear as a guest on Panda Global's Twitch show discussing the summerrank top 50, along with Aiden, Appel, Gimmedatwheat, Edwinbudding, and PracticalTAS.

**** Things I've Consumed
***** Web
- [[https://www.broadinstitute.org/what-broad/areas-focus/project-spotlight/questions-and-answers-about-crispr][What is CRISPR?]] Research on gene editing, a bit out of my element but very interesting
- [[http://bactra.org/notebooks/][Notebooks - Bactra.org]] A fine addition to my "Visions for this website in 30 years" list, along with [[http://www.gwern.net/][gwern.net]]. This is a page of notebooks written by [[https://en.wikipedia.org/wiki/Cosma_Shalizi][Cosma Shalizi]], a professor of Statistics at CMU. There's so much info here! From this alone I'll have a list of books to read that will never end.

***** Video
- [[https://www.youtube.com/watch?v%3DQkXeMoBPSDk][Who Is America? (2018) | Official Clip Ep 2]] I actually just can't believe this video
- [[https://www.youtube.com/watch?v=mcNe1I8X2fg][Secrets to easiest and most athletic BULKING DIET - Eric Bugenhagen]] This dude passionately yelling about food for 15 minutes is worth watching even if you never plan on bulking ever. "If you can't bulk with that direction I've just given you...... you gotta get off my channel, you just don't have the mindset"
- [[https://www.youtube.com/watch?v=absNLWpjnqc][A Bug's Life is LITERALLY Seven Samurai - BREADSWORD]] Breadsword makes consistent incredible content - he's sort of like "SoulBroNo3 meets Nerdwriter, if Nerdwriter made content with substance". I thought his [[https://www.youtube.com/watch?v%3Db9sycdSkngA][Treasure Planet]] video was great, and this is his most recent work which I found to be impressively novel and interesting. Definitely worth a watch. 
- [[https://www.youtube.com/watch?v=nwQmwT1ULMU&feature=youtu.be][The Mystery of the Mole Playing Rough]] cute video explaining the possible reasons for a bizarre enemy placement at a specific spot in Earthbound, exploring a flag in memory set in specific situations - author infers that it is a deliberate decision, which is a hilarious hack if it's true.

***** Books
- [[https://www.goodreads.com/review/show/2300849954?book_show_action=false][Proofs and Refutations: The Logic of Mathematical Discovery]] The Republic meets Philosophy of History of Mathematics. Full thoughts in the link.
- [[https://www.goodreads.com/review/show/2476532471][The Rock Warrior's Way: Mental Training for Climbers]] Decent book about mental game in rock climbing, weirdly zen influenced book but honestly not that bad, review in link.


*** June 2018 
**** Goals for July
- *Send another V3 Problem* I have one that I'm working on but I am worried they will take it down before I get the last move, so if I can't get it by the end of the month then I'll need to find something else
- *Practice an unreasonable amount for Evo 2018* It's probably because I can no longer take Melee for granted and play it every day, but I haven't felt this motivated for a tournament in a very long time. I really want to perform well so I've been practicing a lot and I don't want to let this motivation fizzle out before the event.
- *Work on projects when you have time* I have a lot of things in the works, among which the things I have not finished from months ago, but my priorities have temporarily shifted for now so I think if I finish any real projects in the next month I'll view it as a bonus rather than an explicit goal.
**** Things I have Made
- [[http://planetbanatt.net][Overhauled personal website]] I now generate this entire website from emacs org files; going back and transforming all my html documents to org files was sort of a pain but luckily with pandoc it didn't take longer than an afternoon - the rough part was wrangling with the org html export, which I eventually managed to nail down. It looks cool now! Still some work to be done but not bad.
- [[https://www.youtube.com/watch?v=hsdz2mTnhfM][V3 Boulder Problem]] interesting mantle -> mantle thing going on in this problem; it feels a little easy for a V3 but I'm not complaining since it let me meet my goal for this month! I've now completed every V2 problem in the gym so I'm currently focusing on climbing them cleanly / V3 problems / waiting for new problems
- [[https://www.youtube.com/watch?v%3DYAW1Edfy290][V2 Slab Problem]] really cool problem at a gym I don't usually go to
- [[https://twitter.com/Ambisinister_/status/1013181502375563264][Fountain of Dreams is Cool Now]] stupid movement idea I came up with on this stage

**** Things I have Consumed
- [[https://rockclimberstrainingmanual.com/tools-for-rock-climbing-training/the-making-of-a-rock-prodigy/][Tools for Rock Climbing Training: The Making of a 'Rockprodigy']] a lot of really great quotes in here, I'm starting to get really motivated for improvement in climbing and melee so I've been spending a lot less time on projects and a lot more time on practice.
- [[https://www.youtube.com/watch?v%3DVkFSVBL4AI8][Ocarina of Time glitch exhibition]] 2 hour presentation by ZFG of OoT glitches that are not useful in speedruns. I enjoyed it a lot!
- [[https://www.youtube.com/watch?v%3DoySLq4y-c8M][Sub Float - Quetzalcoatl]] Melee's preimere Peach Frame Data person documents a setup for floating lower than ground float height, allowing for +4 nairs. Not super useful since setup burns your doublejump making it quite dangerous, but almost baffling that the game went this long without anyone discovering this until now.
- [[https://www.youtube.com/watch?v%3DY99Wj-NStok][Choco Mountain: The History of Mario Kart 64's Most Infamous Track]] w e a t h e r t e n k o


*** May 2018
**** Goals for June
- Send a v3 boulder problem
- Make big changes to website formatting using emacs HTML export
- Complete posts I keep postponing work on
- Make it very straightforward to export new things to this site now that everything is centralized in emacs (!!)
**** Things I have Made
- [[https://www.youtube.com/watch?v=2sSQUKU-UnQ][Bombs over Battlefield]] Items combo video feat R2DLiu, Vickram, lpac, and myself, super funny 
- [[https://www.youtube.com/watch?v=5gKaeUDHNzU][Melee Stats Podcast - Episode 9]] I'm in this episode

**** Things I have Consumed
- [[https://fivethirtyeight.com/features/i-faced-off-against-the-worlds-best-chess-player-you-will-totally-believe-what-happened-next/][I Faced Off Against The World’s Best Chess Player. You Will Totally Believe What Happened Next.]] Not exactly a groundbreaking experience if you are a chess player, but it was really cool to see a levelheaded outsider brush up against the chess community and say reasonable things (unlike another article which is derisively hyperlinked in this one)
- [[https://superuser.com/questions/67170/how-do-i-complete-file-paths-in-emacs][find paths in emacs]] ugh
- [[https://orgmode.org/worg/org-contrib/babel/languages/ob-doc-python.html][python inline in org mode]] sick



*** April 2018
**** Goals for May
     - *Turn 23*
     - *Complete Bracket Stamina post* (this has gone on for too long as it is, since I keep encountering cool things abour it, and I made less progress than I would've liked on it despite working on it for ~20ish hours this month, but a lot of that is due to the fact that I am learning emacs through this project; I think I'm mostly completed with interesting things to encounter so I expect to be completed by mid may)
     - *Become very comfortable with emacs*; a friend of mine showed me his emacs setup and I realized that I had virtually the same workflow except strewn across 15 different programs and within two weeks of using it I am back/surpassing to my old productivity speed despite regularly pausing to remember how to perform the "copy" command. Fully expect to sink 300+ hours into configuring this program within the next year but as it stands I am already hooked on it. 
     - *Begin working on next coding project* surprise for now.
     - *Complete some stray writing projects*
**** Things I have Made

***** Videos
      - [[https://www.youtube.com/watch?v%3Dlkz70KroQsU][Box Practical Tech]] A short demo of niche tech skill possible on box controllers with modifiers
      - [[https://www.youtube.com/watch?v%3D9eRnWOFI7gE][Melee Stats Podcast - Episode 1]] I talk about how PAL is bad in this episode
      - [[https://www.youtube.com/watch?v%3DUCINugqRZmQ][Melee Stats Podcast - Episode 3]] I talk about box controllers in this episode, MSPR25 
      - [[https://www.youtube.com/watch?v%3DLS5wuGOlLl0][Melee Stats Podcast - Episode 5]] We talk about summit, I wear a tinfoil hat
**** Things I have Consumed
***** Articles
      - [[http://r2dliu.com/articles/ledgedash.html][On Ledgedashing and PODE (R2Dliu)]] PODE lets you press the perfect ledgedash angle and get a ledgedrop because it pseudo-buffers the horizontal input so you get one frame of vertical down movement first.
      - [[http://docs.python-guide.org/en/latest/writing/gotchas/][Python Gotchas - Default Values]] I started trying to use these in my projects without knowing why they worked and it caused me problems
***** References
      - [[https://www.gnu.org/software/emacs/tour/][Emacs tour]] useful introduction
      - [[https://orgmode.org/guide/][Org Mode guide]] useful document in general
***** Videos
      - [[https://www.youtube.com/watch?v%3DPTmhBRo-91s&feature%3Dyoutu.be][Twilight Princess JotWad TAS in 4:33.54{Post Commentary}]] A short 4 minute TAS with rhyming commentary and a punchline that had me rolling
      - [[https://www.youtube.com/watch?v%3DSzA2YODtgK4][Getting Started with Org Mode]] The second person I've watched use this software, which convinced me it was utter wizardry
      - [[https://www.youtube.com/watch?v%3DAmgkSdhK4K8][Who cares about topology? (Inscribed rectangle problem)]] Was introduced to 3Blue1Brown recently and man what a great channel
      - [[https://www.youtube.com/watch?v%3DspUNpyF58BY][But what is the Fourier Transform? A visual introduction.]] More 3Blue1Brown
      - [[https://www.youtube.com/watch?v%3DZsO4w7hTdWE][WAX - RED]] We doing shit that people do in only dreams  
      - [[https://www.youtube.com/watch?v=Wsf6tkST7bI][Lynn Hill at Hueco Tanks - Patagonia Ambassador goes Bouldering in Texas]] I've been really into bouldering recently and I think this video is a good show of why
      - [[https://www.99boulders.com/bouldering-footwork-fundamentals][Bouldering Footwork Fundamentals - 99boulders]] useful reference mostly for parts of climbing shoe




*** March 2018
    :PROPERTIES:
    :CUSTOM_ID: march
    :END:

**** Goals for April
    :PROPERTIES:
    :CUSTOM_ID: goalsforapril
    :END:

-  Continue learning math, learn some beginner Chinese
-  SSBM: study 30 hours of videos, implement dash out of crouch,
   continue working on aerial drift
-  Complete bracket project (which has proven to be much more
   interesting than I anticipated) and flashcards writeup
-  Learn to use vim, get comfortable with it by playing some
   [[http://crawl.develz.org/wordpress/][DCSS]] (lol)

**** Updates
    :PROPERTIES:
    :CUSTOM_ID: updates
    :END:

-  Downloaded [[http://www.wonderapps.se/atracker/][Atracker]] which I
   plan on using to make more quantifiable monthly goals. Measurement
   defeats all.
-  Did a brief cut and got back down to ~150 from 155

**** Things I've made
     :PROPERTIES:
     :CUSTOM_ID: thingsivemade
     :END:

***** Writing
     :PROPERTIES:
     :CUSTOM_ID: writing
     :END:

[[http://planetbanatt.net/projects.html][Projects]] I updated my
Projects page to summarize the independent work I've completed, since
Google analytics showed me people clicked that often after reading
Making Sense of Melee. It's only my biggest / coolest projects, and at
the moment the prose form is a little wordy but it's better than what I
had before. I'll probably Reupdate it very soon with images but this
should be a better placeholder

[[http://planetbanatt.net/resume.pdf][Resume]] I updated my resume

**** Things I've consumed
     :PROPERTIES:
     :CUSTOM_ID: thingsiveconsumed
     :END:

***** Books
     :PROPERTIES:
     :CUSTOM_ID: books
     :END:

[[http://integrateddaniel.info/book/][Mastering the Core Teachings of
the Buddha]] Weird, but okay book. Full thoughts
[[https://www.goodreads.com/review/show/2323153658?book_show_action=false][here]].

***** Articles
     :PROPERTIES:
     :CUSTOM_ID: articles
     :END:

[[https://www.google.com/amp/s/tim.blog/2012/12/11/how-to-play-the-guitar/amp/][How to Finally Play the Guitar: 80/20 Guitar and Minimalist Music]]

***** Videos
     :PROPERTIES:
     :CUSTOM_ID: videos
     :END:

[[https://www.youtube.com/watch?v=1298ltL8_SA][she - By Your Side]]
Pictures and sounds, pixels turn into lines

[[https://www.youtube.com/watch?v%3DIndm8KGXaEU][{TAS} SSBM (Melee) Fox 1P Mode All-Star {Very Hard, No Damage Clear}]] This video is a literal
masterpiece and I spent something like a full hour watching parts of it
frame by frame several times

[[https://www.youtube.com/watch?v=unGoHAX_gmk][GUNSHIP - Fly For Your
Life]] Interesting what / how much the soundtrack adds to the original
animation [[https://www.youtube.com/watch?v=AjXr9Nj5ZbI][Paths of Hate]]

[[https://www.youtube.com/watch?v=4a1TUszkMfI][The NCAA tournament is a
loser machine | Chart Party]] Singlehandedly delayed my bracket project
a few weeks - I love Jon Bois

--------------


*** February 2018
    :PROPERTIES:
    :CUSTOM_ID: february
    :END:

**** Goals for March
    :PROPERTIES:
    :CUSTOM_ID: goalsformarch
    :END:

-  Finish Bracket Stamina project and Spaced repetition post; finish
   reading Proofs and Refutations; make anki cards on US History; Start
   working through Linear Algebra Done Right and
   [[http://www.math.pku.edu.cn/teachers/anjp/textbook.pdf][this]].
-  SSBM: continue working on implementing aerial drift, specifically out
   of short hop; work on making platform punishes against fastfallers
   more consistent
-  Practice some substantial amount of time this month learning to play
   guitar, figure out some way to track hours practiced (for this and
   for other things)
-  Maintain your reading habits but focus primarily on math / guitar /
   SSBM / writing

**** Updates
    :PROPERTIES:
    :CUSTOM_ID: updates
    :END:

Health

-  finished a two month trial period for
   [[https://examine.com/supplements/bacopa-monnieri/][Bacopa
   Monnieri]]. Ended up observing a rise in correct answers for new +
   young anki cards of about 8%, and no change in mature cards. I didn't
   do any blinding, and would probably have to revisit this if I wanted
   to explore it deeply in any capacity. I don't really feel like bacopa
   gave me anything super valuable given the magnitude of the effect, so
   I've discontinued taking it (although I might consider taking it
   again if I ever decide to become a student again). Funny to think
   about how effectively you can replace the use of short term memory
   with good external capturing like anki or Evernote.

SSBM

-  spent virtually my entire month practicing backwards aerial drift.
   Entered a tournament and placed pretty well despite feeling pretty
   off tech-skill wise. Feel good about practice paying off somewhat for
   me.

Misc

-  Decided against adding an RSS feed, since adding one for a static
   website is more trouble than it's worth and I have a far too small
   readership that would ever use it.
-  Met most of my goals from last month (only finished 2 books but did a
   lot of reading), still need some calibration but enough of my time
   went towards practicing melee that I had a slightly below average
   level of productivity

**** Stuff I've made
     :PROPERTIES:
     :CUSTOM_ID: stuffivemade
     :END:

***** Articles
     :PROPERTIES:
     :CUSTOM_ID: articles
     :END:

[[http://www.planetbanatt.net/articles/boredom.html][A Tale of Two
Boredoms]] A bit more blogposty and philosophical than my usual writing,
but I felt I needed to flesh out my ideas on this topic a bit more
properly. /"Once you saw and named the problems, you couldn't stop
seeing them, it just got more annoying every day."/

***** Videos
     :PROPERTIES:
     :CUSTOM_ID: videos
     :END:

[[https://www.youtube.com/watch?v=HlsDiITk0YM][Shinelock Punishes]]
Somebody asked me to make a video on this and I've been meaning to make
a video anyways so I threw something together.

[[https://twitter.com/Ambisinister_/status/969056550009655296][More fun
Peach TAS things]] ideas mostly courtesy of lpac / r2dliu

**** Stuff I've Consumed
     :PROPERTIES:
     :CUSTOM_ID: stuffiveconsumed
     :END:

***** Books
     :PROPERTIES:
     :CUSTOM_ID: books
     :END:

[[https://drive.google.com/file/d/1gnZQn0EJGI3c1jdxUXulcLH8bb-oQ1ls/view][Rationality:
Abridged]] Summary by Quaerendo of Eliezer Yudkowsky's "Rationality:
From AI to Zombies", which desperately needed a summary. Very cool and
lots of good ideas. Full thoughts
[[https://www.goodreads.com/review/show/2246451089?book_show_action=true][Here]]

[[https://www.goodreads.com/book/show/18937.In_the_Beginning_Was_the_Command_Line][In
the Beginning... Was the Command Line]] Very well written, slightly
elitist history of operating systems. Fun analogies. Full thoughts
[[https://www.goodreads.com/review/show/1963072847?book_show_action=false&from_review_page=1][Here]]

****** Articles
      :PROPERTIES:
      :CUSTOM_ID: articles-1
      :END:

[[http://oracleselixir.com/2015/10/egr-and-mlr-new-team-ratings/][EGR
AND MLR: NEW TEAM RATINGS]] Shown to me by Shi Deng of Big Blue esports.
A pretty interesting look at how different teams perform at different
stages of a match in league of legends; sadly I'm not much of a league
player so the nuances of choosing 15 minutes as a threshold / the
importance of dragons vs gold / etc are lost on me, but the analysis
strategy is pretty interesting and I enjoyed reading it. (Also reminded
me that I need to learn to implement k-fold cross validation)

[[https://arxiv.org/pdf/1708.05866.pdf][A Brief Survey of Deep
Reinforcement Learning]] Pretty cool survey paper. Got a kick out of "We
begin our survey of value-function-based DRL algorithms with the DQN, pictured in Figure 5, which achieved scores across a wide range of
classic Atari 2600 video games that were comparable to that of a
professional video games tester." (what does this even mean?)

[[https://www.gwern.net/docs/psychology/2016-levitt.pdf][HEADS OR TAILS:
THE IMPACT OF A COIN TOSS ON MAJOR LIFE DECISIONS AND SUBSEQUENT
HAPPINESS]] People who make changes report being much happier 2-6 months
later, even when the choice to make that decision was completely random.
"The results of this paper suggest that people may be excessively
cautious when facing life changing choices".

[[http://web.archive.org/web/20091026234156/http://geocities.com/currintrading/][Currin
Trading - Ambition, Deception, Honor, Redemption: The story of the
biggest heist in Eve's history]] Half chilling, half fascinating - Eve
Online scammer details how he ran a ponzi scheme disguised as a
fraudulent trading corporation in-game, eventually leading to him making
away with 30 billion isk (A few thousand dollars). There's a lot of
really amusing anecdotes in here (he claims he didn't sell the isk for
real money because he didn't want to break the terms of service, he
mentions the playerbase revolting after the moderators returned money
from a different scam, and that he had intended to return as much of it
as possible before being mistakenly banned and changing his mind upon
the reversal), and it reads like a wild criminal testimonial for someone
who knows he's not going to face any repercussions. In the end he blew
the whistle on another scammer, the EVE Interstellar Bank, a scam that
netted /that/ scammer 750 billion isk (~$80k USD).

"those who did not make specific requests, and instead asked open-ended
questions like "how can I trust you?" and "how do I know this is for
real?"--these were future investors. They were asking me to persuade
them. They wanted to believe."

"People who posted on the forums seemed to have a negative attitude
about everything. Rather than being a cross-section of the Eve populace,
the forums were populated by a group disparagingly known as "the forum
superstars"--people who spent all their time on the forums instead of
actually playing the game. Not only did they have a fame and influence
far out of proportion to their playing abilities, they were accused of
getting special treatment from the administrators of the Eve servers.
But it was their persistent scorn for anyone making anything new--and
their seeming inability to make their own positive contributions to the
game--that maintained the ordinary players' low regard for them."

"In the end, I decided that the only value in having stolen all of that
isk was not the isk itself, but the stealing of it. I wanted to see if I
could do the impossible, and I did it. The more I pondered the actual
value of isk, the more I saw that the only people who really valued it
were the ones who had earned it themselves. Despite Eve being a game,
they had put real work into it. Many of them had spent three years
shooting rocks and hauling modules around to earn that isk, and now it
would be gone."

"Only now did I appreciate just how insidious a scam could be. I had
thought the isk meant nothing to me. That it was just a means to an end,
a score to beat. But now I was willing to wreak devastation upon all of
my investors just to hold onto it. The scam had scammed me. It stole my
concern for others and replaced it with gluttony. I was disgusted. I
lied. I cheated people. I used people to help me scam their friends. I
was the cause of widespread bankruptcy. But the most damning thing of
all? I think I can live with it, and if I had it to do all over again, I
would. To my surprise, a guilty conscience was a small price to pay for
thirty billion isk. So I will learn to live with it, because I can live
with it."

***** Videos
     :PROPERTIES:
     :CUSTOM_ID: videos-1
     :END:

[[https://www.youtube.com/watch?v=v3O9vNi-dkA][Hear the Otherworldly
Sounds of Skating on Thin Ice | National Geographic]] Unsure if this is
more or less terrifying than that video of
[[https://www.youtube.com/watch?v=Phl82D57P58][Alex Hannold]]
free-soloing El Sendro Luminoso, but to be fair thin ice and heights are
my two greatest fears so perhaps it's just me.

[[https://www.youtube.com/watch?v=wwyznoWJDHI][Medieval Tune.
Hurdy-Gurdy With Organ]] Haunting

[[https://www.youtube.com/watch?v=jSxmZg-5Nxc][6LACK - Never Know]] If I
was waiting on you to tell me, then I would never know

--------------


*** January 2018
**** Goals for February
    :PROPERTIES:
    :CUSTOM_ID: goalsforfebruary
    :END:

-  SSBM: use solo practice time better, do a lot of set analysis /
   notetaking especially vs marth and sheik, work on implementing better
   control over aerial drift
-  Site: make site more mobile friendly, write scripts to manage a bunch
   of pages at once
-  Write one article, make one video, read four books

**** Updates
    :PROPERTIES:
    :CUSTOM_ID: updates
    :END:

-  Tentatively added Disqus comments to my writings - fully prepared to
   reevaluate this later and conclude it was a bad idea but I've been
   meaning to have a means of people sharing their ideas with me without
   needing to contact me on social media so this seems like a worthy try
-  also added google analytics, which I did not do before my statistics
   post and kicked myself for - it'll be useful to check what kind of
   audience I have for everything
-  Couldn't think of use for Raspberry Pi, Didn't get around to adding
   RSS, met all other goals for month and completed four books (!)

**** Stuff I've Made
     :PROPERTIES:
     :CUSTOM_ID: stuffivemade
     :END:

***** Writing
     :PROPERTIES:
     :CUSTOM_ID: writing
     :END:

[[http://planetbanatt.net/articles/ambistats.html][Making Sense of
Melee: The Illusion of Objective Ranks and the Real Impact of
Everything]] The culmination of my most recent long-term Melee Stats
project where I gathered tons of tournament sets and examined trends in
the data - I used this data for seeding and for my SSBMRank Ballot, and
this post details my further scrutinizing of the patterns within. The
post got a lot more attention than I was expecting! (It got something
like 56k views if my rough, then-poor analytics are to be trusted).
Somebody posted it to
[[https://news.ycombinator.com/item?id=16255910][Hacker News]] where it
ended up reaching #6, and it got tons of shares on
[[https://twitter.com/Ambisinister_/status/957830089110147072][Twitter]].
I was very pleased that people were so excited about it, and ended up in
a surreal daze after seeing
[[https://twitter.com/gwern/status/958125156525858816][Gwern]] make a
tweet about Claude Bloodgood the same day.

***** Images
     :PROPERTIES:
     :CUSTOM_ID: images
     :END:

[[https://www.reddit.com/r/SSBM/comments/7rbxeg/assessing_west_coast_bias_on_ssbmrank_and_why_it/][SSBMRank
Voting Distribution Visualization for KayBeats' "Assessing West Coast
Bias on SSBMRank and Why it Doesn't Exist"]] KayB is a Melee Stats
denizen, and he wrote a post exploring the supposed "West Coast Bias" in
the SSBMRank panel. I collabed with him by generating
[[https://imgur.com/a/jUfST][Violin Plots]] (boxplots with kernel
density plots overlayed on top of them) of the top 100 ballots,
graciously provided by Tafokints.

**** Stuff I've consumed
     :PROPERTIES:
     :CUSTOM_ID: stuffiveconsumed
     :END:

***** Papers
     :PROPERTIES:
     :CUSTOM_ID: papers
     :END:

[[http://academic.udayton.edu/JackBauer/Readings%20353/Bonanno%2004%20resilience.pdf][Loss,
Trauma, and Human Resilience - Have We Underestimated the Human Capacity
to Thrive After Extremely Aversive Events?]] A surprisingly optimistic
paper which suggests that most people are actually impressively
resilient after aversive events. Because so many people that show up to
clinicians after bad things happen are in need of clinicians to help
them, the prevailing view was that when bad things happen to people they
usually need time to grieve. However, the sample size was very
self-selecting here, and exploring more "normal" baselines suggest its
possible that on average people are pretty good about staying functional
through traumatic events.

[[http://www.nber.org/papers/w17639.pdf][SELECTING THE BEST? SPILLOVER
AND SHADOWS IN ELIMINATION TOURNAMENTS]]

[[https://www.hri.global/files/2011/07/13/Benowitz_-_Nicotine_Regulation.pdf][Establishing
a Nicotine Threshold for Addiction -- The Implications for Tobacco
Regulation]] I am not a smoker, but I was met with the idle question of
how many cigarettes one would have to smoke daily to become addicted.
The threshold seems to be around 5mg per day, which ends up being
something like 5 cigarettes.

***** Books
     :PROPERTIES:
     :CUSTOM_ID: books
     :END:

[[https://www.goodreads.com/book/show/18713259-worm?ac=1&from_search=true][Worm]]
by wildbow Great min/maxing fantasy-scifi story, full thoughts
[[https://www.goodreads.com/review/show/2054020916?book_show_action=false&from_review_page=1][here]].

[[https://www.goodreads.com/book/show/36595101-fire-and-fury][Fire and
Fury]] Likely a little exaggerated for effect, but a truly wild hit
piece that reads more like fiction than reality, full thoughts
[[https://www.goodreads.com/review/show/2246424359][here]]

[[https://www.goodreads.com/book/show/24724602-flash-boys][Flash Boys: A
Wall Street Revolt]] Cool book that I should have read a lot sooner and
one I'd immediately recommend to someone that wants to know about how my
current field works - full thoughts
[[https://www.goodreads.com/review/show/2277393546][here]]

[[https://www.goodreads.com/book/show/11297.Norwegian_Wood][Norwegian
Wood]] This book was extremely painful to read and made me sad for three
days, would recommend. Full thoughts
[[https://www.goodreads.com/review/show/2279855880?book_show_action=false][here]]

***** Media
     :PROPERTIES:
     :CUSTOM_ID: media
     :END:

[[http://mangakakalot.com/manga/love_is_blind_fujimoto_tatsuki][Love is
Blind - Fujimoto Tatsuki]] amazingly funny oneshot

[[https://www.youtube.com/watch?v=O3eO646jjzQ][Professional Scrabble
Players Replay Their Greatest Moves | The New Yorker]]

[[https://www.youtube.com/watch?v=Z9e7K6Hx_rY][Rex Orange County -
Sunflower]]

--------------


** 2017
   :PROPERTIES:
   :CUSTOM_ID: section
   :END:

*** Year End 2017
    :PROPERTIES:
    :CUSTOM_ID: yearend2017
    :END:

**** Goals for January
    :PROPERTIES:
    :CUSTOM_ID: goalsforjanuary
    :END:

-  Build something interesting with the Raspberry Pi 3 kit I got for
   Christmas, use Amazon Gift Cards to buy assorted things if need be
-  I've made very good progress on my more recent melee stats project
   and expect to be finished very shortly - the only reason I could
   imagine it taking longer than end of January is incorporation of top
   100 data for further analysis
-  learn a bunch of slow cooker recipes
-  Work on the infrastructure of this website - Maybe add Disqus
   comments, an RSS feed, make it slightly nicer looking

**** Stuff I've Made
     :PROPERTIES:
     :CUSTOM_ID: stuffivemade
     :END:

***** Writing
     :PROPERTIES:
     :CUSTOM_ID: writing
     :END:

[[http://planetbanatt.net/articles/360view.html][/Seeing Everything: A
Visual Perception Experiment Proposal/]] Not really a /project/ per-se,
more like a "man, somebody should do this" idea that I've had for a
while that just won't really leave my head.

***** Videos
     :PROPERTIES:
     :CUSTOM_ID: videos
     :END:

[[https://youtu.be/1jp0Q2KWi-E][Downwait Instant Ledgegrab]] An attempt
to make my videos a bit more visually appealing without sacrificing the
content or the conciseness: I rarely feel that these sorts of demos
warrant more than a 60 second video and I would like my content to
remain highly valuable per unit time, but if I can put a bit of extra
effort into them and have them be more polished without sacrificing this
then I don't think there's any reason not to.

***** Images
     :PROPERTIES:
     :CUSTOM_ID: images
     :END:

[[https://twitter.com/Ambisinister_/status/939963464180752386][How Good
is Melee National Seeding?]] Melee Stats group does it better

**** Stuff I've Consumed
     :PROPERTIES:
     :CUSTOM_ID: stuffiveconsumed
     :END:

***** Articles
     :PROPERTIES:
     :CUSTOM_ID: articles
     :END:

[[https://arxiv.org/pdf/1712.01815.pdf][Mastering Chess and Shogi by
Self-Play with a General Reinforcement Learning Algorithm]] A wonderful
paper that appeals to my AI and Chess-playing selves - Deepmind plays
beautifully even with no input from humans whatsoever.

[[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3001541/][Cigarette
smoking: an underused tool in high-performance endurance training]] An
incredible, hilarious paper that I plan on linking people frequently in
the future - from the abstract: /"However, if research results are
selectively chosen, a review has the potential to create a convincing
argument for a faulty hypothesis. Improper correlation or extrapolation
of data can result in dangerously flawed conclusions. The following
paper seeks to illustrate this point, using existing research to argue
the hypothesis that cigarette smoking enhances endurance performance and
should be incorporated into high-level training programs."/

[[http://kadano.net/SSBM/inputlag/][Kadano on Input Lag]] Running Dan
Salvato's polling fix code on console improves input delay by a bit
below 12ms, as measured with an Oscilloscope. Overall a great read on
Input Lag in general.

[[http://bearlamp.com.au/how-i-accidentally-discovered-the-pill-to-enlightenment-but-i-wouldnt-recommend-it/][How
I accidentally discovered the pill to enlightenment but I wouldn't
recommend it.]] Cool writeup I got from a member of the ssc discord, a
cool narrative version of a similar project to my health notes.

***** Media
     :PROPERTIES:
     :CUSTOM_ID: media
     :END:

[[http://slatestarcodex.com/2015/06/02/and-i-show-you-how-deep-the-rabbit-hole-goes/][...And
I Show You How Deep The Rabbit Hole Goes]] I reread this and man do I
love it

[[http://unremediatedgender.space/2018/Jan/blame-me-for-trying/][Blame
Me For Trying]] Cool short scifi story loosely based on
[[https://en.wikipedia.org/wiki/ELIZA][ELIZA]], a classic NLP chatbot
that simulates a psychotherapist.

[[https://www.youtube.com/watch?v=9P8C6-XqaNs][Failing - A very
difficult piece for solo string bass]] Music as performance art,
examining the construct of difficulty and about the paradox of having a
goal of failure.

**** "Resolutions"
    :PROPERTIES:
    :CUSTOM_ID: resolutions
    :END:

I generally dislike "New Years Resolutions" but I think keeping myself
accountable for the things I want to accomplish over long periods of
time is pretty important. As 2018 is the first year I will be completely
operating without educational institutions to hand me goals (weird) I
feel it is more important to have a clear vision of my long-term goals.

-  Read 30 books
-  Write 15 longform posts on this website, not including links posts
-  Reach a point where creating a Patreon wouldn't be an embarrassing
   idea, create a Patreon, get at least three Patrons
-  become the fittest I have ever been

--------------

*** September 2017
    :PROPERTIES:
    :CUSTOM_ID: sept2017
    :END:

**** Goals for October
    :PROPERTIES:
    :CUSTOM_ID: goalsforoctober
    :END:

-  Move into an apartment, figure out general living / exercise / etc
   arrangements there
-  Figure out a good way to do rankings with the big SSBM dataset (~22k
   sets), write up more extensive analysis, mostly complete this project
-  Place well at The Big House 7, record a lot of sets for review later
-  Learn Keras / Deep Learning stuff and do a project with it
-  Complete reading GEB

**** Things I've Made
     :PROPERTIES:
     :CUSTOM_ID: thingsivemade
     :END:

***** Writing
     :PROPERTIES:
     :CUSTOM_ID: writing
     :END:

/[[http://planetbanatt.net/articles/potbonus.html][Do Pot Bonuses Affect
Entrant Numbers at Melee Tournaments?]]/ (short answer: no)

/[[http://planetbanatt.net/articles/random20xx.html][20XX 4.06 Savestate
Workflow in Dolphin]]/ Not a perfect solution but if I'm hoping if this
is written then somebody will improve upon it and it'll be amazing to
practice with.

***** Videos
     :PROPERTIES:
     :CUSTOM_ID: videos
     :END:

/[[https://www.youtube.com/watch?v=xD20oBJnAS8&feature=youtu.be][Understanding
Luigi's Ledgedashes]]/

/[[https://youtu.be/JCyHqiLimM4][Super Portable Recording Setup]]/ This
thing is amazing and I'm glad I bought it.

/[[https://www.youtube.com/watch?v=2BBE9I7genw][Tech You Should Already
Know - Spotdodge / Amsah Tech Option Select]]/ Habit I wanna pick up
during spotdodges, tested and verified idea I had a million years ago
working on my notes for the fox-sheik matchup.

***** Images
     :PROPERTIES:
     :CUSTOM_ID: images
     :END:

/[[https://twitter.com/ambisinister_/status/904469847794483203][Understanding
Fox Antiair Hitboxes]]/

/[[https://twitter.com/Ambisinister_/status/913580629996064768][The
Local is Dying]]/, in which I examine the attendance at SSBM local
tournaments and determine that attendance is roughly the same as 2016

**** Things I've Consumed
     :PROPERTIES:
     :CUSTOM_ID: thingsiveconsumed
     :END:

***** Interesting things I've committed to anki cards this month
     :PROPERTIES:
     :CUSTOM_ID: interestingthingsivecommittedtoankicardsthismonth
     :END:

-  Different types of cuts in cooking
-  [[https://docs.google.com/spreadsheets/d/1yIZuPIC5tCim159zb-ihQNTL88sOE2eMchTIz2wkt8Y/edit#gid=34872173][Aerial
   Advantage numbers for Melee]]
-  [[http://www.hsquizbowl.org/db/questionsets/747/][2014 Introductory
   Collaborative Collegiate Set, rounds 1-5]]
-  If I knew the answer somewhere, I'd add the fact before the one I
   knew. If I didn't know the answer, I'd make a more detailed card
   about it. For bonuses I'd just add it unless I was certain I didn't
   care enough to memorize it (usually opera or trash questions)
-  [[https://www.cdc.gov/ncbddd/hearingloss/parentsguide/download/fingerspelling.pdf][ASL
   Fingerspelling]]

***** Books
     :PROPERTIES:
     :CUSTOM_ID: books
     :END:

[[http://www.guidetojapanese.org/learn/grammar][Tae Kim's Guide to
Japanese Grammar]] feels like a pretty comprehensive collection of
grammar points in the Japanese language, and I suspect I will frequently
go back and read through this if I forget something or if I encounter a
grammatical structure that I am unfamiliar with. I really appreciated
the structure and despite it being a little wonky at first it made the
rest of the guide pretty simple to understand since everything made some
sense from a Japanese-speaking perspective rather than an
English-speaking one imposed upon the Japanese language. Gonna start
working through Genki I now that I've gotten through this book.

***** Video Games
     :PROPERTIES:
     :CUSTOM_ID: videogames
     :END:

[[http://store.steampowered.com/app/698780/agecheck][Doki Doki
Literature Club]] Dan Salvato's new studio put out this game this month,
and I played through it. The tl;dr on my thoughts is that this game
manages to be cliche in two genres and draws far too much inspiration
from creepypasta. Full thoughts [[./articles/ddlc.html][here]].

[[http://sm64hacks.com/hack.php?id=59][SM64: The Last Impact]] a fun
romhack that is technically interesting and has some cool ideas and fun
levels, but suffers enormously from difficulty curve irregularity / bugs
/ poor level design. I found myself frequently getting softlocked, dying
randomly due to weird level geometry problems, having issues with the
camera, etc, and I eventually made it a game to see how many stars I
could get by BLJing past walls instead of actually earning them. I had
fun with it, but I couldn't manage to 100% it because there were just
some stars that were so broken that I got too frustrated to continue
playing. It made me appreciate how relatively not broken the original
game was, and how important beta testing is for these sorts of games.

[[https://www.playbattlegrounds.com/main.pu][Playerunknown's
Battlegrounds]] A fun game to fool around with friends in, but not one I
think is particularly well-designed from an esports perspective.

***** Articles
     :PROPERTIES:
     :CUSTOM_ID: articles
     :END:

/[[https://www.wired.com/2017/08/the-hotel-hacker/][The Hotel Room
Hacker]]/ Crazy story

***** Papers
     :PROPERTIES:
     :CUSTOM_ID: papers
     :END:

/[[https://arxiv.org/pdf/1702.06230.pdf][Beating the World's Best at
Super Smash Brothers with Deep Reinforcement Learning]]/ I believe this
is a more updated version of the paper I mentioned last month, so I'm
putting it here.

/[[http://www.glicko.net/glicko/glicko2.pdf][Example of the Glicko-2
System]]/ I ran this on a database of 22k super smash brothers melee
tournament set results, after ELO gave me mediocre results. The results
were better than ELO but still not very good.

***** Videos
     :PROPERTIES:
     :CUSTOM_ID: videos-1
     :END:

/[[https://www.youtube.com/watch?v=Zpql4uegZao][Earth Wind & Fire,
September - Bass Clarinet Choir]]/

/[[https://www.youtube.com/watch?v=KmbRTgjn2VQ][Learn Modal Jazz in 12
minutes. (No kidding.)]]/ Man, I miss being really involved with music
like I was in high school - I might pick up a music theory textbook and
brush up on it.

/[[https://www.youtube.com/watch?v=PDAseJvCpvk][How to Learn Music
(Epistemology and Music in the Digital Age)]]/ I'm not crazy about
Malcolm Gladwell but this video I think is a really well-worded
depiction of learning skills in general. I've watched a bunch of Adam
Neely's videos and he strikes me as extremely well-read, I was impressed
by how interesting all of his videos were while still consistently being
about music each time.

/[[https://www.youtube.com/watch?v=4p9_GxicLlw][Legend of Zelda: Ocarina
of Time - All Dungeons, No Doors TAS]]/ Crazy

/[[https://www.youtube.com/watch?v=vmNh_Ney87Y][Matchup Breakdown - Fox
vs Luigi (Chillindude829)]]/ Watched this after playing a set at Shine
2017 against a luigi and realizing that I didn't have a firm
understanding of my goals in this matchup (shine doesn't lead to
anything, grab doesn't lead to anything, so what are you going for in
neutral against luigi? What's your gameplan? I ended up just going for
random hits and getting steamrolled). Takeaways: uptilt vs nairs, dash
attack is a common mixup situation (nair out jump out etc), usually
avoid midrange (close/far is good), Disjoints are good (uptilt, falling
upair). Being above luigi is very good. Empty drill into fullhop is
pretty good because you can punish grab attempts with falling upair.

/[[https://www.youtube.com/watch?v=-uO1XE2MSnc][A YouTube choir: the
history of the most viewed videos converted into sound]]/ Perfect blend
of Music, Math, Visualization, and Shitposting. I got a huge kick out of
the inclusion of "All I Want For Christmas Is You" which predictably
shot up every december and then didn't move for the rest of the year.

/[[https://www.youtube.com/watch?v=ChPO9yPOy8c]["Rewrite" Production
Vlog #6: Everything is Fucked Up]]/ This is one of those "Truth is
stranger than fiction" type of stories I struggle to wrap my head
around, and yet I actually believe. tl;dr these two are shooting a
documentary about a now-shut-down modded video game, and got in contact
with a reclusive developer "Magus" who moves into their apartment to
help them with the documentary. However, it turns out that the person
that claimed to be Magus was actually somebody impersonating Magus,
having done so for months and knowing intimate information that
"verified" their identity with other dev team members. Nobody knows who
this person was, or how they knew so much about Magus and the internal
details of the development team, and everybody is freaked out about it.

/[[https://www.youtube.com/watch?v=LeItHAxLg9w][Batman: The Dark Knight
Trilogy Cover - Pedrosaxo]]/ Guy plays a duet with himself, seems very
technically demanding. I don't play saxophone but what I'm vaguely sure
is going on here is he's using the same technique you use for circular
breathing in order to hum a note at the same time he produces a note on
his instrument, resulting in two notes being played. Very neat!

--------------

*** August 2017
    :PROPERTIES:
    :CUSTOM_ID: August2017
    :END:

**** Goals for September
    :PROPERTIES:
    :CUSTOM_ID: goals-for-september
    :END:

-  Finish Tae Kim Guide to Japanese (~75% complete) and move on to Genki
   I
-  Finish the books I'm currently reading, as well as GEB and the
   fast.ai MOOC
-  establish working demo of melee stats page, scrape at least 8000
   sets, learn enough webdev to get a working prototype complete by the
   end of the month
-  write draft for posts on spaced repetition, man vs AI publicity
   stunts, melee stats analysis
-  join a gym, begin resistance training, begin eating at a surplus
-  other potential project ideas: something with Keras (MP3 file -> osu
   map? Too much?), do pot bonuses boost attendance at melee
   tournaments?

**** Things I've made
     :PROPERTIES:
     :CUSTOM_ID: things-ive-made
     :END:

***** Writing:
     :PROPERTIES:
     :CUSTOM_ID: writing
     :END:

/[[./articles/health.html][Optimizing health with cronometer]]/ I hit my
weight goal, going to start resistance training next

/[[./articles/omron.html][How variable are Omron Scales]]/ Since I met
my weight goal I tested the variability of my scale a second time. If I
gain weight in a substantially lean way and get my old values for
bodyfat, I'll conclude that the scales results are useless. Otherwise,
I'll measure what it returns.

***** Videos:
     :PROPERTIES:
     :CUSTOM_ID: videos
     :END:

/[[https://www.youtube.com/watch?v=UhDw-Q6nv5Y&feature=youtu.be&a][Using
Fox Lifesaver with Shine Stalls]]/ Video made to explore using shine
stall w/ conserving doublejump, also correcting for the 20 frame tap
jump buffer which KJH lists as 4f in his video

/[[https://www.youtube.com/watch?v=Ug4RvHKBZGs&feature=youtu.be][Samus
Hammer Throw Glitch]]/ Video of a sort of obscure glitch with Samus in
1.00, it's one of my favorite glitches and doesn't have a tutorial
anywhere, so I made one.

/Peach Q-Drop Pressure/ [[[https://twitter.com/Ambisinister%253Cem%253E/status/894236993554714624][1]]] [[[https://twitter.com/Ambisinister/status/894301430693195776][2]]]

**** Links
     :PROPERTIES:
     :CUSTOM_ID: links
     :END:

***** Blogposts, Web
     :PROPERTIES:
     :CUSTOM_ID: blogposts-web
     :END:

/OpenAI Dota 2 AI/ [[https://blog.openai.com/dota-2/][{1}]] [[https://blog.openai.com/more-on-dota-2/][{2}]] Not good enough at dota
to make an accurate assessment. Compare to Vlad "Xpilot" Firoiu's
[[https://dspace.mit.edu/bitstream/handle/1721.1/108984/986497700-MIT.pdf?sequence=1][master's
thesis at MIT]] Philip the Falcon Ditto AI, which
[[https://www.youtube.com/watch?v=dXJUlqBsZtE][can beat good players]];
as well as [[https://www.youtube.com/watch?v=9qWHM8DNdr8][SmashBot]],
which uses a hardcoded goals hierarchy rather than learning it all via
deep reinforcement learning. These fall under what I call "Watson
Syndrome" where they are capable of winning because of their superior
"biology" rather than actually outplaying their opponents, and as such I
don't think these are particularly useful as training tools (I.e. A
"winning position" for the AI is not necessarily winning for a human, if
such a situation requires something like frame perfect reaction time,
and attempting to emulate its playstyle would likely be extremely
foolish, unlike with Deep Blue or AlphaGo. For games with a biological
element [Melee, Dota, Jeopardy] emulating realistic biology is important
before you can announce "triumph" over human players.)

/[[http://www.genetickanji.com/grade1.asp][Genetickanji - Kanji Grade
1]]/ I've been doing five of these each day and have gone through a
little over 100 this month - I specifically wanted something reasonably
structured by radical / Mnemonic but with actual readings (which RTK did
not have - I have a copy of it and I'm using it for kanji I'm having
trouble with but as a method by itself it seems pretty terrible). Some
of the suggestions for remembering things in genetickanji are bad / big
stretches, but overall it's nicely structured and not too big a
commitment to figure out.

/[[https://twitter.com/ambisinister_/status/903323311089885185][Bet on
UCF not being at any majors]]/ I bet $10 with @uconnsdoom that UCF is
not present at Big House 7, Summit, Genesis, CEO, or EVO.

***** Papers
     :PROPERTIES:
     :CUSTOM_ID: papers
     :END:

/[[https://makegirlsmoe.github.io/assets/pdf/technical_report.pdf][Create
Anime Characters With A.I.! (Jin et al 2017)]]/ amazing / hilarious /
surprisingly straightforward, particularly enjoyed the section on
generating release-date-specific images ("as you can see from figure
5... the more recent images are cuter and higher quality")

/[[https://www.ncbi.nlm.nih.gov/m/pubmed/28742910/][Clinicopathological
Evaluation of Chronic Traumatic Encephalopathy in Players of American
Football (Mez et al 2017)]]/ Football is a moral evil and inherently
dangerous (half kidding). A somewhat self-selecting sample, but the
effect size is so large that this could be considered a huge blow to the
idea that "football is safe enough for children".

/[[https://arxiv.org/ftp/arxiv/papers/1707/1707.06643.pdf][Predicting
Personality from Book Preferences with User-Generated Content Labels
(Annalyn et al 2017)]]/ A cool paper exploring differences in
personality among people who enjoy certain genres of books, using
user-submitted tags on goodreads and declared preferences on facebook.
The visualization in this paper is excellent, and although I don't think
the paper's conclusion is that powerful (correlation between a
preference + big 5 feels pretty unimportant) I think the methodology was
great.

***** Books / Audiobooks
     :PROPERTIES:
     :CUSTOM_ID: books-audiobooks
     :END:

/Berlitz Complete Japanese/ A good series of dialogues to introduce
basic Japanese grammar (I'm still very much a beginner but I imagine
this is all N5 level). The dialogues are charming enough to keep you
reasonably engaged - I found myself more amused than I ought to be
listening to Harrison-san's antics, which I think is a good thing for
this type of resource. The dialogues are completely in Japanese, which
is what I wanted, but things become confusing if you can't figure out
what words mean so this might be worth supplementing with another
textbook, a dictionary, or the workbook. There's some weirdness
(pronouncing wo particle actually as "wo" sometimes) but overall good to
listen to if you want to practice listening/speaking

/Introductory Statistics with R/ A book that I think is best suited
either with a teacher or with another, more traditional, statistics
textbook. Using R has proven very useful, but the book was heavy with
jargon that it did not explain properly, and I frequently felt lost
despite making flashcards and reading very carefully. Certain concepts
are vaguely explained or not explained at all, and you're expected to
have a minimum level of knowledge that I felt was inappropriate given
that it also explained really basic stuff like factorials. Overall a
useful book that added a good tool to my toolkit, but one that
frequently had me googling things for clarification.

***** Manga
     :PROPERTIES:
     :CUSTOM_ID: manga
     :END:

/[[https://en.wikipedia.org/wiki/Aria_(manga)][Aria]]/ Slow, relaxing,
with some basic scifi concepts, works better as a manga than an anime
due to pacing. Fits the genre of "utopia that isn't a utopia", everyone
just sort of lazily goes about their days and most of the story is
literally about being able to slow down and admire the scenery around
you (MC's entire personality type, as well as the job of the Primas).

/[[https://www.gwern.net/Aria%27s%20past,%20present,%20and%20future][Aria's
Past, Present, and Future (Gwern)]]/ Hilarious, I've always had a soft
spot for violating suspension of disbelief and then trying to explain it
away using crazy theories. Reminds me a lot of the
"[[http://matrix.wikia.com/wiki/Matrix_in_a_Matrix_theory][Matrix in a
Matrix]]" theory, where people plugged the ridiculous left-field plot
hole of Matrix Reloaded as evidence that, since Neo can use powers in
the "real world", it's likely not the real world - just another layer of
fabrication that Neo pulled his punches in because he didn't believe he
had powers in there. Probably false, but a fun way to engage with plot
holes!

***** Anime
     :PROPERTIES:
     :CUSTOM_ID: anime
     :END:

/Koe no Katachi (2016)/ - I think as good of a film adaptation as I
could have reasonably expected from condensing this rather long story
into a two hour film. Pacing issues that were not present in the manga,
parts felt extremely rushed due to cutting out some smaller arcs to make
time. Characters didn't have enough time to properly develop into
believable characters with the exception of the main character, again a
byproduct of lack of time. Where this film shines is sound direction, it
uses silence and white noise extremely well, which compliments the films
themes (hearing vs listening / blocking out the world / etc). The
animation is fantastic as well, Kyoto Animation delivers as you might
expect. Overall not quite as good as the manga adaptation, but not bad
by any means.

***** Videos
     :PROPERTIES:
     :CUSTOM_ID: videos-1
     :END:

/[[https://www.youtube.com/watch?v=ajM4vYCZMZk][Carolina Eyck - The
Ecstasy of Gold (Theremin & Voice Cover)]]/

/[[https://www.youtube.com/watch?v=oS_yNsDsbaQ][残酷な天使のテーゼ (A
Cruel Angel's Thesis) まるやまたつや (Guitar)]]/

/[[https://www.youtube.com/watch?v=npZqCT-Quzo][Speed Bag Memory
Lane-Netsky Punch Drum]]/

/[[https://www.youtube.com/watch?v=UARP2K-ufU8][KJH's Fox Privilege
Series: FOX LIFESAVER]]/

/[[https://www.youtube.com/watch?v=TE4eplsFSms][Learn to Read Korean in
5 Minutes (seriously)]]/ doesn't get all the letters in but a cool intro
to the ease of this alphabet, I made flashcards for Hangul via wikipedia
+ 15 easy useful phrases

/[[https://www.youtube.com/watch?v=lX44CAz-JhU][SIAMÉS - "The Wolf"]]/
Listened to this before Shine 2017, played pretty well

#+BEGIN_HTML
  </div>
#+END_HTML
