#+Title: TODO
* Planetbanatt.net TODO list

There are lots of things I still need to do for this website. 

** Writing TODOs

*** New Writing TODOs

- *Which Way Can Multiplayer Games Be Hard?*[fn:1]
- *"Good Taste" is a Euphemism for Understanding*
- *The Designer as Adversary in Arcade Games*
  - ITGMania vs DDR charting as case study
- *Arcades as Multi-Arm Bandit Problem Article*
- *Yu Yu Hakusho Dub Thoughts*[fn:2]
- *CRT Technology and Downstream Game Design*
- *The Internet is Mostly Freaks And Weirdos*

*** Editing TODOs

- Graduate /Games Are Media Ecosystems, Not Software/ to proper article
  - "low effort IP" section is probably too flippant

** Website TODOs

- *Hard Launch Blog* This needs every page to be re-exported due to the change in taskbar.
- *SSBMRank Portal*: Data stuff can probably be linked to from the recently refactored Melee tab.
- *Blog Support Scripts*
- *ITG Stamina Improvement Tracker* This pipeline needs to be made more efficient.

** System TODOs

- LLM agent loop-in
  - Overall still too much moving stuff around manually.
  - Maybe capture templates / etc
  - Maybe agent which assists me looking stuff up 
- Admin Dashboard
  - Some way to do simple tasks from my phone would be useful, but would require dashboard with authentication etc

** HOLD Hiatus TODOs

- *Riichi Mahjong as Spiritual Healing for Bad Luck* I need to revisit this when I have more time for actually grinding out hanchans again
- *Anime and Transhumanism Article* 
- *Youtube Channel scrape for vods viewer*: Losing access to liquipedia API torched this project a lot. Luckystats has a lot of the value from this project, and given that I have for now ~quit competing for career reasons I have diminished motivation

* Footnotes

[fn:2] Some intellectual property thoughts [[https://bsky.app/profile/ambisinister.planetbanatt.net/post/3mo35ukbumk2r][here]].

[fn:1] Based on random discord messages I sent:

My personal definition of games being easy/hard is A: how high the skill curve goes + B: how skilled the playerbase is + C: how path-agnostic the path from beginner to master is, given some amount of effort.

there's lots of games which are pretty much open-and-shut put effort in -> get skill out which requires much less forward thinking about how you plan on improving at it

likewise there are a bunch of these games which are like chess, which is very very easy to improve at but you basically need a lifetime tier of hours to get really good at

on the flipside there are games which are really difficult to pathfind high skill for but have pretty low skilled playerbases just due to the game not being too large or optimized

hardest for me is the clear intersection between high skill game / high skill floor community / not very path agnostic

this is still just a cartoon though there's lots of factors which cause little carve out exceptions

games which more intense physical requirements like tac shooters / dance games I guess

but as a first order approximation this is how I think of it, at least

(ycz objection: account for existence of tools and materials to help you improve)
