#+Title: TODO
* Planetbanatt.net TODO list

There are lots of things I still need to do for this website. 

** Website TODOs

- *Links Page Updates Through July*: As always I have fallen behind on this
- *Fix code syntax highlighting*: This was broken at some point
- *Overall code cleanup*: Lots of hacky stuff needs improving
- *SSBMRank Portal*: Data stuff can probably be linked to from the recently refactored Melee tab.
- *Youtube Channel scrape for vods viewer*: Not sure how much I want to dig into this but too much stuff does not leverage the liquipedia API as I thought

** Article TODOs

- *Learning Riichi Mahjong*
- *Arcades as Multi-Arm Bandit Problem Article*
- *CRT Technology and Downstream Game Design*
- *Anime and Transhumanism Article*
- *Post Training LLMs Article*
- *Read more Deep RL Papers*

** System TODOs

- loop in LLM for website work management. Maybe scratchpad document which gets sorted into notebook bins. Streamline notetaking from single text input buffer into several distinct destinations. 

Overall there's still way too much manually moving things around. There's a vision of putting stuff in and having it appear inside here somewhere and then being able to spend all the time just thinking as much as possible. Need to make that something more like a reality. 
