#+Title: TODO
* Planetbanatt.net TODO list

There are lots of things I still need to do for this website. 

** Website TODOs

- *Dark Mode*: This would be nice as a toggle, ideally with preference stored in browser storage or something, just to make it a little more readable in the evenings. Would need to play nice on mobile. Would also need to have a good vibe.
- *Links Page Updates Through July*: As always I have fallen behind on this
- *Fix code syntax highlighting*: This was broken at some point
- *Overall code cleanup*: Lots of hacky stuff needs improving
- *SSBMRank Portal*: Data stuff can probably be linked to from the recently refactored Melee tab.
- *Youtube Channel scrape for vods viewer*: Not sure how much I want to dig into this but too much stuff does not leverage the liquipedia API as I thought
- *Practice Scheduler Work*: Needs to be done when I get through all my savestates at least once, no point in working on it before then. 

** Article TODOs

- *DeepSeek Part II Update*: Need to add R1 paper summary to this page
- *LLMs as Modern Montessori Article*: Briefly abandoned out of skittishness for controversy 
- *Anime and Transhumanism Article*
- *Arcades as Multi-Arm Bandit Problem Article*
- *Post Training LLMs Article*
- *Read more Deep RL Papers*

** System TODOs

- Figure out some way to wirelessly send savestates from my computer to my CRT without using a flash drive. GCMM is workable but extremely annoying.
- Figure out some way to organize savestates in folders, and then use individual small memory cards instead of the huge one with the buttons (slow)
- Figure out llm driven system for me to dump stuff into unread -> have that stuff get sorted and presented to me in some sort of order.

Overall there's still way too much manually moving things around. There's a vision of putting stuff in and having it appear inside here somewhere and then being able to spend all the time just thinking as much as possible. Need to make that something more like a reality. 
